var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");
'use strict';var hv,iv,jv,kv,lv,mv,ov,pv,qv,rv,sv,Zba,aca,tv,uv,vv,wv,gca,xv,yv,zv,Av,Bv,Cv,Dv,Ev,Fv,Gv,Hv,Iv,Jv,Kv,Lv,Mv,Nv,Ov,Pv,Qv,Rv,Sv,Tv,Uv,Vv,Wv,Xv,Yv,Zv,$v;hv=function(a){this.f=a;this.yd=null;this.D=32768;this.K=0};iv=function(a){return $CLJS.Q.h($CLJS.r(Nba),a)};jv=function(a){return $CLJS.Q.h($CLJS.r(Oba),a)};kv=function(a){return $CLJS.Q.h($CLJS.r(Pba),a)};lv=function(a){return $CLJS.Q.h($CLJS.r(Qba),a)};mv=function(a){return $CLJS.Q.h($CLJS.r(Rba),a)};
$CLJS.nv=function(a){return $CLJS.Q.h($CLJS.r(Sba),a)};ov=function(a){return $CLJS.Q.h($CLJS.r(Tba),a)};pv=function(a){return $CLJS.Q.h($CLJS.r(Uba),a)};qv=function(a){return $CLJS.Q.h($CLJS.r(Vba),a)};rv=function(a){return $CLJS.Q.h($CLJS.r(Wba),a)};sv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(Xba)};Zba=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(Yba)};
aca=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r($ba)};tv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(bca)};uv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(cca)};vv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(dca)};
wv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(eca)};gca=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(fca)};xv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(hca)};yv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(ica)};
zv=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(jca)};Av=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.r(kca)};Bv=function(a){return null!=$CLJS.sf(a)};Cv={};Dv={};Ev={};Fv=new $CLJS.w("clojure.test.check.generators","boolean","clojure.test.check.generators/boolean",1586992347,null);
Gv=new $CLJS.w("clojure.test.check.generators","one-of","clojure.test.check.generators/one-of",-183339191,null);Hv=new $CLJS.w("clojure.test.check.generators","elements","clojure.test.check.generators/elements",438991326,null);Iv=new $CLJS.w("clojure.test.check.generators","return","clojure.test.check.generators/return",1744522038,null);Jv=new $CLJS.w("clojure.test.check.generators","keyword-ns","clojure.test.check.generators/keyword-ns",-1492628482,null);
Kv=new $CLJS.w("clojure.test.check.generators","symbol-ns","clojure.test.check.generators/symbol-ns",-862629490,null);Lv=new $CLJS.w("clojure.test.check.generators","large-integer*","clojure.test.check.generators/large-integer*",-437830670,null);Mv=new $CLJS.w("clojure.test.check.generators","any-printable","clojure.test.check.generators/any-printable",-1570493991,null);Nv=new $CLJS.w("clojure.test.check.generators","set","clojure.test.check.generators/set",-1027639543,null);
Ov=new $CLJS.w("clojure.test.check.generators","large-integer","clojure.test.check.generators/large-integer",-865967138,null);Pv=new $CLJS.w("clojure.test.check.generators","double","clojure.test.check.generators/double",668331090,null);Qv=new $CLJS.w("clojure.test.check.generators","keyword","clojure.test.check.generators/keyword",24530530,null);Rv=new $CLJS.w("clojure.test.check.generators","char","clojure.test.check.generators/char",-1426343459,null);
Sv=new $CLJS.w("clojure.test.check.generators","fmap","clojure.test.check.generators/fmap",1957997092,null);Tv=new $CLJS.w("clojure.test.check.generators","uuid","clojure.test.check.generators/uuid",1589373144,null);Uv=new $CLJS.w("clojure.test.check.generators","list","clojure.test.check.generators/list",506971058,null);Vv=new $CLJS.w("clojure.test.check.generators","string-alphanumeric","clojure.test.check.generators/string-alphanumeric",836374939,null);
Wv=new $CLJS.w("clojure.test.check.generators","such-that","clojure.test.check.generators/such-that",-1754178732,null);Xv=new $CLJS.w("clojure.test.check.generators","map","clojure.test.check.generators/map",45738796,null);Yv=new $CLJS.w("clojure.test.check.generators","vector","clojure.test.check.generators/vector",1081775325,null);Zv=new $CLJS.w("clojure.test.check.generators","symbol","clojure.test.check.generators/symbol",-1305461065,null);
$v=new $CLJS.w("clojure.test.check.generators","simple-type-printable","clojure.test.check.generators/simple-type-printable",-58489962,null);var Nba,Oba,Pba,Qba,Rba,Sba,Tba,Uba,Vba,Wba,Xba,Yba,$ba,bca,cca,dca,eca,fca,hca,ica,jca,kca;hv.prototype.jc=function(){if(null!=this.yd)return this.yd;var a=this.f.A?this.f.A():this.f.call(null);null!=a&&(this.yd=a);return a};Nba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.bw)return $CLJS.bw;throw Error(["Var ",$CLJS.p.g(Uv)," does not exist, ",$CLJS.sf(Uv)," never required"].join(""));});
Oba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.cw)return $CLJS.cw;throw Error(["Var ",$CLJS.p.g(Xv)," does not exist, ",$CLJS.sf(Xv)," never required"].join(""));});
Pba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.dw)return $CLJS.dw;throw Error(["Var ",$CLJS.p.g(Nv)," does not exist, ",$CLJS.sf(Nv)," never required"].join(""));});
Qba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.ew)return $CLJS.ew;throw Error(["Var ",$CLJS.p.g(Yv)," does not exist, ",$CLJS.sf(Yv)," never required"].join(""));});
Rba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.fw)return $CLJS.fw;throw Error(["Var ",$CLJS.p.g(Sv)," does not exist, ",$CLJS.sf(Sv)," never required"].join(""));});
Sba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.gw)return $CLJS.gw;throw Error(["Var ",$CLJS.p.g(Hv)," does not exist, ",$CLJS.sf(Hv)," never required"].join(""));});
Tba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.hw)return $CLJS.hw;throw Error(["Var ",$CLJS.p.g(Gv)," does not exist, ",$CLJS.sf(Gv)," never required"].join(""));});
Uba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.iw)return $CLJS.iw;throw Error(["Var ",$CLJS.p.g(Wv)," does not exist, ",$CLJS.sf(Wv)," never required"].join(""));});
Vba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.jw)return $CLJS.jw;throw Error(["Var ",$CLJS.p.g(Iv)," does not exist, ",$CLJS.sf(Iv)," never required"].join(""));});
Wba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.kw)return $CLJS.kw;throw Error(["Var ",$CLJS.p.g(Lv)," does not exist, ",$CLJS.sf(Lv)," never required"].join(""));});
Xba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.lw)return $CLJS.lw;throw Error(["Var ",$CLJS.p.g(Mv)," does not exist, ",$CLJS.sf(Mv)," never required"].join(""));});
Yba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.mw)return $CLJS.mw;throw Error(["Var ",$CLJS.p.g(Fv)," does not exist, ",$CLJS.sf(Fv)," never required"].join(""));});
$ba=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.nw)return $CLJS.nw;throw Error(["Var ",$CLJS.p.g(Rv)," does not exist, ",$CLJS.sf(Rv)," never required"].join(""));});
bca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.ow)return $CLJS.ow;throw Error(["Var ",$CLJS.p.g(Pv)," does not exist, ",$CLJS.sf(Pv)," never required"].join(""));});
cca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.pw)return $CLJS.pw;throw Error(["Var ",$CLJS.p.g(Qv)," does not exist, ",$CLJS.sf(Qv)," never required"].join(""));});
dca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.qw)return $CLJS.qw;throw Error(["Var ",$CLJS.p.g(Jv)," does not exist, ",$CLJS.sf(Jv)," never required"].join(""));});
eca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.rw)return $CLJS.rw;throw Error(["Var ",$CLJS.p.g(Ov)," does not exist, ",$CLJS.sf(Ov)," never required"].join(""));});
fca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.sw)return $CLJS.sw;throw Error(["Var ",$CLJS.p.g($v)," does not exist, ",$CLJS.sf($v)," never required"].join(""));});
hca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.tw)return $CLJS.tw;throw Error(["Var ",$CLJS.p.g(Vv)," does not exist, ",$CLJS.sf(Vv)," never required"].join(""));});
ica=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.uw)return $CLJS.uw;throw Error(["Var ",$CLJS.p.g(Zv)," does not exist, ",$CLJS.sf(Zv)," never required"].join(""));});
jca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.vw)return $CLJS.vw;throw Error(["Var ",$CLJS.p.g(Kv)," does not exist, ",$CLJS.sf(Kv)," never required"].join(""));});
kca=new hv(function(){if("undefined"!==typeof Cv&&"undefined"!==typeof Dv&&"undefined"!==typeof Ev&&"undefined"!==typeof $CLJS.aw&&"undefined"!==typeof $CLJS.ww)return $CLJS.ww;throw Error(["Var ",$CLJS.p.g(Tv)," does not exist, ",$CLJS.sf(Tv)," never required"].join(""));});
$CLJS.lca=new $CLJS.dj(function(){var a=gca();return $CLJS.Yh([$CLJS.zf,$CLJS.we,$CLJS.qe,$CLJS.Lb,$CLJS.ve,$CLJS.Kb,$CLJS.Gb,$CLJS.Gd,$CLJS.wf,$CLJS.ne,$CLJS.Fe,$CLJS.le,$CLJS.oe,$CLJS.je,$CLJS.Jb,$CLJS.Ij,$CLJS.Ge,$CLJS.Be,$CLJS.me,$CLJS.rf,$CLJS.Td,$CLJS.ef,$CLJS.yf,$CLJS.De,$CLJS.Bb,$CLJS.tf,$CLJS.vf,$CLJS.ue,$CLJS.Ae,$CLJS.Ee,$CLJS.Ce,$CLJS.Bj,$CLJS.te,$CLJS.kf,$CLJS.uf,$CLJS.Db,$CLJS.xf,$CLJS.xe,$CLJS.rd,$CLJS.ke],[pv($CLJS.J([Bv,vv()])),iv($CLJS.J([a])),lv($CLJS.J([a])),ov($CLJS.J([new $CLJS.R(null,
2,5,$CLJS.S,[qv($CLJS.J([null])),sv()],null)])),Zba(),aca(),pv($CLJS.J([$CLJS.Gb,sv()])),mv($CLJS.J([function(b){return new Date(b)},wv()])),yv(),ov($CLJS.J([new $CLJS.R(null,2,5,$CLJS.S,[iv($CLJS.J([a])),lv($CLJS.J([a]))],null)])),tv(),kv($CLJS.J([a])),jv($CLJS.J([a,a])),$CLJS.nv($CLJS.J([new $CLJS.R(null,5,5,$CLJS.S,[null,$CLJS.yd,$CLJS.Rg,$CLJS.P,$CLJS.ui],null)])),xv(),mv($CLJS.J([function(b){return new $CLJS.kb(["http://",$CLJS.p.g(b),".com"].join(""))},Av()])),tv(),wv(),ov($CLJS.J([new $CLJS.R(null,
2,5,$CLJS.S,[jv($CLJS.J([a,a])),lv($CLJS.J([a]))],null)])),vv(),lv($CLJS.J([a])),qv($CLJS.J([0])),uv(),rv($CLJS.J([new $CLJS.k(null,1,[$CLJS.cm,-1],null)])),qv($CLJS.J([null])),ov($CLJS.J([new $CLJS.R(null,2,5,$CLJS.S,[vv(),zv()],null)])),pv($CLJS.J([Bv,ov($CLJS.J([new $CLJS.R(null,2,5,$CLJS.S,[vv(),zv()],null)]))])),qv($CLJS.J([!0])),wv(),rv($CLJS.J([new $CLJS.k(null,1,[$CLJS.vk,0],null)])),rv($CLJS.J([new $CLJS.k(null,1,[$CLJS.vk,1],null)])),Av(),qv($CLJS.J([!1])),iv($CLJS.J([a])),ov($CLJS.J([new $CLJS.R(null,
2,5,$CLJS.S,[uv(),yv()],null)])),ov($CLJS.J([new $CLJS.R(null,2,5,$CLJS.S,[wv(),tv()],null)])),pv($CLJS.J([Bv,zv()])),ov($CLJS.J([new $CLJS.R(null,6,5,$CLJS.S,[qv($CLJS.J([null])),iv($CLJS.J([a])),lv($CLJS.J([a])),jv($CLJS.J([a,a])),kv($CLJS.J([a])),xv()],null)])),zv(),ov($CLJS.J([new $CLJS.R(null,4,5,$CLJS.S,[jv($CLJS.J([a,a])),iv($CLJS.J([a])),lv($CLJS.J([a])),kv($CLJS.J([a]))],null)]))])});