var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.set.js");
'use strict';var rz,tda,uda,uz,vda,xz,yz;
$CLJS.qz=function(a,b,c){return function(){function d(q,u,v){return a.S?a.S(b,c,q,u,v):a.call(null,b,c,q,u,v)}function e(q,u){return a.C?a.C(b,c,q,u):a.call(null,b,c,q,u)}function f(q){return a.j?a.j(b,c,q):a.call(null,b,c,q)}function g(){return a.h?a.h(b,c):a.call(null,b,c)}var l=null,n=function(){function q(v,x,z,B){var H=null;if(3<arguments.length){H=0;for(var I=Array(arguments.length-3);H<I.length;)I[H]=arguments[H+3],++H;H=new $CLJS.y(I,0,null)}return u.call(this,v,x,z,H)}function u(v,x,z,B){return $CLJS.Q.l(a,
b,c,v,x,$CLJS.J([z,B]))}q.v=3;q.B=function(v){var x=$CLJS.C(v);v=$CLJS.D(v);var z=$CLJS.C(v);v=$CLJS.D(v);var B=$CLJS.C(v);v=$CLJS.zd(v);return u(x,z,B,v)};q.l=u;return q}();l=function(q,u,v,x){switch(arguments.length){case 0:return g.call(this);case 1:return f.call(this,q);case 2:return e.call(this,q,u);case 3:return d.call(this,q,u,v);default:var z=null;if(3<arguments.length){z=0;for(var B=Array(arguments.length-3);z<B.length;)B[z]=arguments[z+3],++z;z=new $CLJS.y(B,0,null)}return n.l(q,u,v,z)}throw Error("Invalid arity: "+
arguments.length);};l.v=3;l.B=n.B;l.A=g;l.g=f;l.h=e;l.j=d;l.l=n.l;return l}()};rz=function(a,b){return $CLJS.F.h(a,b)?new $CLJS.R(null,3,5,$CLJS.S,[null,null,a],null):new $CLJS.R(null,3,5,$CLJS.S,[a,b,null],null)};tda=function(a){return $CLJS.A(a)?$CLJS.Tb(function(b,c){var d=$CLJS.K(c,0,null);c=$CLJS.K(c,1,null);return $CLJS.U.j(b,d,c)},$CLJS.Sg($CLJS.tg($CLJS.Q.h($CLJS.Om,$CLJS.mi(a)),null)),a):null};
uda=function(a,b,c){var d=$CLJS.M.h(a,c),e=$CLJS.M.h(b,c),f=$CLJS.sz(d,e),g=$CLJS.K(f,0,null),l=$CLJS.K(f,1,null);f=$CLJS.K(f,2,null);a=$CLJS.Ie(a,c);b=$CLJS.Ie(b,c);d=a&&b&&(null!=f||null==d&&null==e);return new $CLJS.R(null,3,5,$CLJS.S,[!a||null==g&&d?null:$CLJS.Tf([c,g]),!b||null==l&&d?null:$CLJS.Tf([c,l]),d?$CLJS.Tf([c,f]):null],null)};
uz=function(a,b){var c=$CLJS.xg.h,d=tz.j,e=$CLJS.qe(a)?a:$CLJS.Sg(a),f=$CLJS.qe(b)?b:$CLJS.Sg(b);a=$CLJS.E(a);b=$CLJS.E(b);return $CLJS.Sg(c.call($CLJS.xg,tda,d.call(tz,e,f,$CLJS.Gi(0,a>b?a:b))))};vda=function(a,b){return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Vf($CLJS.vz.h(a,b)),$CLJS.Vf($CLJS.vz.h(b,a)),$CLJS.Vf($CLJS.wz.h(a,b))],null)};
xz=function(a){if(null!=a&&null!=a.Hh)a=a.Hh(a);else{var b=xz[$CLJS.Na(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=xz._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Ob("EqualityPartition.equality-partition",a);}return a};yz=function(a,b){if(null!=a&&null!=a.Gh)a=a.Gh(a,b);else{var c=yz[$CLJS.Na(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=yz._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $CLJS.Ob("Diff.diff-similar",a);}return a};
$CLJS.sz=function(a,b){return $CLJS.F.h(a,b)?new $CLJS.R(null,3,5,$CLJS.S,[null,null,a],null):$CLJS.F.h(xz(a),xz(b))?yz(a,b):rz(a,b)};$CLJS.vz=function vz(a){switch(arguments.length){case 1:return vz.g(arguments[0]);case 2:return vz.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return vz.l(arguments[0],arguments[1],new $CLJS.y(c.slice(2),0,null))}};$CLJS.vz.g=function(a){return a};
$CLJS.vz.h=function(a,b){return $CLJS.E(a)<$CLJS.E(b)?$CLJS.Tb(function(c,d){return $CLJS.Ie(b,d)?$CLJS.Km.h(c,d):c},a,a):$CLJS.Tb($CLJS.Km,a,b)};$CLJS.vz.l=function(a,b,c){return $CLJS.Tb($CLJS.vz,a,$CLJS.mf.h(c,b))};$CLJS.vz.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);c=$CLJS.D(c);return this.l(b,a,c)};$CLJS.vz.v=2;
$CLJS.wz=function wz(a){switch(arguments.length){case 1:return wz.g(arguments[0]);case 2:return wz.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return wz.l(arguments[0],arguments[1],new $CLJS.y(c.slice(2),0,null))}};$CLJS.wz.g=function(a){return a};
$CLJS.wz.h=function(a,b){for(;;)if($CLJS.E(b)<$CLJS.E(a)){var c=a;a=b;b=c}else return $CLJS.Tb(function(d,e){return function(f,g){return $CLJS.Ie(e,g)?f:$CLJS.Km.h(f,g)}}(a,b),a,a)};$CLJS.wz.l=function(a,b,c){a=$CLJS.jz(function(d){return-$CLJS.E(d)},$CLJS.mf.l(c,b,$CLJS.J([a])));return $CLJS.Tb($CLJS.wz,$CLJS.C(a),$CLJS.zd(a))};$CLJS.wz.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);c=$CLJS.D(c);return this.l(b,a,c)};$CLJS.wz.v=2;var zz=new $CLJS.N(null,"atom","atom",-397043653);var tz=function tz(a){switch(arguments.length){case 2:return tz.h(arguments[0],arguments[1]);case 3:return tz.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};tz.h=function(a,b){return tz.j(a,b,$CLJS.pz.h($CLJS.mi(a),$CLJS.mi(b)))};tz.j=function(a,b,c){return $CLJS.Tb(function(d,e){return $CLJS.Ii($CLJS.xg.j($CLJS.mn,d,e))},new $CLJS.R(null,3,5,$CLJS.S,[null,null,null],null),$CLJS.xg.h($CLJS.qz(uda,a,b),c))};tz.v=3;
xz["null"]=function(){return zz};xz.string=function(){return zz};xz.number=function(){return zz};xz.array=function(){return $CLJS.rl};xz["function"]=function(){return zz};xz["boolean"]=function(){return zz};
xz._=function(a){return(null!=a?a.D&1024||$CLJS.t===a.vh||(a.D?0:$CLJS.Mb($CLJS.rc,a)):$CLJS.Mb($CLJS.rc,a))?$CLJS.bm:(null!=a?a.D&4096||$CLJS.t===a.zh||(a.D?0:$CLJS.Mb($CLJS.vc,a)):$CLJS.Mb($CLJS.vc,a))?$CLJS.Mk:(null!=a?a.D&16777216||$CLJS.t===a.Rf||(a.D?0:$CLJS.Mb($CLJS.Lc,a)):$CLJS.Mb($CLJS.Lc,a))?$CLJS.rl:zz};yz["null"]=function(a,b){return rz(a,b)};yz.string=function(a,b){return rz(a,b)};yz.number=function(a,b){return rz(a,b)};yz.array=function(a,b){return uz(a,b)};
yz["function"]=function(a,b){return rz(a,b)};yz["boolean"]=function(a,b){return rz(a,b)};yz._=function(a,b){var c=function(){var d=xz(a);d=d instanceof $CLJS.N?d.N:null;switch(d){case "atom":return rz;case "set":return vda;case "sequential":return uz;case "map":return tz;default:throw Error(["No matching clause: ",$CLJS.p.g(d)].join(""));}}();return c.h?c.h(a,b):c.call(null,a,b)};