var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./clojure.walk.js");require("./no.en.core.js");
'use strict';var BG,dga,CG,GG,IG;BG=function(a,b,c,d,e){this.pattern=a;this.ed=b;this.F=c;this.m=d;this.G=e;this.D=2230716170;this.K=139264};dga=function(a,b){return new BG(a,b,null,null,null)};CG=function(a,b){$CLJS.Ie($CLJS.yi($CLJS.r(a)),b)||$CLJS.jj.j(a,$CLJS.mf,b)};$CLJS.DG=function(a){if(null==a||"string"===typeof a)return a;if(a instanceof $CLJS.N||a instanceof $CLJS.w){var b=$CLJS.sf(a);return $CLJS.m(b)?[b,"/",$CLJS.Ai(a)].join(""):$CLJS.Ai(a)}return null};
GG=function(a){a=$CLJS.A($CLJS.Q.h(EG,a));for(var b=null,c=0,d=0;;)if(d<c){var e=b.aa(null,d);CG($CLJS.FG,e);d+=1}else if(a=$CLJS.A(a))b=a,$CLJS.re(b)?(a=$CLJS.$c(b),c=$CLJS.ad(b),b=a,e=$CLJS.E(a),a=c,c=e):(e=$CLJS.C(b),CG($CLJS.FG,e),a=$CLJS.D(b),b=null,c=0),d=0;else break};
IG=function(a){a=$CLJS.A($CLJS.Q.h(EG,a));for(var b=null,c=0,d=0;;)if(d<c){var e=b.aa(null,d);CG(HG,e);d+=1}else if(a=$CLJS.A(a))b=a,$CLJS.re(b)?(a=$CLJS.$c(b),c=$CLJS.ad(b),b=a,e=$CLJS.E(a),a=c,c=e):(e=$CLJS.C(b),CG(HG,e),a=$CLJS.D(b),b=null,c=0),d=0;else break};var HG,KG;$CLJS.h=BG.prototype;$CLJS.h.ka=function(a,b){return this.U(null,b,null)};$CLJS.h.U=function(a,b,c){switch(b instanceof $CLJS.N?b.N:null){case "pattern":return this.pattern;case "replacement":return this.ed;default:return $CLJS.M.j(this.m,b,c)}};$CLJS.h.va=function(a,b,c){return $CLJS.Tb(function(d,e){var f=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);return b.j?b.j(d,f,e):b.call(null,d,f,e)},c,this)};
$CLJS.h.W=function(a,b,c){return $CLJS.Oi(b,function(d){return $CLJS.Oi(b,$CLJS.Ti,""," ","",c,d)},"#inflections.core.Rule{",", ","}",c,$CLJS.wg.h(new $CLJS.R(null,2,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Du,this.pattern],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Iu,this.ed],null)],null),this.m))};$CLJS.h.oa=function(){return new $CLJS.jh(this,2,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Du,$CLJS.Iu],null),$CLJS.m(this.m)?$CLJS.fd(this.m):$CLJS.Xf())};$CLJS.h.M=function(){return this.F};
$CLJS.h.ea=function(){return 2+$CLJS.E(this.m)};$CLJS.h.ca=function(){var a=this.G;return null!=a?a:this.G=a=-1327743444^$CLJS.Ed(this)};$CLJS.h.T=function(a,b){return null!=b&&this.constructor===b.constructor&&$CLJS.F.h(this.pattern,b.pattern)&&$CLJS.F.h(this.ed,b.ed)&&$CLJS.F.h(this.m,b.m)};
$CLJS.h.za=function(a,b){return $CLJS.Ie(new $CLJS.ti(null,new $CLJS.k(null,2,[$CLJS.Iu,null,$CLJS.Du,null],null),null),b)?$CLJS.Jm.h($CLJS.Dc($CLJS.th.h($CLJS.P,this),this.F),b):new BG(this.pattern,this.ed,this.F,$CLJS.Vf($CLJS.Jm.h(this.m,b)),null)};$CLJS.h.ta=function(a,b){switch(b instanceof $CLJS.N?b.N:null){case "pattern":case "replacement":return!0;default:return $CLJS.Ie(this.m,b)}};
$CLJS.h.$=function(a,b,c){return $CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.Du,b):$CLJS.O.call(null,$CLJS.Du,b))?new BG(c,this.ed,this.F,this.m,null):$CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.Iu,b):$CLJS.O.call(null,$CLJS.Iu,b))?new BG(this.pattern,c,this.F,this.m,null):new BG(this.pattern,this.ed,this.F,$CLJS.U.j(this.m,b,c),null)};$CLJS.h.da=function(){return $CLJS.A($CLJS.wg.h(new $CLJS.R(null,2,5,$CLJS.S,[new $CLJS.Ke($CLJS.Du,this.pattern),new $CLJS.Ke($CLJS.Iu,this.ed)],null),this.m))};
$CLJS.h.O=function(a,b){return new BG(this.pattern,this.ed,b,this.m,this.G)};$CLJS.h.ja=function(a,b){return $CLJS.qe(b)?this.$(null,$CLJS.be(b,0),$CLJS.be(b,1)):$CLJS.Tb($CLJS.dc,this,b)};var EG=function EG(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return EG.l(0<c.length?new $CLJS.y(c.slice(0),0,null):null)};EG.l=function(a){return $CLJS.xg.h(function(b){return $CLJS.Q.h(dga,b)},$CLJS.fu(2,2,a))};EG.v=0;EG.B=function(a){return this.l($CLJS.A(a))};
$CLJS.JG=$CLJS.ij.g(new $CLJS.ti(null,new $CLJS.k(null,81,["gossip",null,"sadness",null,"space",null,"happiness",null,"blood",null,"silver",null,"cotton",null,"species",null,"mist",null,"paper",null,"education",null,"wine",null,"up",null,"food",null,"sugar",null,"gold",null,"literature",null,"pork",null,"lightning",null,"sheep",null,"shopping",null,"fresh",null,"news",null,"pepper",null,"experience",null,"milk",null,"honey",null,"oxygen",null,"fiction",null,"luck",null,"vinegar",null,"coffee",null,
"ground",null,"peanut",null,"confusion",null,"tennis",null,"power",null,"meat",null,"butter",null,"music",null,"luggage",null,"love",null,"grass",null,"knowledge",null,"time",null,"cheese",null,"jam",null,"thunder",null,"electricity",null,"gum",null,"sunshine",null,"history",null,"snow",null,"money",null,"wool",null,"rice",null,"series",null,"liquid",null,"equipment",null,"pressure",null,"oil",null,"information",null,"steam",null,"chewing",null,"petrol",null,"research",null,"patience",null,"toothpaste",
null,"speed",null,"entertainment",null,"wood",null,"tea",null,"art",null,"washing",null,"forgiveness",null,"traffic",null,"alcohol",null,"ice",null,"homework",null,"fish",null,"air",null],null),null));$CLJS.ij.g(new $CLJS.k(null,2,["hst","HST","nasa","NASA"],null));$CLJS.FG=$CLJS.ij.g($CLJS.Rg);HG=$CLJS.ij.g($CLJS.Rg);
KG=$CLJS.ij.g(function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.Tb($CLJS.dc,$CLJS.nn,0<b.length?new $CLJS.y(b.slice(0),0,null):null)}());
GG($CLJS.J([/$/i,"s",/s$/i,"s",/(ax|test)is$/i,"$1es",/(octop|vir)us$/i,"$1i",/(alias|status)$/i,"$1es",/(bu)s$/i,"$1ses",/(buffal|tomat)o$/i,"$1oes",/([ti])um$/i,"$1a",/sis$/i,"ses",/(?:([^f])fe|([lr])f)$/i,"$1$2ves",/(hive)$/i,"$1s",/([^aeiouy]|qu)y$/i,"$1ies",/(x|ch|ss|sh)$/i,"$1es",/(matr|vert|ind)(?:ix|ex)$/i,"$1ices",/([m|l])ouse$/i,"$1ice",/^(ox)$/i,"$1en",/(quiz)$/i,"$1zes"]));
IG($CLJS.J([/s$/i,"",/(ss)$/i,"$1",/(n)ews$/i,"$1ews",/([ti])a$/i,"$1um",/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)(sis|ses)$/i,"$1$2sis",/(^analy)(sis|ses)$/i,"$1sis",/([^f])ves$/i,"$1fe",/(hive)s$/i,"$1",/(tive)s$/i,"$1",/([lr])ves$/i,"$1f",/([^aeiouy]|qu)ies$/i,"$1y",/(s)eries$/i,"$1eries",/(m)ovies$/i,"$1ovie",/(x|ch|ss|sh)es$/i,"$1",/([m|l])ice$/i,"$1ouse",/(bus)(es)?$/i,"$1",/(o)es$/i,"$1",/(shoe)s$/i,"$1",/(cris|ax|test)(is|es)$/i,"$1is",/(octop|vir)(us|i)$/i,"$1us",/(alias|status)(es)?$/i,
"$1",/^(ox)en/i,"$1",/(vert|ind)ices$/i,"$1ex",/(matr)ices$/i,"$1ix",/(quiz)zes$/i,"$1",/(database)s$/i,"$1"]));
$CLJS.Ii($CLJS.xg.h(function(a){var b=$CLJS.C(a);a=$CLJS.Zd(a);b=$CLJS.DG(b).toLowerCase();a=$CLJS.DG(a).toLowerCase();$CLJS.jj.j($CLJS.JG,$CLJS.Km,$CLJS.DG(b).toLowerCase());$CLJS.jj.j($CLJS.JG,$CLJS.Km,$CLJS.DG(a).toLowerCase());IG($CLJS.J([$CLJS.Li(["^",a,"$"].join("")),b]));GG($CLJS.J([$CLJS.Li(["^",b,"$"].join("")),a]));$CLJS.jj.j(KG,$CLJS.mf,b);return $CLJS.jj.j(KG,$CLJS.mf,a)},new $CLJS.R(null,14,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,["amenity","amenities"],null),new $CLJS.R(null,2,5,$CLJS.S,
["child","children"],null),new $CLJS.R(null,2,5,$CLJS.S,["cow","kine"],null),new $CLJS.R(null,2,5,$CLJS.S,["foot","feet"],null),new $CLJS.R(null,2,5,$CLJS.S,["louse","lice"],null),new $CLJS.R(null,2,5,$CLJS.S,["mailman","mailmen"],null),new $CLJS.R(null,2,5,$CLJS.S,["man","men"],null),new $CLJS.R(null,2,5,$CLJS.S,["mouse","mice"],null),new $CLJS.R(null,2,5,$CLJS.S,["move","moves"],null),new $CLJS.R(null,2,5,$CLJS.S,["ox","oxen"],null),new $CLJS.R(null,2,5,$CLJS.S,["person","people"],null),new $CLJS.R(null,
2,5,$CLJS.S,["sex","sexes"],null),new $CLJS.R(null,2,5,$CLJS.S,["tooth","teeth"],null),new $CLJS.R(null,2,5,$CLJS.S,["woman","women"],null)],null)));