var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./lambdaisland.glogi.js");require("./lambdaisland.glogi.print.js");
'use strict';var OE=function(){},PE=function(a){var b=$CLJS.K(a,0,null);a=$CLJS.K(a,1,null);return new $CLJS.R(null,2,5,$CLJS.S,[[$CLJS.p.g(b),$CLJS.p.g(" ")].join(""),a],null)},QE=function(a,b,c){var d=$CLJS.K(a,0,null);a=$CLJS.K(a,1,null);return new $CLJS.R(null,2,5,$CLJS.S,[[$CLJS.p.g(d),"%c",$CLJS.p.g(b),"%c"].join(""),$CLJS.mf.l(a,["color:",$CLJS.p.g($CLJS.M.h($CLJS.NE,$CLJS.LE)),";background-color:",$CLJS.p.g($CLJS.M.h($CLJS.NE,c))].join(""),$CLJS.J(["color:black;background-color:inherit"]))],
null)},RE=function(a,b,c){var d=$CLJS.K(a,0,null);a=$CLJS.K(a,1,null);return new $CLJS.R(null,2,5,$CLJS.S,[[$CLJS.p.g(d),"%c",$CLJS.p.g(b),"%c"].join(""),$CLJS.mf.l(a,["color:",$CLJS.p.g($CLJS.M.h($CLJS.NE,c))].join(""),$CLJS.J(["color:black"]))],null)},SE=function(a){return $CLJS.M.h($CLJS.ED,a).value},vfa=function(a){var b=SE(a);return $CLJS.m(function(){var c=SE($CLJS.UD);return $CLJS.Nm.h?$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.zE:$CLJS.m(function(){var c=SE($CLJS.TD);return $CLJS.Nm.h?
$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.JE:$CLJS.m(function(){var c=SE($CLJS.RD);return $CLJS.Nm.h?$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.CE:$CLJS.m(function(){var c=SE($CLJS.MD);return $CLJS.Nm.h?$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.IE:$CLJS.m(function(){var c=SE($CLJS.SD);return $CLJS.Nm.h?$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.KE:$CLJS.m(function(){var c=SE($CLJS.OD);return $CLJS.Nm.h?$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.FE:$CLJS.m(function(){var c=
SE($CLJS.JD);return $CLJS.Nm.h?$CLJS.Nm.h(c,b):$CLJS.Nm.call(null,c,b)}())?$CLJS.GE:$CLJS.HE},wfa=function(a){function b(c,d){return d>=c}a=SE(a);if(b(SE($CLJS.UD),a))return"error";if(b(SE($CLJS.TD),a))return"warn";if(b(SE($CLJS.RD),a))return"info";b(SE($CLJS.MD),a);return"log"},TE=function(a){return function(b){var c=$CLJS.Uf(b),d=$CLJS.M.h(c,$CLJS.KD),e=$CLJS.M.h(c,$CLJS.Qu);b=$CLJS.M.h(c,$CLJS.VD);e=wfa(e);e=$CLJS.Ua(console,e);e=$CLJS.m(e)?e:console.log;$CLJS.Q.h(e,a.g?a.g(c):a.call(null,c));
return $CLJS.m(b)?(c=["[",$CLJS.p.g(d),"]"].join(""),d=$CLJS.p.g(b),b=b.stack,e.C?e.C(c,d,"\n",b):e.call(null,c,d,"\n",b)):null}},UE=function UE(a,b){for(;;){if($CLJS.F.h($CLJS.yE,b))return RE(a,", ",$CLJS.HE);if($CLJS.F.h($CLJS.AE,b))return PE(a);if(b instanceof $CLJS.N)return RE(a,b,$CLJS.CE);if(b instanceof $CLJS.w)return RE(a,b,$CLJS.IE);if("string"===typeof b)return RE(a,$CLJS.gj.l($CLJS.J([b])),$CLJS.BE);if($CLJS.Og(b)){var d=PE(function(){var f=a,g=$CLJS.tc(b);return UE.h?UE.h(f,g):UE.call(null,
f,g)}()),e=$CLJS.uc(b);return UE.h?UE.h(d,e):UE.call(null,d,e)}if(b instanceof $CLJS.k||b instanceof $CLJS.Xh)return d=a,d=RE(d,"{",$CLJS.ME),d=$CLJS.Tb(UE,d,$CLJS.vg($CLJS.yE,b)),RE(d,"}",$CLJS.ME);if($CLJS.oe(b))return d=a,d=RE(d,["#",$CLJS.p.g(function(){var f=$CLJS.Nb(b),g=f.name;return $CLJS.je(g)?$CLJS.gj.l($CLJS.J([f])):g}())," "].join(""),$CLJS.DE),d=RE(d,"{",$CLJS.ME),d=$CLJS.Tb(UE,d,$CLJS.vg($CLJS.yE,b)),RE(d,"}",$CLJS.ME);if($CLJS.le(b))return d=a,d=RE(d,"#{",$CLJS.ME),d=$CLJS.Tb(UE,d,
$CLJS.vg($CLJS.AE,b)),RE(d,"}",$CLJS.ME);if($CLJS.qe(b))return d=a,d=RE(d,"[",$CLJS.ME),d=$CLJS.Tb(UE,d,$CLJS.vg($CLJS.AE,b)),RE(d,"]",$CLJS.ME);if(b instanceof $CLJS.fh)d=RE(a,"#queue ",$CLJS.DE),e=$CLJS.th.h($CLJS.Rg,b),a=d,b=e;else{if($CLJS.we(b))return d=a,d=RE(d,"(",$CLJS.DE),d=$CLJS.Tb(UE,d,$CLJS.vg($CLJS.AE,b)),RE(d,")",$CLJS.DE);if(null!=b?b.K&16384||$CLJS.t===b.Bj||(b.K?0:$CLJS.Mb(OE,b)):$CLJS.Mb(OE,b))d=RE(a,"#atom ",$CLJS.DE),e=$CLJS.r(b),a=d,b=e;else if($CLJS.Bj(b))d=RE(a,"#uuid ",$CLJS.DE),
e=$CLJS.p.g(b),a=d,b=e;else if($CLJS.Ib(b))d=RE(a,"#js ",$CLJS.DE),e=$CLJS.Tb(function(f,g){return function(l,n){return $CLJS.U.j(l,$CLJS.Ui.g(n),$CLJS.Ua(g,n))}}(a,b),$CLJS.P,Object.keys(b)),a=d,b=e;else if($CLJS.Cb(b))d=RE(a,"#js ",$CLJS.DE),e=$CLJS.th.h($CLJS.Rg,b),a=d,b=e;else return RE(a,$CLJS.gj.l($CLJS.J([b])),$CLJS.EE)}}};$CLJS.xfa=TE(function(a){a=$CLJS.Uf(a);$CLJS.M.h(a,$CLJS.Qu);var b=$CLJS.M.h(a,$CLJS.KD),c=$CLJS.M.h(a,$CLJS.Dk);$CLJS.M.h(a,$CLJS.VD);return new $CLJS.R(null,2,5,$CLJS.S,[["[",$CLJS.p.g(b),"]"].join(""),c],null)});
$CLJS.yfa=TE(function(a){var b=$CLJS.Uf(a),c=$CLJS.M.h(b,$CLJS.Qu);a=$CLJS.M.h(b,$CLJS.KD);var d=$CLJS.M.h(b,$CLJS.Dk);$CLJS.M.h(b,$CLJS.VD);b=vfa(c);d=UE(PE(QE(QE(QE(new $CLJS.R(null,2,5,$CLJS.S,["",$CLJS.Rg],null),"[",b),a,b),"]",b)),d);a=$CLJS.K(d,0,null);d=$CLJS.K(d,1,null);return $CLJS.pf(a,d)});
$CLJS.zfa=TE(function(a){a=$CLJS.Uf(a);$CLJS.M.h(a,$CLJS.Qu);var b=$CLJS.M.h(a,$CLJS.KD),c=$CLJS.M.h(a,$CLJS.Dk);$CLJS.M.h(a,$CLJS.VD);return new $CLJS.R(null,2,5,$CLJS.S,[["[",$CLJS.p.g(b),"]"].join(""),$CLJS.gj.l($CLJS.J([c]))],null)});