var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./metabase.types.js");require("./schema.core.js");
'use strict';var QM,RM;QM=function(a){if(null!=a&&null!=a.Md)a=a.Md(a);else{var b=QM[$CLJS.Na(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=QM._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Ob("HasPrecondition.precondition",a);}return a};RM=function(a,b,c,d){this.Pc=a;this.F=b;this.m=c;this.G=d;this.D=2230716170;this.K=139264};$CLJS.SM=function(a){return new RM(a,null,null,null)};$CLJS.AL.prototype.Md=$CLJS.Ma(59,function(){return $CLJS.dg(this.na)});
$CLJS.FL.prototype.Md=$CLJS.Ma(58,function(){var a=this;return $CLJS.Sm.h($CLJS.dg(a.na),$CLJS.Q.h($CLJS.Tm,function(){return function d(c){return new $CLJS.Af(null,function(){for(;;){var e=$CLJS.A(c);if(e){if($CLJS.re(e)){var f=$CLJS.$c(e),g=$CLJS.E(f),l=$CLJS.Df(g);a:for(var n=0;;)if(n<g){var q=$CLJS.be(f,n),u=$CLJS.Uf(q);q=$CLJS.M.h(u,$CLJS.CL);u=$CLJS.M.h(u,$CLJS.hm);q=$CLJS.m(q)?$CLJS.Sm.h(q,QM($CLJS.WL(u))):QM($CLJS.WL(u));l.add(q);n+=1}else{f=!0;break a}return f?$CLJS.If($CLJS.Kf(l),d($CLJS.ad(e))):
$CLJS.If($CLJS.Kf(l),null)}l=$CLJS.C(e);f=$CLJS.Uf(l);l=$CLJS.M.h(f,$CLJS.CL);f=$CLJS.M.h(f,$CLJS.hm);return $CLJS.pf($CLJS.m(l)?$CLJS.Sm.h(l,QM($CLJS.WL(f))):QM($CLJS.WL(f)),d($CLJS.zd(e)))}return null}},null,null)}(a.options)}()))});$CLJS.NL.prototype.Md=$CLJS.Ma(57,function(){return $CLJS.dg(this.na)});$CLJS.h=RM.prototype;$CLJS.h.ka=function(a,b){return this.U(null,b,null)};
$CLJS.h.U=function(a,b,c){switch(b instanceof $CLJS.N?b.N:null){case "schemas":return this.Pc;default:return $CLJS.M.j(this.m,b,c)}};$CLJS.h.va=function(a,b,c){return $CLJS.Tb(function(d,e){var f=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);return b.j?b.j(d,f,e):b.call(null,d,f,e)},c,this)};
$CLJS.h.W=function(a,b,c){return $CLJS.Oi(b,function(d){return $CLJS.Oi(b,$CLJS.Ti,""," ","",c,d)},"#schema.core.CondPre{",", ","}",c,$CLJS.wg.h(new $CLJS.R(null,1,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.tM,this.Pc],null)],null),this.m))};$CLJS.h.oa=function(){return new $CLJS.jh(this,1,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.tM],null),$CLJS.m(this.m)?$CLJS.fd(this.m):$CLJS.Xf())};$CLJS.h.M=function(){return this.F};$CLJS.h.ea=function(){return 1+$CLJS.E(this.m)};
$CLJS.h.ca=function(){var a=this.G;return null!=a?a:this.G=a=-56613580^$CLJS.Ed(this)};$CLJS.h.T=function(a,b){return null!=b&&this.constructor===b.constructor&&$CLJS.F.h(this.Pc,b.Pc)&&$CLJS.F.h(this.m,b.m)};$CLJS.h.za=function(a,b){return $CLJS.Ie(new $CLJS.ti(null,new $CLJS.k(null,1,[$CLJS.tM,null],null),null),b)?$CLJS.Jm.h($CLJS.Dc($CLJS.th.h($CLJS.P,this),this.F),b):new RM(this.Pc,this.F,$CLJS.Vf($CLJS.Jm.h(this.m,b)),null)};
$CLJS.h.ta=function(a,b){switch(b instanceof $CLJS.N?b.N:null){case "schemas":return!0;default:return $CLJS.Ie(this.m,b)}};$CLJS.h.$=function(a,b,c){return $CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.tM,b):$CLJS.O.call(null,$CLJS.tM,b))?new RM(c,this.F,this.m,null):new RM(this.Pc,this.F,$CLJS.U.j(this.m,b,c),null)};$CLJS.h.da=function(){return $CLJS.A($CLJS.wg.h(new $CLJS.R(null,1,5,$CLJS.S,[new $CLJS.Ke($CLJS.tM,this.Pc)],null),this.m))};$CLJS.h.O=function(a,b){return new RM(this.Pc,b,this.m,this.G)};
$CLJS.h.ja=function(a,b){return $CLJS.qe(b)?this.$(null,$CLJS.be(b,0),$CLJS.be(b,1)):$CLJS.Tb($CLJS.dc,this,b)};
$CLJS.h.Ab=function(){var a=this;return $CLJS.GL($CLJS.VL,function(){return function d(c){return new $CLJS.Af(null,function(){for(;;){var e=$CLJS.A(c);if(e){if($CLJS.re(e)){var f=$CLJS.$c(e),g=$CLJS.E(f),l=$CLJS.Df(g);a:for(var n=0;;)if(n<g){var q=$CLJS.be(f,n);q=new $CLJS.k(null,2,[$CLJS.CL,QM($CLJS.WL(q)),$CLJS.hm,q],null);l.add(q);n+=1}else{f=!0;break a}return f?$CLJS.If($CLJS.Kf(l),d($CLJS.ad(e))):$CLJS.If($CLJS.Kf(l),null)}l=$CLJS.C(e);return $CLJS.pf(new $CLJS.k(null,2,[$CLJS.CL,QM($CLJS.WL(l)),
$CLJS.hm,l],null),d($CLJS.zd(e)))}return null}},null,null)}(a.Pc)}(),function(b){return new $CLJS.jf(null,$CLJS.Eha,new $CLJS.jf(null,b,null,1,null),2,null)})};$CLJS.h.Ea=function(){return $CLJS.pf($CLJS.wha,$CLJS.xg.h($CLJS.XL,this.Pc))};$CLJS.h.ma=$CLJS.t;$CLJS.h.W=function(a,b){return $CLJS.Qc(b,this.Ea(null))};$CLJS.TM=$CLJS.fM($CLJS.LM,$CLJS.dg($CLJS.lF),"Non-blank string");$CLJS.UM=$CLJS.bM(function(a){return $CLJS.XG(a,$CLJS.sl)},"Valid field type");$CLJS.VM=$CLJS.bM(function(a){return $CLJS.XG(a,$CLJS.hl)||$CLJS.XG(a,$CLJS.Vj)},"Valid semantic type");$CLJS.WM=$CLJS.fM($CLJS.OM,$CLJS.df,"positive integer");$CLJS.XM=$CLJS.fM($CLJS.OM,$CLJS.dg($CLJS.gf),"integer \x3e\x3d 0");$CLJS.Pha=$CLJS.Tf([$CLJS.KM,$CLJS.KM]);$CLJS.Qha=$CLJS.SM($CLJS.J([$CLJS.PM,$CLJS.LM]));