var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.malli.registry.js");
'use strict';var sY,vY,xY,Qna,zY,AY;sY=new $CLJS.N("metabase.lib.schema.join","join","metabase.lib.schema.join/join",1110197236);$CLJS.tY=new $CLJS.N("mbql","join","mbql/join",-709512370);$CLJS.uY=new $CLJS.N("metabase.lib.schema","stages","metabase.lib.schema/stages",-391672350);vY=new $CLJS.N("metabase.lib.schema.join","conditions","metabase.lib.schema.join/conditions",118173612);$CLJS.wY=new $CLJS.N("metabase.lib.schema.join","joins","metabase.lib.schema.join/joins",106891649);
xY=new $CLJS.N("metabase.lib.schema.join","alias","metabase.lib.schema.join/alias",53862412);$CLJS.yY=new $CLJS.N(null,"stages","stages",-442109532);Qna=new $CLJS.N("metabase.lib.schema.join","strategy.option","metabase.lib.schema.join/strategy.option",473280855);zY=new $CLJS.N("metabase.lib.schema.join","fields","metabase.lib.schema.join/fields",391974200);AY=new $CLJS.N("metabase.lib.schema.join","strategy","metabase.lib.schema.join/strategy",1569892832);
$CLJS.BY=new $CLJS.N(null,"conditions","conditions",-1647236270);$CLJS.CY=new $CLJS.N("option","join.strategy","option/join.strategy",1337097154);$CLJS.rK(zY,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Gk,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.ot,$CLJS.ID,$CLJS.Lu],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.rl,new $CLJS.k(null,1,[$CLJS.vk,1],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.yK],null)],null)],null));$CLJS.rK(xY,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Gk,new $CLJS.k(null,1,[$CLJS.Xy,function(a){return[$CLJS.p.g(a),"-",$CLJS.p.g($CLJS.IK())].join("")}],null),$CLJS.zK],null));
$CLJS.rK(vY,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.rl,new $CLJS.k(null,1,[$CLJS.vk,1],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.SK],null)],null));$CLJS.rK(AY,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.ot,$CLJS.OI,$CLJS.jH,$CLJS.yJ,$CLJS.SJ],null));
$CLJS.rK(sY,new $CLJS.R(null,8,5,$CLJS.S,[$CLJS.bm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.wl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.tY],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.MF,$CLJS.DK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.yY,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.uY],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.BY,vY],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.qI,xY],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.AH,new $CLJS.k(null,1,[$CLJS.Wj,!0],null),zY],null),new $CLJS.R(null,
3,5,$CLJS.S,[$CLJS.dK,new $CLJS.k(null,1,[$CLJS.Wj,!0],null),AY],null)],null));
$CLJS.rK($CLJS.wY,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Qj,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.rl,new $CLJS.k(null,1,[$CLJS.vk,1],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,sY],null)],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.pt,new $CLJS.k(null,1,[$CLJS.Yu,function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(){return $CLJS.bH("Join aliases must be unique at a given stage of a query")}
a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}()],null),function(a){a=$CLJS.Vf($CLJS.Ag($CLJS.Gb,$CLJS.xg.h($CLJS.qI,a)));return $CLJS.m(a)?$CLJS.Q.h($CLJS.Cu,a):!0}],null)],null));
$CLJS.rK(Qna,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.bm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.wl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.CY],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.dK,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,AY],null)],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Uj,new $CLJS.k(null,1,[$CLJS.Wj,!0],null),$CLJS.pk],null)],null));