var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.aggregation.js");require("./metabase.lib.binning.js");require("./metabase.lib.breakout.js");require("./metabase.lib.expression.js");require("./metabase.lib.field.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.join.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.normalize.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.lib.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.malli.js");
'use strict';var E7,Vta,H7,Wta,K7,Xta,Yta,Zta,$ta,aua,bua,cua,N7,dua,P7,Q7,eua,R7;
E7=function(a){return function(b){var c=$CLJS.og($CLJS.ui);return function(){function d(l,n){var q=a.g?a.g(n):a.call(null,n);if($CLJS.Ie($CLJS.r(c),q))return l;c.Ie(null,$CLJS.mf.h(c.jc(null),q));return b.h?b.h(l,n):b.call(null,l,n)}function e(l){return b.g?b.g(l):b.call(null,l)}function f(){return b.A?b.A():b.call(null)}var g=null;g=function(l,n){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,n)}throw Error("Invalid arity: "+arguments.length);
};g.A=f;g.g=e;g.h=d;return g}()}};$CLJS.F7=function(a,b){return $CLJS.N1.h(a,b instanceof $CLJS.N?b:$CLJS.bk.g(b))};$CLJS.G7=function(a){a=$CLJS.O1.g(a);return $CLJS.m(a)?new $CLJS.k(null,2,[$CLJS.wl,$CLJS.XU,$CLJS.bk,a],null):null};Vta=function(a,b,c){return $CLJS.th.j($CLJS.Rg,$CLJS.QY(function(d){return $CLJS.y5(a,b,d,new $CLJS.k(null,2,[$CLJS.R0,c,$CLJS.M0,!1],null))}),$CLJS.fO.g($CLJS.s0(a,b)))};
H7=function(a,b,c){return $CLJS.th.j($CLJS.Rg,$CLJS.QY(function(d){return $CLJS.y3(a,b,d,c)}),$CLJS.fO.g($CLJS.s0(a,b)))};$CLJS.I7=function(a,b){return $CLJS.R4.h(a,$CLJS.Ie(b,$CLJS.i4)?$CLJS.i4.g(b):b)};$CLJS.J7=function(a,b){var c=$CLJS.Vf($CLJS.SO.g($CLJS.s0(a,b)));return null==c?null:$CLJS.Vm.h(function(d){return $CLJS.U.j($CLJS.y0.j(a,b,d),$CLJS.J_,$CLJS.e0)},c)};Wta=function(a,b,c){var d=$CLJS.D_(c);return $CLJS.U.l($CLJS.y0.j(a,b,c),$CLJS.J_,$CLJS.X_,$CLJS.J([$CLJS.V,d,$CLJS.YH,d]))};
K7=function(a,b){var c=$CLJS.C3(b);if($CLJS.m(c))a=c;else a:{var d=$CLJS.Uf(b);c=$CLJS.M.h(d,$CLJS.vQ);d=$CLJS.M.h(d,$CLJS.N_);if($CLJS.m($CLJS.m(c)?d:c)&&(d=$CLJS.H5(a,d),$CLJS.m(d))){d=$CLJS.V.g(d);a=$CLJS.V.g($CLJS.x3(a,c));a=$CLJS.xa.j?$CLJS.xa.j("%s__via__%s",d,a):$CLJS.xa.call(null,"%s__via__%s",d,a);break a}a=null}return $CLJS.m(a)?$CLJS.G3(a,$CLJS.V.g(b)):$CLJS.V.g(b)};
$CLJS.M3=function(a,b){return $CLJS.Tb(function(c,d){return $CLJS.t0(c,d,$CLJS.U,$CLJS.J([$CLJS.C5,$CLJS.Z4(c,d,$CLJS.s0(c,d))]))},a,$CLJS.Iz(0,$CLJS.r0(a,b)))};
Xta=function(a,b){a=$CLJS.s0(a,b);a=$CLJS.Uf(a);var c=$CLJS.M.h(a,$CLJS.wl),d=$CLJS.M.h(a,$CLJS.XY);b=$CLJS.C5.g(a);if($CLJS.m(b))return b;var e=$CLJS.SY.g(a);if($CLJS.m(e)&&$CLJS.m(function(){var g=$CLJS.F.h(c,$CLJS.hZ);return g?g:d}())){var f=function(){var g=c instanceof $CLJS.N?c.N:null;switch(g){case "mbql.stage/native":return $CLJS.d0;case "mbql.stage/mbql":return $CLJS.b0;default:throw Error(["No matching clause: ",$CLJS.p.g(g)].join(""));}}();return $CLJS.Vf(function(){return function n(l){return new $CLJS.Af(null,
function(){for(;;){var q=$CLJS.A(l);if(q){if($CLJS.re(q)){var u=$CLJS.$c(q),v=$CLJS.E(u),x=$CLJS.Df(v);a:for(var z=0;;)if(z<v){var B=$CLJS.be(u,z);B=$CLJS.mn.l($CLJS.J([new $CLJS.k(null,2,[$CLJS.T_,$CLJS.V.g(B),$CLJS.$_,$CLJS.V.g(B)],null),B,new $CLJS.k(null,1,[$CLJS.J_,f],null)]));x.add(B);z+=1}else{u=!0;break a}return u?$CLJS.If($CLJS.Kf(x),n($CLJS.ad(q))):$CLJS.If($CLJS.Kf(x),null)}x=$CLJS.C(q);return $CLJS.pf($CLJS.mn.l($CLJS.J([new $CLJS.k(null,2,[$CLJS.T_,$CLJS.V.g(x),$CLJS.$_,$CLJS.V.g(x)],
null),x,new $CLJS.k(null,1,[$CLJS.J_,f],null)])),n($CLJS.zd(q)))}return null}},null,null)}($CLJS.G_.g(e))}())}return null};
Yta=function(a,b,c){return $CLJS.Vf(function(){return function f(e){return new $CLJS.Af(null,function(){for(;;){var g=$CLJS.A(e);if(g){if($CLJS.re(g)){var l=$CLJS.$c(g),n=$CLJS.E(l),q=$CLJS.Df(n);return function(){for(var v=0;;)if(v<n){var x=$CLJS.be(l,v),z=q,B=$CLJS.U,H=B.l,I=x,T=$CLJS.Tm.h($CLJS.T_,$CLJS.V)(x);x=K7(a,x);x=c.g?c.g(x):c.call(null,x);B=H.call(B,I,$CLJS.J_,$CLJS.e0,$CLJS.J([$CLJS.T_,T,$CLJS.$_,x]));z.add(B);v+=1}else return!0}()?$CLJS.If($CLJS.Kf(q),f($CLJS.ad(g))):$CLJS.If($CLJS.Kf(q),
null)}var u=$CLJS.C(g);return $CLJS.pf($CLJS.U.l(u,$CLJS.J_,$CLJS.e0,$CLJS.J([$CLJS.T_,$CLJS.Tm.h($CLJS.T_,$CLJS.V)(u),$CLJS.$_,function(){var v=K7(a,u);return c.g?c.g(v):c.call(null,v)}()])),f($CLJS.zd(g)))}return null}},null,null)}($CLJS.J7(a,b))}())};
Zta=function(a,b,c){return $CLJS.Vf(function(){return function f(e){return new $CLJS.Af(null,function(){for(;;){var g=$CLJS.A(e);if(g){if($CLJS.re(g)){var l=$CLJS.$c(g),n=$CLJS.E(l),q=$CLJS.Df(n);return function(){for(var v=0;;)if(v<n){var x=$CLJS.be(l,v),z=q,B=$CLJS.U,H=B.l,I=x,T=$CLJS.V.g(x);x=$CLJS.V.g(x);x=c.g?c.g(x):c.call(null,x);B=H.call(B,I,$CLJS.J_,$CLJS.f0,$CLJS.J([$CLJS.T_,T,$CLJS.$_,x]));z.add(B);v+=1}else return!0}()?$CLJS.If($CLJS.Kf(q),f($CLJS.ad(g))):$CLJS.If($CLJS.Kf(q),null)}var u=
$CLJS.C(g);return $CLJS.pf($CLJS.U.l(u,$CLJS.J_,$CLJS.f0,$CLJS.J([$CLJS.T_,$CLJS.V.g(u),$CLJS.$_,function(){var v=$CLJS.V.g(u);return c.g?c.g(v):c.call(null,v)}()])),f($CLJS.zd(g)))}return null}},null,null)}($CLJS.L7.h(a,b))}())};
$ta=function(a,b,c){var d=$CLJS.s0(a,b);if($CLJS.m(d)){d=$CLJS.Uf(d);var e=$CLJS.M.h(d,$CLJS.AH);return $CLJS.Vf(function(){return function l(g){return new $CLJS.Af(null,function(){for(;;){var n=$CLJS.A(g);if(n){if($CLJS.re(n)){var q=$CLJS.$c(n),u=$CLJS.E(q),v=$CLJS.Df(u);return function(){for(var I=0;;)if(I<u){var T=$CLJS.be(q,I),W=$CLJS.K(T,0,null),ba=function(){var pa=W;pa=pa instanceof $CLJS.N?pa.N:null;switch(pa){case "field":return $CLJS.c0;case "expression":return $CLJS.X_;default:throw Error(["No matching clause: ",
$CLJS.p.g(pa)].join(""));}}(),ha=$CLJS.y0.j(a,b,T);$CLJS.Jf(v,$CLJS.U.l(ha,$CLJS.J_,ba,$CLJS.J([$CLJS.T_,$CLJS.X0.j(a,b,ha),$CLJS.$_,function(){var pa=K7(a,ha);return c.g?c.g(pa):c.call(null,pa)}()])));I+=1}else return!0}()?$CLJS.If($CLJS.Kf(v),l($CLJS.ad(n))):$CLJS.If($CLJS.Kf(v),null)}var x=$CLJS.C(n),z=$CLJS.K(x,0,null),B=function(){var I=z;I=I instanceof $CLJS.N?I.N:null;switch(I){case "field":return $CLJS.c0;case "expression":return $CLJS.X_;default:throw Error(["No matching clause: ",$CLJS.p.g(I)].join(""));
}}(),H=$CLJS.y0.j(a,b,x);return $CLJS.pf($CLJS.U.l(H,$CLJS.J_,B,$CLJS.J([$CLJS.T_,$CLJS.X0.j(a,b,H),$CLJS.$_,function(){var I=K7(a,H);return c.g?c.g(I):c.call(null,I)}()])),l($CLJS.zd(n)))}return null}},null,null)}(e)}())}return null};aua=function(a,b,c){return $CLJS.Vf($CLJS.th.j($CLJS.Rg,$CLJS.QY(function(d){return d.j?d.j(a,b,c):d.call(null,a,b,c)}),new $CLJS.R(null,2,5,$CLJS.S,[Yta,Zta],null)))};
bua=function(a,b,c){var d=$CLJS.x5(a,b);return $CLJS.m(d)?$CLJS.Vf(function(){return function g(f){return new $CLJS.Af(null,function(){for(;;){var l=$CLJS.A(f);if(l){if($CLJS.re(l)){var n=$CLJS.$c(l),q=$CLJS.E(n),u=$CLJS.Df(q);return function(){for(var z=0;;)if(z<q){var B=$CLJS.be(n,z);var H=$CLJS.Tm.h($CLJS.$_,$CLJS.T_)(B);H=$CLJS.m(H)?H:$CLJS.X0.j(a,b,B);B=$CLJS.Jm.h($CLJS.U.l(B,$CLJS.J_,$CLJS.U_,$CLJS.J([$CLJS.T_,H,$CLJS.$_,c.g?c.g(H):c.call(null,H)])),$CLJS.E5);u.add(B);z+=1}else return!0}()?
$CLJS.If($CLJS.Kf(u),g($CLJS.ad(l))):$CLJS.If($CLJS.Kf(u),null)}var v=$CLJS.C(l),x=function(){var z=$CLJS.Tm.h($CLJS.$_,$CLJS.T_)(v);return $CLJS.m(z)?z:$CLJS.X0.j(a,b,v)}();return $CLJS.pf($CLJS.Jm.h($CLJS.U.l(v,$CLJS.J_,$CLJS.U_,$CLJS.J([$CLJS.T_,x,$CLJS.$_,c.g?c.g(x):c.call(null,x)])),$CLJS.E5),g($CLJS.zd(l)))}return null}},null,null)}($CLJS.Z4(a,d,$CLJS.s0(a,d)))}()):null};
cua=function(a,b,c,d){return $CLJS.m(c)?(c=$CLJS.x0(a,c),$CLJS.m(c)?$CLJS.Vf($CLJS.Vm.h(function(e){return $CLJS.Jm.h(e,$CLJS.K3)},$CLJS.y5(a,b,c,new $CLJS.k(null,2,[$CLJS.R0,d,$CLJS.M0,!1],null)))):null):null};
N7=function(a,b,c){return $CLJS.Vf(function(){return function f(e){return new $CLJS.Af(null,function(){for(;;){var g=$CLJS.A(e);if(g){if($CLJS.re(g)){var l=$CLJS.$c(g),n=$CLJS.E(l),q=$CLJS.Df(n);return function(){for(var v=0;;)if(v<n){var x=$CLJS.be(l,v),z=q;var B=$CLJS.LF.g(x);var H=$CLJS.U.l,I=x,T=$CLJS.V.g(x);x=$CLJS.V.g(x);x=c.g?c.g(x):c.call(null,x);B=$CLJS.V4(H.call($CLJS.U,I,$CLJS.J_,$CLJS.X_,$CLJS.J([$CLJS.T_,T,$CLJS.$_,x])),$CLJS.qk,$CLJS.m(B)?B:$CLJS.sl);z.add(B);v+=1}else return!0}()?$CLJS.If($CLJS.Kf(q),
f($CLJS.ad(g))):$CLJS.If($CLJS.Kf(q),null)}var u=$CLJS.C(g);return $CLJS.pf(function(){var v=$CLJS.LF.g(u),x=$CLJS.U.l,z=u,B=$CLJS.V.g(u);var H=$CLJS.V.g(u);H=c.g?c.g(H):c.call(null,H);return $CLJS.V4(x.call($CLJS.U,z,$CLJS.J_,$CLJS.X_,$CLJS.J([$CLJS.T_,B,$CLJS.$_,H])),$CLJS.qk,$CLJS.m(v)?v:$CLJS.sl)}(),f($CLJS.zd(g)))}return null}},null,null)}(M7.h(a,b))}())};
dua=function(a,b,c,d){var e=$CLJS.th.j($CLJS.ui,$CLJS.xg.g($CLJS.N_),c);return $CLJS.th.j($CLJS.Rg,$CLJS.Rm.l($CLJS.zg($CLJS.K3),E7($CLJS.K3),$CLJS.xg.g(function(f){var g=$CLJS.Uf(f);f=$CLJS.M.h(g,$CLJS.Lk);g=$CLJS.M.h(g,$CLJS.K3);return $CLJS.U.j($CLJS.x3(a,g),O7,f)}),$CLJS.J([$CLJS.Um.g(function(f){return $CLJS.Ie(e,$CLJS.N_.g(f))}),E7($CLJS.N_),$CLJS.QY(function(f){f=$CLJS.Uf(f);var g=$CLJS.M.h(f,$CLJS.N_),l=$CLJS.M.h(f,O7);f=$CLJS.w0(a,g);return function u(q){return new $CLJS.Af(null,function(){for(;;){var v=
$CLJS.A(q);if(v){if($CLJS.re(v)){var x=$CLJS.$c(v),z=$CLJS.E(x),B=$CLJS.Df(z);return function(){for(var T=0;;)if(T<z){var W=$CLJS.be(x,T),ba=$CLJS.U.l(W,$CLJS.vQ,l,$CLJS.J([$CLJS.J_,$CLJS.Y_,$CLJS.T_,$CLJS.V.g(W)]));W=B;var ha=$CLJS.U,pa=ha.j,Ga=ba;ba=K7(a,ba);ba=d.g?d.g(ba):d.call(null,ba);ha=pa.call(ha,Ga,$CLJS.$_,ba);W.add(ha);T+=1}else return!0}()?$CLJS.If($CLJS.Kf(B),u($CLJS.ad(v))):$CLJS.If($CLJS.Kf(B),null)}var H=$CLJS.C(v),I=$CLJS.U.l(H,$CLJS.vQ,l,$CLJS.J([$CLJS.J_,$CLJS.Y_,$CLJS.T_,$CLJS.V.g(H)]));
return $CLJS.pf($CLJS.U.j(I,$CLJS.$_,function(){var T=K7(a,I);return d.g?d.g(T):d.call(null,T)}()),u($CLJS.zd(v)))}return null}},null,null)}($CLJS.c1.C(a,b,f,new $CLJS.k(null,2,[$CLJS.R0,d,$CLJS.M0,!1],null)))})])),c)};
P7=function(a,b,c){var d=$CLJS.Uf(c),e=$CLJS.M.h(d,$CLJS.R0);return $CLJS.Vm.h(function(f){return $CLJS.Jm.l(f,$CLJS.B3,$CLJS.J([$CLJS.E5,$CLJS.D5,$CLJS.vQ]))},function(){var f=bua(a,b,e);if($CLJS.m(f))return f;f=$CLJS.s0(a,b);f=$CLJS.Uf(f);var g=$CLJS.M.h(f,$CLJS.kP),l=$CLJS.M.h(f,$CLJS.XY),n=$CLJS.m(g)?function(){var q=$CLJS.w0(a,g);return $CLJS.y5(a,b,q,d)}():null;if($CLJS.m(n))return n;l=$CLJS.m(l)?cua(a,b,l,e):null;return $CLJS.m(l)?l:function v(u){return new $CLJS.Af(null,function(){for(;;){var x=
$CLJS.A(u);if(x){if($CLJS.re(x)){var z=$CLJS.$c(x),B=$CLJS.E(z),H=$CLJS.Df(B);return function(){for(var T=0;;)if(T<B){var W=$CLJS.be(z,T),ba=H,ha=$CLJS.U,pa=ha.l,Ga=W,eb=$CLJS.V.g(W);W=$CLJS.V.g(W);W=e.g?e.g(W):e.call(null,W);ha=pa.call(ha,Ga,$CLJS.J_,$CLJS.d0,$CLJS.J([$CLJS.T_,eb,$CLJS.$_,W]));ba.add(ha);T+=1}else return!0}()?$CLJS.If($CLJS.Kf(H),v($CLJS.ad(x))):$CLJS.If($CLJS.Kf(H),null)}var I=$CLJS.C(x);return $CLJS.pf($CLJS.U.l(I,$CLJS.J_,$CLJS.d0,$CLJS.J([$CLJS.T_,$CLJS.V.g(I),$CLJS.$_,function(){var T=
$CLJS.V.g(I);return e.g?e.g(T):e.call(null,T)}()])),v($CLJS.zd(x)))}return null}},null,null)}($CLJS.G_.g($CLJS.SY.g(f)))}())};
Q7=function(a,b){var c=$CLJS.K(a,0,null);$CLJS.K(a,1,null);var d=$CLJS.K(a,2,null);switch(c instanceof $CLJS.N?c.N:null){case "field":if("number"===typeof d||"string"===typeof d)return $CLJS.F.h(d,$CLJS.Lk.g(b));throw $CLJS.Ej("unknown type of :field ref in lib.stage/ref-to?",new $CLJS.k(null,2,[$CLJS.vR,a,$CLJS.Fk,b],null));case "expression":return $CLJS.F.h(d,$CLJS.V.g(b));default:throw $CLJS.Ej("unknown clause in lib.stage/ref-to?",new $CLJS.k(null,2,[$CLJS.vR,a,$CLJS.Fk,b],null));}};
eua=function(a,b,c){var d=$CLJS.SO.g($CLJS.s0(a,b));return $CLJS.m(d)?function g(f){return new $CLJS.Af(null,function(){for(;;){var l=$CLJS.A(f);if(l){var n=l;if($CLJS.re(n)){var q=$CLJS.$c(n),u=$CLJS.E(q),v=$CLJS.Df(u);return function(){for(var z=0;;)if(z<u){var B=$CLJS.be(q,z);$CLJS.Jf(v,function(){var H=$CLJS.LV(function(W,ba){return function(ha){return Q7(ha,ba)}}(z,B,q,u,v,n,l,d,d),d);if($CLJS.m(H)){var I=$CLJS.A5(H);H=$CLJS.G7(H);H=$CLJS.Uf(H);H=$CLJS.M.h(H,$CLJS.bk);var T=B;I=$CLJS.m(I)?$CLJS.I7(T,
I):T;return $CLJS.m(H)?$CLJS.F7(I,H):I}return B}());z+=1}else return!0}()?$CLJS.If($CLJS.Kf(v),g($CLJS.ad(n))):$CLJS.If($CLJS.Kf(v),null)}var x=$CLJS.C(n);return $CLJS.pf(function(){var z=$CLJS.LV(function(I){return function(T){return Q7(T,I)}}(x,n,l,d,d),d);if($CLJS.m(z)){var B=$CLJS.A5(z);z=$CLJS.G7(z);z=$CLJS.Uf(z);z=$CLJS.M.h(z,$CLJS.bk);var H=x;B=$CLJS.m(B)?$CLJS.I7(H,B):H;return $CLJS.m(z)?$CLJS.F7(B,z):B}return x}(),g($CLJS.zd(n)))}return null}},null,null)}(c):c};
R7=function R7(a){switch(arguments.length){case 2:return R7.h(arguments[0],arguments[1]);case 3:return R7.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};R7.h=function(a,b){return R7.j(a,-1,b)};R7.j=function(a,b,c){return $CLJS.Y0.j(a,b,$CLJS.Ui.g(c))};R7.v=3;
$CLJS.L7=function L7(a){switch(arguments.length){case 1:return L7.g(arguments[0]);case 2:return L7.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.L7.g=function(a){return $CLJS.L7.h(a,-1)};
$CLJS.L7.h=function(a,b){var c=$CLJS.Vf($CLJS.ZO.g($CLJS.s0(a,b)));return null==c?null:$CLJS.th.j($CLJS.Rg,$CLJS.xg.g(function(d){var e=$CLJS.y0.j(a,b,d),f=$CLJS.U.l,g=$CLJS.LF.g(e);return f.call($CLJS.U,$CLJS.V4(e,$CLJS.qk,$CLJS.m(g)?g:$CLJS.sl),$CLJS.J_,$CLJS.f0,$CLJS.J([$CLJS.L1,$CLJS.EK.g($CLJS.Zd(d))]))}),c)};$CLJS.L7.v=2;
var M7=function M7(a){switch(arguments.length){case 1:return M7.g(arguments[0]);case 2:return M7.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};M7.g=function(a){return M7.h(a,-1)};M7.h=function(a,b){var c=$CLJS.Vf($CLJS.aQ.g($CLJS.s0(a,b)));return null==c?null:$CLJS.Vm.h($CLJS.qz(Wta,a,b),c)};M7.v=2;
var O7=new $CLJS.N("metabase.lib.stage","source-field-id","metabase.lib.stage/source-field-id",-962431705),S7=new $CLJS.N("metabase.lib.stage","stage","metabase.lib.stage/stage",1448689281);$CLJS.fra={};$CLJS.BU($CLJS.bZ,S7);$CLJS.BU($CLJS.hZ,S7);$CLJS.u3.o(null,$CLJS.bZ,function(a){return $CLJS.t3(a,new $CLJS.k(null,2,[$CLJS.ZO,$CLJS.fg($CLJS.Vm,$CLJS.u3),$CLJS.mZ,$CLJS.fg($CLJS.Vm,$CLJS.u3)],null))});$CLJS.y0.o(null,S7,function(){throw $CLJS.Ej("You can't calculate a metadata map for a stage! Use lib.metadata.calculation/returned-columns-method instead.",$CLJS.P);});
$CLJS.c1.o(null,S7,function(a,b,c,d){var e=$CLJS.Uf(d);c=$CLJS.M.h(e,$CLJS.R0);d=$CLJS.M.h(e,$CLJS.M0);a=$CLJS.M3(a,b);e=$CLJS.Uf(e);var f=$CLJS.M.h(e,$CLJS.R0),g=$CLJS.M.h(e,$CLJS.P0),l=$CLJS.M.h(e,$CLJS.U0);e=$CLJS.wg.l(P7(a,b,e),$CLJS.m(l)?N7(a,b,f):null,$CLJS.J([$CLJS.m(g)?Vta(a,b,f):null]));return eua(a,b,$CLJS.wg.h(e,$CLJS.m(d)?dua(a,b,e,c):null))});
$CLJS.b1.o(null,S7,function(a,b,c,d){c=$CLJS.Uf(d);d=$CLJS.M.h(c,$CLJS.R0);var e=Xta(a,b);if($CLJS.m(e))return e;a=$CLJS.M3(a,b);e=aua(a,b,d);var f=$ta(a,b,d);return $CLJS.m(e)?$CLJS.th.h(e,f):$CLJS.m(f)?($CLJS.Ii(f),$CLJS.th.j($CLJS.Rg,E7(function(g){return $CLJS.Jm.l(g,$CLJS.g0,$CLJS.J([$CLJS.J_,$CLJS.L1,$CLJS.$_]))}),$CLJS.wg.h(f,H7(a,b,c)))):$CLJS.wg.l(P7(a,b,new $CLJS.k(null,2,[$CLJS.M0,!1,$CLJS.R0,d],null)),N7(a,b,d),$CLJS.J([H7(a,b,c)]))});$CLJS.V0.o(null,$CLJS.hZ,function(){return $CLJS.bH("Native query")});
var fua=new $CLJS.R(null,7,5,$CLJS.S,[$CLJS.kP,$CLJS.XY,$CLJS.ZO,$CLJS.SO,$CLJS.mZ,$CLJS.kR,$CLJS.ER],null);
$CLJS.V0.o(null,$CLJS.bZ,function(a,b,c,d){var e=$CLJS.M3(a,b);a=$CLJS.Vf(function(){return $CLJS.Uu.h(", ",$CLJS.Um.h($CLJS.lF,function(){return function l(g){return new $CLJS.Af(null,function(){for(;;){var n=$CLJS.A(g);if(n){if($CLJS.re(n)){var q=$CLJS.$c(n),u=$CLJS.E(q),v=$CLJS.Df(u);a:for(var x=0;;)if(x<u){var z=$CLJS.be(q,x);z=R7.j(e,b,z);v.add(z);x+=1}else{q=!0;break a}return q?$CLJS.If($CLJS.Kf(v),l($CLJS.ad(n))):$CLJS.If($CLJS.Kf(v),null)}v=$CLJS.C(n);return $CLJS.pf(R7.j(e,b,v),l($CLJS.zd(n)))}return null}},
null,null)}(fua)}()))}());if($CLJS.m(a))return a;a=$CLJS.x5(e,b);return $CLJS.m(a)?$CLJS.z0.C(e,a,$CLJS.s0(e,a),d):null});