var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.mbql_clause.js");require("./metabase.lib.schema.temporal_bucketing.js");require("./metabase.util.malli.registry.js");
'use strict';var nna;nna=new $CLJS.N("metabase.lib.schema.filter","operator","metabase.lib.schema.filter/operator",-805746630);$CLJS.yX=new $CLJS.N("operator","filter","operator/filter",-1518842858);$CLJS.zX=new $CLJS.N(null,"display-name-variant","display-name-variant",-1831788853);for(var AX=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Qj,$CLJS.Gk],null)),BX=null,CX=0,DX=0;;)if(DX<CX){var ona=BX.aa(null,DX);$CLJS.OU(ona,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.pl,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.et,new $CLJS.k(null,1,[$CLJS.vk,2],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.hm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.SK],null)],null)],null)],null)]));DX+=1}else{var EX=$CLJS.A(AX);if(EX){var FX=EX;if($CLJS.re(FX)){var GX=$CLJS.$c(FX),pna=$CLJS.ad(FX),
qna=GX,rna=$CLJS.E(GX);AX=pna;BX=qna;CX=rna}else{var sna=$CLJS.C(FX);$CLJS.OU(sna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.pl,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.et,new $CLJS.k(null,1,[$CLJS.vk,2],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.hm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.SK],null)],null)],null)],null)]));AX=$CLJS.D(FX);BX=null;CX=0}DX=0}else break}$CLJS.MU($CLJS.Yk,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.SK],null)]));
for(var HX=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.JJ],null)),IX=null,JX=0,KX=0;;)if(KX<JX){var tna=IX.aa(null,KX);$CLJS.OU(tna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.pl,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.et,new $CLJS.k(null,1,[$CLJS.vk,2],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.hm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.WK],null)],null)],null)],null)]));KX+=1}else{var LX=$CLJS.A(HX);if(LX){var MX=LX;if($CLJS.re(MX)){var NX=$CLJS.$c(MX),una=$CLJS.ad(MX),
vna=NX,wna=$CLJS.E(NX);HX=una;IX=vna;JX=wna}else{var xna=$CLJS.C(MX);$CLJS.OU(xna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.pl,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.et,new $CLJS.k(null,1,[$CLJS.vk,2],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.hm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.WK],null)],null)],null)],null)]));HX=$CLJS.D(MX);IX=null;JX=0}KX=0}else break}
for(var OX=$CLJS.A(new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.mm,$CLJS.zm,$CLJS.pm,$CLJS.ym],null)),PX=null,QX=0,RX=0;;)if(RX<QX){var yna=PX.aa(null,RX);$CLJS.MU(yna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null)]));RX+=1}else{var SX=$CLJS.A(OX);if(SX){var TX=SX;if($CLJS.re(TX)){var UX=$CLJS.$c(TX),zna=$CLJS.ad(TX),Ana=UX,Bna=$CLJS.E(UX);OX=zna;PX=Ana;QX=Bna}else{var Cna=$CLJS.C(TX);$CLJS.MU(Cna,$CLJS.J([$CLJS.hu,$CLJS.Fl,
new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null)]));OX=$CLJS.D(TX);PX=null;QX=0}RX=0}else break}$CLJS.MU($CLJS.PH,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null)]));
$CLJS.MU($CLJS.ZH,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.YK],null)]));
for(var VX=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.DH,$CLJS.sI],null)),WX=null,XX=0,YX=0;;)if(YX<XX){var Dna=WX.aa(null,YX);$CLJS.MU(Dna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.TK],null)]));YX+=1}else{var ZX=$CLJS.A(VX);if(ZX){var $X=ZX;if($CLJS.re($X)){var aY=$CLJS.$c($X),Ena=$CLJS.ad($X),Fna=aY,Gna=$CLJS.E(aY);VX=Ena;WX=Fna;XX=Gna}else{var Hna=$CLJS.C($X);$CLJS.MU(Hna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.TK],null)]));VX=$CLJS.D($X);
WX=null;XX=0}YX=0}else break}
for(var bY=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.QH,$CLJS.eI],null)),cY=null,dY=0,eY=0;;)if(eY<dY){var Ina=cY.aa(null,eY);$CLJS.MU(Ina,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.ZK],null)]));eY+=1}else{var fY=$CLJS.A(bY);if(fY){var gY=fY;if($CLJS.re(gY)){var hY=$CLJS.$c(gY),Jna=$CLJS.ad(gY),Kna=hY,Lna=$CLJS.E(hY);bY=Jna;cY=Kna;dY=Lna}else{var Mna=$CLJS.C(gY);$CLJS.MU(Mna,$CLJS.J([$CLJS.hu,$CLJS.Fl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.ZK],null)]));bY=$CLJS.D(gY);
cY=null;dY=0}eY=0}else break}
for(var iY=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.bm,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fJ,new $CLJS.k(null,1,[$CLJS.Wj,!0],null),$CLJS.pk],null)],null),jY=$CLJS.A(new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.zI,$CLJS.sJ,$CLJS.QI,$CLJS.AI],null)),kY=null,lY=0,mY=0;;)if(mY<lY){var nY=kY.aa(null,mY);$CLJS.JU(nY,$CLJS.Fl,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.tt,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,nY],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Qt,$CLJS.DK,iY],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.ZK],
null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.ZK],null)],null));mY+=1}else{var oY=$CLJS.A(jY);if(oY){var pY=oY;if($CLJS.re(pY)){var qY=$CLJS.$c(pY),Nna=$CLJS.ad(pY),Ona=qY,Pna=$CLJS.E(qY);jY=Nna;kY=Ona;lY=Pna}else{var rY=$CLJS.C(pY);$CLJS.JU(rY,$CLJS.Fl,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.tt,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,rY],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Qt,$CLJS.DK,iY],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.ZK],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.ZK],
null)],null));jY=$CLJS.D(pY);kY=null;lY=0}mY=0}else break}
$CLJS.JU($CLJS.wJ,$CLJS.Fl,new $CLJS.R(null,6,5,$CLJS.S,[$CLJS.tt,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.wJ],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Qt,$CLJS.DK,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.bm,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.EJ,new $CLJS.k(null,1,[$CLJS.Wj,!0],null),$CLJS.pk],null)],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.RK],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Gk,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.ot,$CLJS.eB,$CLJS.gD,$CLJS.WH],null),new $CLJS.R(null,2,
5,$CLJS.S,[$CLJS.nq,$CLJS.aL],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.nq,$CLJS.WU],null)],null));$CLJS.JU($CLJS.sH,$CLJS.Fl,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.tt,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.sH],null),$CLJS.DK,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Gk,$CLJS.wK,$CLJS.zK],null)],null));
$CLJS.rK(nna,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.bm,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.wl,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.yX],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.QU,new $CLJS.R(null,17,5,$CLJS.S,[$CLJS.ot,$CLJS.lm,$CLJS.JJ,$CLJS.ZH,$CLJS.PH,$CLJS.mm,$CLJS.pm,$CLJS.zm,$CLJS.ym,$CLJS.DH,$CLJS.sI,$CLJS.QH,$CLJS.eI,$CLJS.QI,$CLJS.AI,$CLJS.zI,$CLJS.sJ],null)],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.zX,$CLJS.Jk],null)],null));