var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./shadow.js.shim.module$crc_32.js");require("./clojure.set.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.common.js");require("./metabase.lib.options.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.id.js");require("./metabase.mbql.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.malli.js");
'use strict';var apa,E_,bpa,cpa,epa,dpa;$CLJS.z_=function(a,b){return $CLJS.Q.j($CLJS.xa,a,b)};$CLJS.A_=function(a){if("string"===typeof a){var b=$CLJS.Ji(/[+-]?\d+/,a);return $CLJS.m(b)?(a=parseInt(a),a<=Number.MAX_SAFE_INTEGER&&a>=Number.MIN_SAFE_INTEGER?a:null):b}throw Error($CLJS.jo(a));};
apa=function(a){var b=new $CLJS.qb,c=$CLJS.Kz;$CLJS.Kz=new $CLJS.gd(b);try{var d=$CLJS.Kz,e=$CLJS.Fb($CLJS.RA(d)),f=$CLJS.Kz;$CLJS.Kz=e?$CLJS.IA(d):d;try{d=$CLJS.TA;$CLJS.TA=!0;try{$CLJS.VA(a)}finally{$CLJS.TA=d}$CLJS.F.h(0,$CLJS.Rz($CLJS.Kz,$CLJS.Tz))||$CLJS.Qc($CLJS.Kz,"\n");$CLJS.Qz()}finally{$CLJS.Kz=f}$CLJS.Fz($CLJS.p.g(b))}finally{$CLJS.Kz=c}};$CLJS.B_=function(a){var b=new $CLJS.qb,c=$CLJS.zb;$CLJS.zb=function(d){return b.append(d)};try{apa(a)}finally{$CLJS.zb=c}return $CLJS.p.g(b)};
$CLJS.C_=function(a){return $CLJS.qe(a)&&1<$CLJS.E(a)&&$CLJS.C(a)instanceof $CLJS.N&&$CLJS.oe($CLJS.Zd(a))&&$CLJS.Ie($CLJS.Zd(a),$CLJS.EK)};$CLJS.D_=function(a){return $CLJS.C_(a)?$CLJS.vu(a,new $CLJS.R(null,2,5,$CLJS.S,[1,$CLJS.VK],null)):null};E_=function(a,b,c){var d=$CLJS.Ie(a,b)?$CLJS.Wm.j(a,b,function(e){return $CLJS.qe(e)&&$CLJS.F.h($CLJS.C(e),$CLJS.Qj)?$CLJS.Sg($CLJS.qg(1,e)):new $CLJS.R(null,1,5,$CLJS.S,[e],null)}):a;return $CLJS.Ie(a,b)?$CLJS.ZM(d,$CLJS.Tf([b,c])):d};
bpa=function(a){var b=$CLJS.ri(a,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.kP,$CLJS.xQ],null));b=F_.g?F_.g(b):F_.call(null,b);return $CLJS.vV($CLJS.U.l(E_($CLJS.Jm.l(a,$CLJS.kP,$CLJS.J([$CLJS.xQ])),$CLJS.mR,$CLJS.BY),$CLJS.wl,$CLJS.tY,$CLJS.J([$CLJS.yY,b])))};cpa=function(a){return $CLJS.Vm.h(bpa,a)};
epa=function(a){return $CLJS.m(a)?$CLJS.U.j($CLJS.Wm.j($CLJS.xe(a)?new $CLJS.k(null,1,[$CLJS.G_,a],null):a,$CLJS.G_,function(b){return $CLJS.Vm.h(function(c){return $CLJS.U.j($CLJS.pF(c,$CLJS.wF),$CLJS.wl,$CLJS.xV)},b)}),$CLJS.wl,dpa):null};
$CLJS.H_=function(a){if($CLJS.F.h($CLJS.wl.g(a),$CLJS.lZ))return a;var b=$CLJS.al.g(a);b=b instanceof $CLJS.N?b.N:null;switch(b){case "native":return $CLJS.mn.l($CLJS.J([new $CLJS.k(null,2,[$CLJS.wl,$CLJS.lZ,$CLJS.yY,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.mn.l($CLJS.J([new $CLJS.k(null,1,[$CLJS.wl,$CLJS.hZ],null),$CLJS.ZM($CLJS.fQ.g(a),new $CLJS.k(null,1,[$CLJS.GN,$CLJS.fQ],null))]))],null)],null),$CLJS.Jm.l(a,$CLJS.al,$CLJS.J([$CLJS.fQ]))]));case "query":return $CLJS.mn.l($CLJS.J([new $CLJS.k(null,
2,[$CLJS.wl,$CLJS.lZ,$CLJS.yY,F_($CLJS.GN.g(a))],null),$CLJS.Jm.l(a,$CLJS.al,$CLJS.J([$CLJS.GN]))]));default:throw Error(["No matching clause: ",$CLJS.p.g(b)].join(""));}};$CLJS.I_=function(a){return"string"===typeof a&&(a=$CLJS.Ki(/^card__(\d+)$/,a),$CLJS.m(a))?($CLJS.K(a,0,null),a=$CLJS.K(a,1,null),$CLJS.A_(a)):null};$CLJS.J_=new $CLJS.N("lib","source","lib/source",-434086550);$CLJS.K_=new $CLJS.N("metadata","segment","metadata/segment",-1286738015);
$CLJS.L_=new $CLJS.N("metadata","table","metadata/table",-882499405);$CLJS.fpa=new $CLJS.N(null,"num-stages","num-stages",1426797535);$CLJS.M_=new $CLJS.N(null,"tables","tables",1334623052);$CLJS.N_=new $CLJS.N(null,"table-id","table-id",-766649466);$CLJS.G_=new $CLJS.N(null,"columns","columns",1998437288);$CLJS.gpa=new $CLJS.N("metadata","database","metadata/database",-924828824);$CLJS.O_=new $CLJS.N(null,"table","table",-564943036);$CLJS.P_=new $CLJS.N("metadata","card","metadata/card",-1039333889);
dpa=new $CLJS.N("metadata","results","metadata/results",330329298);var F_;
F_=function F_(a){a=$CLJS.Uf(a);var c=$CLJS.M.h(a,$CLJS.xQ),d=$CLJS.M.h(a,$CLJS.$O);c=$CLJS.m(c)?F_.g?F_.g(c):F_.call(null,c):$CLJS.Rg;d=epa(d);var e=$CLJS.E(c)-1;c=$CLJS.m($CLJS.m(d)?!(0>e):d)?$CLJS.Bu(c,new $CLJS.R(null,2,5,$CLJS.S,[e,$CLJS.SY],null),d):c;d=$CLJS.m($CLJS.fQ.g(a))?$CLJS.hZ:$CLJS.bZ;a=$CLJS.mn.l($CLJS.J([new $CLJS.k(null,1,[$CLJS.wl,d],null),$CLJS.Jm.l(a,$CLJS.xQ,$CLJS.J([$CLJS.$O]))]));a=$CLJS.A($CLJS.fO.g(a))?$CLJS.Wm.j(a,$CLJS.fO,cpa):a;a=E_(a,$CLJS.TN,$CLJS.mZ);return $CLJS.mf.h(c,a)};
$CLJS.Q_=RegExp(" id$","i");