var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.lib.aggregation.js");require("./metabase.lib.binning.js");require("./metabase.lib.breakout.js");require("./metabase.lib.card.js");require("./metabase.lib.column_group.js");require("./metabase.lib.common.js");require("./metabase.lib.database.js");require("./metabase.lib.expression.js");require("./metabase.lib.field.js");require("./metabase.lib.filter.js");require("./metabase.lib.join.js");require("./metabase.lib.limit.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.metric.js");require("./metabase.lib.native.js");require("./metabase.lib.normalize.js");require("./metabase.lib.order_by.js");require("./metabase.lib.query.js");require("./metabase.lib.ref.js");require("./metabase.lib.remove_replace.js");require("./metabase.lib.segment.js");require("./metabase.lib.stage.js");require("./metabase.lib.table.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.shared.util.namespaces.js");
'use strict';var X7,sua,Y7,tua,uua,Z7,vua,wua,xua,$7,yua,zua,a8,b8,Aua,c8,d8,e8,f8,Bua,g8,h8,Cua,i8,Dua,Eua,Fua,Gua,Hua,Iua,Jua,Kua,Lua,j8,Mua,k8,l8,Nua,Oua,m8,Pua,Qua,Rua,Sua,Tua,Uua,Vua,Wua,Xua,Yua,Zua,$ua,ava,bva,cva,dva,eva,o8,p8,q8,r8,s8,fva,gva,hva,iva,jva,kva,lva,v8,w8,mva,nva,z8,x8,y8,A8,ova,pva,qva,B8,rva,sva,C8,tva,uva,t8;X7=function(a,b){$CLJS.Tb(function(c,d){return a.g?a.g(d):a.call(null,d)},null,b)};
sua=function(a,b){return $CLJS.E(a)<=$CLJS.E(b)&&$CLJS.$f(function(c){return $CLJS.Ie(b,c)},a)};Y7=function(a){return $CLJS.EK.g($CLJS.HK(a))};tua=function(a,b){return $CLJS.Vc($CLJS.Tb(function(c,d){return $CLJS.xh.j(c,a.g?a.g(d):a.call(null,d),d)},$CLJS.Tc($CLJS.P),b))};uua=function(a,b){return $CLJS.nF(function(c){return function(d,e,f){return $CLJS.m(a.g?a.g(e):a.call(null,e))?c.j?c.j(d,e,f):c.call(null,d,e,f):d}},b)};
Z7=function(a,b){if(b=$CLJS.A(b)){var c=$CLJS.A(b);b=$CLJS.C(c);c=$CLJS.D(c);return $CLJS.A(c)?(c=Z7($CLJS.M.h(a,b),c),$CLJS.je(c)?$CLJS.Jm.h(a,b):$CLJS.U.j(a,b,c)):$CLJS.Jm.h(a,b)}return a};vua=function(a,b,c,d){return function q(f,g,l,n){var u=$CLJS.A(g);g=$CLJS.C(u);u=$CLJS.D(u);var v=$CLJS.Le(f,g);return $CLJS.m(v)?u?$CLJS.U.j(f,g,q($CLJS.uc(v),u,l,n)):$CLJS.U.j(f,g,$CLJS.Q.j(l,$CLJS.uc(v),n)):f}(a,b,c,d)};
wua=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return vua(arguments[0],arguments[1],arguments[2],3<b.length?new $CLJS.y(b.slice(3),0,null):null)};xua=function(a,b){return $CLJS.C($CLJS.ig(function(c){if($CLJS.m($CLJS.m(c)?b:c)){var d=$CLJS.Du.g(c);c=$CLJS.Iu.g(c);d=$CLJS.m($CLJS.Ki(d,b))?$CLJS.zu(b,d,c):null}else d=null;return d},a))};
$7=function(a){a=$CLJS.DG(a);var b=$CLJS.lF(a);b||($CLJS.m(a)?(b=$CLJS.m(a)?!$CLJS.Ie($CLJS.r($CLJS.JG),$CLJS.DG(a).toLowerCase()):null,b=$CLJS.Fb(b)):b=null);return $CLJS.m(b)?a:xua($CLJS.Pc($CLJS.r($CLJS.FG)),a)};
yua=function(a){return function(b){var c=$CLJS.og(!0);return function(){function d(l,n){var q=$CLJS.r(c);if($CLJS.m($CLJS.m(q)?a.g?a.g(n):a.call(null,n):q))return l;$CLJS.Dn(c,null);return b.h?b.h(l,n):b.call(null,l,n)}function e(l){return b.g?b.g(l):b.call(null,l)}function f(){return b.A?b.A():b.call(null)}var g=null;g=function(l,n){switch(arguments.length){case 0:return f.call(this);case 1:return e.call(this,l);case 2:return d.call(this,l,n)}throw Error("Invalid arity: "+arguments.length);};g.A=
f;g.g=e;g.h=d;return g}()}};zua=function(a){var b=$CLJS.K(a,0,null),c=$CLJS.K(a,1,null);return $CLJS.m(a)?new $CLJS.k(null,4,[$CLJS.wl,$CLJS.xK,$CLJS.VI,b instanceof $CLJS.N?$CLJS.Ai(b):b,$CLJS.Sk,c,$CLJS.pl,$CLJS.an.h(a,2)],null):null};a8=function(a,b){if(null!=a&&null!=a.Zg)a=a.Zg(a,b);else{var c=a8[$CLJS.Na(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=a8._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $CLJS.Ob("MetadataProvider.metrics",a);}return a};
b8=function(a,b){return $CLJS.C_(a)&&$CLJS.F.h($CLJS.C(a),b)};
Aua=function(a,b,c,d){var e=$CLJS.F.h($CLJS.aQ,$CLJS.C(b))?$CLJS.E2(d,$CLJS.D_(c)):d;return wua(a,b,function(f){return $CLJS.Sg(function(){return function n(l){return new $CLJS.Af(null,function(){for(;;){var q=$CLJS.A(l);if(q){if($CLJS.re(q)){var u=$CLJS.$c(q),v=$CLJS.E(u),x=$CLJS.Df(v);a:for(var z=0;;)if(z<v){var B=$CLJS.be(u,z);B=$CLJS.F.h(Y7(B),Y7(c))?e:B;x.add(B);z+=1}else{u=!0;break a}return u?$CLJS.If($CLJS.Kf(x),n($CLJS.ad(q))):$CLJS.If($CLJS.Kf(x),null)}x=$CLJS.C(q);return $CLJS.pf($CLJS.F.h(Y7(x),
Y7(c))?e:x,n($CLJS.zd(q)))}return null}},null,null)}(f)}())})};
c8=function(a,b,c){var d=$CLJS.vu(a,b);if($CLJS.m(d)){var e=Y7(c),f=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.C(b),$CLJS.$d(b)],null);c=$CLJS.K(f,0,null);f=$CLJS.K(f,1,null);d=$CLJS.th.j($CLJS.Rg,$CLJS.Um.g($CLJS.Rm.h($CLJS.vi([e]),Y7)),d);d=$CLJS.F.h(b,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.AH],null))&&$CLJS.$f(function(g){return b8(g,$CLJS.IF)},d)?null:d;if($CLJS.A(d))return $CLJS.Bu(a,b,d);if($CLJS.F.h(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.fO,$CLJS.BY],null),new $CLJS.R(null,2,5,$CLJS.S,[c,f],null)))throw $CLJS.Ej($CLJS.bH("Cannot remove the final join condition"),
new $CLJS.k(null,1,[$CLJS.BY,$CLJS.vu(a,b)],null));return $CLJS.F.h(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.fO,$CLJS.AH],null),new $CLJS.R(null,2,5,$CLJS.S,[c,f],null))?$CLJS.RZ.C(a,$CLJS.ie(b),$CLJS.Jm,f):Z7(a,b)}return a};d8=function(a,b){a=$CLJS.Uf(a);a=$CLJS.M.h(a,$CLJS.yY);b=0>b?$CLJS.E(a)+b:b;return b+1<$CLJS.E(a)?b+1:null};
e8=function(a,b,c,d){a=$CLJS.H_(a);b=$CLJS.m(b)?b:-1;var e=$CLJS.s0(a,b);e=!($CLJS.A($CLJS.ZO.g(e))||$CLJS.A($CLJS.SO.g(e)));c=$CLJS.t0(a,b,$CLJS.Wm,$CLJS.J([c,function(f){return $CLJS.mf.h($CLJS.Sg(f),$CLJS.zV.g(d))}]));return e?$CLJS.Wm.S($CLJS.O5(c,b,function(f){return $CLJS.SZ.j($CLJS.Jm.l(f,$CLJS.kR,$CLJS.J([$CLJS.AH])),$CLJS.fO,function(g){return $CLJS.Vm.h(function(l){return $CLJS.Jm.h(l,$CLJS.AH)},g)})}),$CLJS.yY,$CLJS.Rm.h(function(f){return $CLJS.th.h($CLJS.Rg,f)},$CLJS.an),0,$CLJS.r0(a,
b)+1):c};f8=function(a){var b=$CLJS.HK(a);b=$CLJS.m($CLJS.qk.g(b))?null:$CLJS.LF.g(b);return $CLJS.m(b)?$CLJS.tV(a,$CLJS.U,$CLJS.J([$CLJS.qk,b])):a};Bua=function(a){return $CLJS.uV(a,function(b){return $CLJS.th.j($CLJS.P,$CLJS.Um.g(function(c){var d=$CLJS.K(c,0,null);$CLJS.K(c,1,null);return $CLJS.zf(d)}),b)})};
g8=function(a,b){for(var c=$CLJS.Ze,d=new $CLJS.R(null,4,5,$CLJS.S,[function(){return function(g){return $CLJS.tV(g,$CLJS.SZ,$CLJS.J([$CLJS.bR,$CLJS.Jm,$CLJS.V_,$CLJS.wl]))}}(c),Bua,function(){return function(g){return $CLJS.tV(g,$CLJS.Jm,$CLJS.J([$CLJS.LF,$CLJS.qk]))}}(c),function(){return function(g){return $CLJS.tV(g,$CLJS.Jm,$CLJS.J([$CLJS.yP]))}}(c)],null);;){var e=function(){var g=c.g?c.g(a):c.call(null,a);return $CLJS.LV(function(l,n,q){return function(u){return $CLJS.n0.h(l.g?l.g(u):l.call(null,
u),q)}}(c,d,g),b)}();if($CLJS.m(e))return e;if($CLJS.A(d)){e=$CLJS.Rm.h(c,$CLJS.C(d));var f=$CLJS.zd(d);c=e;d=f}else return null}};
h8=function(a,b,c){var d=g8(b,c);return $CLJS.m(d)?d:$CLJS.C($CLJS.A($CLJS.Ag($CLJS.Gb,function l(f,g){try{if($CLJS.qe(g)&&3===$CLJS.E(g))try{var n=$CLJS.G(g,0);if($CLJS.O(n,$CLJS.PP))try{var q=$CLJS.G(g,2);if($CLJS.Ae(q)){var u=$CLJS.G(g,2),v=$CLJS.G(g,1);n=$CLJS.S;var x=$CLJS.V.g($CLJS.x3(a,u));var z=$CLJS.m(x)?g8(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,v,x],null),c):null;return new $CLJS.R(null,1,5,n,[z],null)}throw $CLJS.Z;}catch(H){if(H instanceof Error){var B=H;if(B===$CLJS.Z)throw $CLJS.Z;throw B;
}throw H;}else throw $CLJS.Z;}catch(H){if(H instanceof Error){B=H;if(B===$CLJS.Z)throw $CLJS.Z;throw B;}throw H;}else throw $CLJS.Z;}catch(H){if(H instanceof Error){B=H;if(B===$CLJS.Z)return $CLJS.WY(l,f,g);throw B;}throw H;}}($CLJS.Rg,b))))};
Cua=function(a){if($CLJS.F.h($CLJS.wl.g($CLJS.s0(a,-1)),$CLJS.hZ))return null;try{return $CLJS.z0.h(a,a)}catch(c){if(c instanceof Error){a=c;var b=$CLJS.mF($CLJS.Nu);$CLJS.m($CLJS.qF("metabase.lib.metadata.calculation",b))&&(a instanceof Error?$CLJS.rF("metabase.lib.metadata.calculation",b,$CLJS.MB.l($CLJS.J([$CLJS.aH("Error calculating display name for query: {0}",$CLJS.J([$CLJS.rZ(a)]))])),a):$CLJS.rF("metabase.lib.metadata.calculation",b,$CLJS.MB.l($CLJS.J([a,$CLJS.aH("Error calculating display name for query: {0}",
$CLJS.J([$CLJS.rZ(a)]))])),null));return null}throw c;}};
i8=function(a){return $CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.q1,a):$CLJS.x1.call(null,$CLJS.q1,a))?$CLJS.J1:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.n1,a):$CLJS.x1.call(null,$CLJS.n1,a))?$CLJS.J1:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.k1,a):$CLJS.x1.call(null,$CLJS.k1,a))?$CLJS.ypa:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.t1,a):$CLJS.x1.call(null,$CLJS.t1,a))?$CLJS.zpa:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.s1,a):$CLJS.x1.call(null,$CLJS.s1,a))?$CLJS.Apa:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.j1,a):$CLJS.x1.call(null,
$CLJS.j1,a))?$CLJS.Bpa:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.h1,a):$CLJS.x1.call(null,$CLJS.h1,a))?$CLJS.Cpa:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.i1,a):$CLJS.x1.call(null,$CLJS.i1,a))?$CLJS.Dpa:$CLJS.m($CLJS.x1.h?$CLJS.x1.h($CLJS.o1,a):$CLJS.x1.call(null,$CLJS.o1,a))?$CLJS.Epa:$CLJS.Fpa};
Dua=function(a,b){a=$CLJS.Q1(a);b=$CLJS.m(b)?b:$CLJS.oz;return 0===a?$CLJS.bH("Now"):0>a?$CLJS.aH("{0} {1} ago",$CLJS.J([Math.abs(a),$CLJS.M1.h(Math.abs(a),b).toLowerCase()])):$CLJS.aH("{0} {1} from now",$CLJS.J([a,$CLJS.M1.h(a,b).toLowerCase()]))};Eua=function(a){return $CLJS.U1.g(a)};
Fua=function(a,b){var c=$CLJS.th.j($CLJS.P,$CLJS.En(function(e){var f=g8($CLJS.wV(e),b);return $CLJS.m(f)?new $CLJS.R(null,2,5,$CLJS.S,[f,e],null):null}),a);c=$CLJS.xg.h(c,b);var d=$CLJS.LV($CLJS.Tm.h($CLJS.A1,$CLJS.B1),c);if($CLJS.m(d))return d;c=$CLJS.C(c);if($CLJS.m(c))return c;c=$CLJS.LV($CLJS.A1,a);if($CLJS.m(c))return c;c=$CLJS.LV($CLJS.B1,a);return $CLJS.m(c)?c:$CLJS.C(a)};Gua=function(a){return"string"===typeof a?(0,$CLJS.Ca)($CLJS.zu(a,/ id$/i,"")):null};
Hua=function(a,b){var c="string"===typeof a;if(c){if(c="string"===typeof b){c=new $CLJS.dj(function(){return $7(b)});var d=new $CLJS.dj(function(){return $7(a)});return $CLJS.F.h(a,b)||$CLJS.F.h(a,$CLJS.r(c))||$CLJS.F.h($CLJS.r(d),b)||$CLJS.F.h($CLJS.r(d),$CLJS.r(c))}return c}return c};
Iua=function(a,b,c){var d=$CLJS.z0.h($CLJS.F.h($CLJS.wl.g(b),$CLJS.lZ)?b:a,b),e=$CLJS.m(c)?Gua($CLJS.z0.h(a,c)):null,f=Hua(d,e);return function(){var g=function(){if($CLJS.m(d)){if($CLJS.m(e)){var l=$CLJS.Fb($CLJS.Ji(/id/i,e));return l?(l=!f)?[$CLJS.p.g(d)," - ",e].join(""):l:l}return e}return d}();return $CLJS.m(g)?g:$CLJS.m(d)?d:$CLJS.m(e)?e:"source"}()};
Jua=function(a,b,c,d){return function l(f,g){try{if(b8(g,$CLJS.PP)&&$CLJS.ye(h8(a,g,d)))return $CLJS.D3(g,c);throw $CLJS.Z;}catch(q){if(q instanceof Error){var n=q;if(n===$CLJS.Z)return $CLJS.FZ(l,f,g);throw n;}throw q;}}($CLJS.Rg,b)};
Kua=function(a,b,c,d,e){b=Jua(a,b,c,e);return function n(g,l){try{if($CLJS.qe(l)&&4===$CLJS.E(l))try{var q=$CLJS.G(l,2);if(b8(q,$CLJS.PP))try{var u=$CLJS.G(l,3);if(b8(u,$CLJS.PP)){var v=$CLJS.G(l,3),x=$CLJS.G(l,2),z=$CLJS.G(l,0),B=$CLJS.G(l,1),H=$CLJS.Ie($CLJS.HK(x),$CLJS.yP),I=$CLJS.Ie($CLJS.HK(v),$CLJS.yP);if(H||I){if(H&&I){var T=$CLJS.tV(x,$CLJS.Jm,$CLJS.J([$CLJS.yP])),W=$CLJS.tV(v,$CLJS.Jm,$CLJS.J([$CLJS.yP])),ba=null==h8(a,T,d);var ha=ba?h8(a,W,d):ba;return $CLJS.m(ha)?new $CLJS.R(null,4,5,$CLJS.S,
[z,B,x,W],null):new $CLJS.R(null,4,5,$CLJS.S,[z,B,T,v],null)}return l}return $CLJS.m(h8(a,v,d))?new $CLJS.R(null,4,5,$CLJS.S,[z,B,$CLJS.D3(x,c),v],null):new $CLJS.R(null,4,5,$CLJS.S,[z,B,x,$CLJS.D3(v,c)],null)}throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){var pa=Ga;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw Ga;}else throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){pa=Ga;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw Ga;}else throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){pa=Ga;if(pa===$CLJS.Z)return $CLJS.FZ(n,
g,l);throw pa;}throw Ga;}}($CLJS.Rg,b)};Lua=function(a,b){var c=$CLJS.G2();X7(c,b);return c(a)};
j8=function(a,b,c){if($CLJS.Ie(c,$CLJS.qI))return c;var d=$CLJS.s0(a,b);b=$CLJS.z5(a,b,d);var e=$CLJS.A($CLJS.Ag($CLJS.Gb,function v(q,u){try{if($CLJS.qe(u)&&1<=$CLJS.E(u))try{var x=$CLJS.an.j(u,0,1);if($CLJS.qe(x)&&1===$CLJS.E(x))try{var z=$CLJS.G(x,0);if($CLJS.O(z,$CLJS.PP))return new $CLJS.R(null,1,5,$CLJS.S,[u],null);throw $CLJS.Z;}catch(H){if(H instanceof Error){var B=H;if(B===$CLJS.Z)throw $CLJS.Z;throw B;}throw H;}else throw $CLJS.Z;}catch(H){if(H instanceof Error){B=H;if(B===$CLJS.Z)throw $CLJS.Z;
throw B;}throw H;}else throw $CLJS.Z;}catch(H){if(H instanceof Error){B=H;if(B===$CLJS.Z)return $CLJS.WY(v,q,u);throw B;}throw H;}}($CLJS.Rg,$CLJS.BY.g(c))));e=Fua(b,e);var f=Lua(Iua(a,c,e),$CLJS.ig($CLJS.qI,$CLJS.fO.g(d))),g=$CLJS.Vm.h($CLJS.wV,b),l=$CLJS.Vm.h($CLJS.wV,$CLJS.$4($CLJS.z3(a,$CLJS.yY.g(c))));return $CLJS.D3($CLJS.Wm.j(c,$CLJS.BY,function(q){return $CLJS.Vm.h(function(u){return Kua(a,u,f,g,l)},q)}),f)};Mua=function(a){return $CLJS.BY.g(a)};k8=function(a){return $CLJS.AH.g(a)};
l8=function(a){return $CLJS.mn.l($CLJS.J([new $CLJS.k(null,2,[$CLJS.wl,$CLJS.CY,$CLJS.dK,a],null),$CLJS.F.h(a,$CLJS.OI)?new $CLJS.k(null,1,[$CLJS.Uj,!0],null):null]))};Nua=function(a){return l8($CLJS.M.j(a,$CLJS.dK,$CLJS.OI))};Oua=function(a,b){return $CLJS.U.j(a,$CLJS.dK,$CLJS.F.h($CLJS.LG(b),$CLJS.CY)?$CLJS.dK.g(b):b)};
m8=function(a){a=$CLJS.lj(function(d){return $CLJS.B1(d)?$CLJS.J3:$CLJS.A1(d)?$CLJS.I3:$CLJS.gz},a);var b=$CLJS.Uf(a);a=$CLJS.M.h(b,$CLJS.J3);var c=$CLJS.M.h(b,$CLJS.I3);b=$CLJS.M.h(b,$CLJS.gz);return $CLJS.wg.l(a,c,$CLJS.J([b]))};Pua=function(a,b,c){var d=$CLJS.Lk.g(c);return $CLJS.m(d)?$CLJS.LV(function(e){e=$CLJS.Uf(e);var f=$CLJS.M.h(e,$CLJS.K3);return $CLJS.A1(e)&&$CLJS.F.h(f,d)},$CLJS.z5(a,b,$CLJS.s0(a,b))):null};
$CLJS.n8=function(a,b){b=$CLJS.C($CLJS.yY.g(b));return $CLJS.m($CLJS.XY.g(b))?$CLJS.x0(a,$CLJS.XY.g(b)):$CLJS.m($CLJS.kP.g(b))?$CLJS.w0(a,$CLJS.kP.g(b)):null};Qua=function(a,b){var c=$CLJS.C3(b),d=$CLJS.G2();return $CLJS.Vm.h(function(e){e=$CLJS.D3(e,c);return $CLJS.H3(b,d,e)},a)};
Rua=function(a,b){b=k8(b);if($CLJS.F.h($CLJS.ID,b))return $CLJS.Vm.h(function(e){return $CLJS.U.j(e,$CLJS.a0,!0)},a);if($CLJS.F.h($CLJS.Lu,b)||$CLJS.F.h(null,b))return $CLJS.Vm.h(function(e){return $CLJS.U.j(e,$CLJS.a0,!1)},a);b=$CLJS.Vm.h($CLJS.wV,b);a=$CLJS.Vm.h(function(e){return $CLJS.U.j(e,$CLJS.L3,$CLJS.wV(e))},a);var c=$CLJS.Vm.h($CLJS.L3,a),d=$CLJS.th.j($CLJS.ui,$CLJS.xg.g(function(e){return g8(e,c)}),b);return $CLJS.Vm.h(function(e){return $CLJS.Jm.h($CLJS.U.j(e,$CLJS.a0,$CLJS.Ie(d,$CLJS.L3.g(e))),
$CLJS.L3)},a)};Sua=function(a,b,c){var d=$CLJS.F.h($CLJS.LG(c),$CLJS.tY)?c:null;c=$CLJS.m(d)?$CLJS.n8(a,c):c;a=$CLJS.Z4(a,b,c);a=$CLJS.m(d)?Qua(a,d):a;return $CLJS.m(d)?Rua(a,d):a};
Tua=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.h(a,$CLJS.J_);switch(b instanceof $CLJS.N?b.N:null){case "source/implicitly-joinable":return new $CLJS.k(null,2,[$CLJS.O3,$CLJS.ora,$CLJS.vQ,$CLJS.vQ.g(a)],null);case "source/joins":return new $CLJS.k(null,2,[$CLJS.O3,$CLJS.pra,$CLJS.yP,$CLJS.C3(a)],null);default:return new $CLJS.k(null,1,[$CLJS.O3,$CLJS.nra],null)}};
Uua=function(a){return $CLJS.Vm.h(function(b){var c=$CLJS.K(b,0,null);b=$CLJS.K(b,1,null);return $CLJS.U.l(c,$CLJS.wl,$CLJS.P3,$CLJS.J([$CLJS.Q3,b]))},$CLJS.lj(Tua,a))};Vua=function(a){return $CLJS.Q3.g(a)};Wua=function(a){return $CLJS.G_.g(a)};
Xua=function(a,b){if($CLJS.A(a)){var c=$CLJS.K(b,0,null);$CLJS.K(b,1,null);var d=$CLJS.K(b,2,null),e=$CLJS.bQ.g($CLJS.HK(d));return $CLJS.Vm.h(function(f){return $CLJS.F.h($CLJS.QU.g(f),c)?$CLJS.SZ.j($CLJS.U.j(f,$CLJS.a0,!0),$CLJS.G_,function(g){var l=$CLJS.Vm.h($CLJS.wV,g),n=g8($CLJS.tV(d,$CLJS.Jm,$CLJS.J([$CLJS.bQ])),l);return $CLJS.m(n)?$CLJS.Vm.j(function(q,u){q=$CLJS.F.h(q,n)?$CLJS.U.j(u,$CLJS.a0,!0):u;return null!=e?$CLJS.F7(q,e):q},l,g):g}):f},a)}return null};
Yua=function(a){var b=$CLJS.YP.g(a);if($CLJS.m(b)){if($CLJS.qi.h(b,-1337))return b;b=$CLJS.XY.g($CLJS.C($CLJS.yY.g(a)));if($CLJS.m(b))return a=$CLJS.x0(a,b),$CLJS.m(a)?$CLJS.ipa.g(a):null}return null};Zua=function(a,b,c){var d=$CLJS.s0(a,b);a=$CLJS.z5(a,b,d);var e=$CLJS.tF(c);return $CLJS.ag(function(f){return $CLJS.F.h($CLJS.tF($CLJS.V.g(f)),e)},a)};
$ua=function(a,b){var c=$CLJS.Wm.C(a,$CLJS.aQ,$CLJS.gg($CLJS.mf,$CLJS.Rg),b);return $CLJS.qe($CLJS.AH.g(a))?$CLJS.Wm.C(c,$CLJS.AH,$CLJS.mf,$CLJS.vV(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.IF,$CLJS.P,$CLJS.D_(b)],null))):c};
ava=function(a,b){return function e(d){return new $CLJS.Af(null,function(){for(var f=d;;)if(f=$CLJS.A(f)){if($CLJS.re(f)){var g=$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);a:for(var q=0;;)if(q<l){var u=$CLJS.be(g,q);$CLJS.F.h($CLJS.J_.g(u),$CLJS.X_)&&(u=$CLJS.wV(u),n.add(u));q+=1}else{g=!0;break a}return g?$CLJS.If($CLJS.Kf(n),e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}n=$CLJS.C(f);if($CLJS.F.h($CLJS.J_.g(n),$CLJS.X_))return $CLJS.pf($CLJS.wV(n),e($CLJS.zd(f)));f=$CLJS.zd(f)}else return null},null,null)}($CLJS.y5(a,
b,$CLJS.s0(a,b),new $CLJS.k(null,3,[$CLJS.P0,!1,$CLJS.U0,!0,$CLJS.M0,!1],null)))};bva=function(a){var b=$CLJS.u0(a);return $CLJS.m(b)?$CLJS.Vf(a8($CLJS.v0(a),b)):null};cva=function(a){return $CLJS.th.j($CLJS.ui,$CLJS.Rm.h($CLJS.QY(function(b){return $CLJS.V5(b,a)}),$CLJS.xg.g($CLJS.Zd)),$CLJS.Lta)};dva=function(a){return new $CLJS.k(null,3,[$CLJS.al,$CLJS.PF,$CLJS.V,a,$CLJS.Lk,$CLJS.p.g($CLJS.IK())],null)};
eva=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.h(a,$CLJS.V);return $CLJS.mn.l($CLJS.J([a,function(){var c=$CLJS.Ji(/^#(\d+)(-[a-z0-9-]*)?$/,b);$CLJS.m(c)?($CLJS.K(c,0,null),c=$CLJS.K(c,1,null),c=$CLJS.A_(c)):c=null;return $CLJS.m(c)?new $CLJS.k(null,2,[$CLJS.al,$CLJS.ZN,$CLJS.QQ,c],null):null}(),function(){var c=0==b.lastIndexOf("snippet:",0)?(0,$CLJS.Ca)(b.substring(8)):null;return $CLJS.m(c)?new $CLJS.k(null,2,[$CLJS.al,$CLJS.EN,$CLJS.xN,c],null):null}(),$CLJS.m($CLJS.YH.g(a))?null:new $CLJS.k(null,
1,[$CLJS.YH,$CLJS.Y4.h($CLJS.X4,b)],null)]))};o8=function(a){switch(arguments.length){case 1:return o8.g(arguments[0]);case 2:return o8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};p8=function(a){a=$CLJS.v3($CLJS.v0(a));return $CLJS.m($CLJS.vu(a,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Ou,$CLJS.Jta],null)))?$CLJS.mf.h($CLJS.ui,$CLJS.AO):$CLJS.ui};
q8=function(a,b){var c=p8(a);return $CLJS.O5(a,0,function(d){var e=$CLJS.vz.h($CLJS.Ota,c);d=$CLJS.Q.j($CLJS.Jm,d,e);d=$CLJS.mn.l($CLJS.J([d,$CLJS.ri(b,c)]));$CLJS.vz.h(c,$CLJS.yi($CLJS.mi(b)));$CLJS.s0(a,0);return d})};r8=function(a){switch(arguments.length){case 2:return r8.h(arguments[0],arguments[1]);case 4:return r8.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};
s8=function(a){switch(arguments.length){case 2:return s8.h(arguments[0],arguments[1]);case 3:return s8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};fva=function(a){return $CLJS.Vf($CLJS.ri($CLJS.s0(a,0),p8(a)))};gva=function(a,b){return $CLJS.O5(a,0,function(c){c=$CLJS.Uf(c);var d=$CLJS.M.h(c,$CLJS.uQ);return $CLJS.U.l(c,$CLJS.fQ,b,$CLJS.J([$CLJS.uQ,o8.h(b,d)]))})};
hva=function(a,b){return $CLJS.O5(a,0,function(c){c=$CLJS.Uf(c);var d=$CLJS.M.h(c,$CLJS.uQ),e=$CLJS.mi(d);return $CLJS.U.j(c,$CLJS.uQ,t8.h(d,$CLJS.ri(b,e)))})};iva=function(a){return $CLJS.fQ.g($CLJS.s0(a,0))};jva=function(a){return $CLJS.uQ.g($CLJS.s0(a,0))};kva=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.h(a,$CLJS.LF);return $CLJS.ag(function(c){return $CLJS.XG(b,c)},$CLJS.bL)};
lva=function(a,b){var c=Y7(b);return function g(e,f){try{if($CLJS.qe(f)&&3===$CLJS.E(f))try{if($CLJS.F.h($CLJS.EK.g($CLJS.G(f,1)),c)){var l=$CLJS.G(f,0);return $CLJS.U.j(f,0,$CLJS.C7.g?$CLJS.C7.g(l):$CLJS.C7.call(null,l))}throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)return $CLJS.FZ(g,e,f);throw l;}throw n;}}($CLJS.Rg,a)};
v8=function(a,b){var c=u8.h(a,b),d=$CLJS.Gi(0,$CLJS.E(c));return $CLJS.wg.l(new $CLJS.R(null,6,5,$CLJS.S,[new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.kR],null),new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.SO],null),new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.mZ],null),new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.AH],null),new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.ZO],null),new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.aQ],null)],null),function(){return function g(f){return new $CLJS.Af(null,function(){for(var l=f;;)if(l=$CLJS.A(l)){if($CLJS.re(l)){var n=
$CLJS.$c(l),q=$CLJS.E(n),u=$CLJS.Df(q);a:for(var v=0;;)if(v<q){var x=$CLJS.be(n,v),z=$CLJS.G(c,x);$CLJS.AH.g(z)instanceof $CLJS.N||u.add(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fO,x,$CLJS.AH],null));v+=1}else{n=!0;break a}return n?$CLJS.If($CLJS.Kf(u),g($CLJS.ad(l))):$CLJS.If($CLJS.Kf(u),null)}u=$CLJS.C(l);n=$CLJS.G(c,u);if($CLJS.AH.g(n)instanceof $CLJS.N)l=$CLJS.zd(l);else return $CLJS.pf(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fO,u,$CLJS.AH],null),g($CLJS.zd(l)))}else return null},null,null)}(d)}(),$CLJS.J([function(){return function g(f){return new $CLJS.Af(null,
function(){for(;;){var l=$CLJS.A(f);if(l){if($CLJS.re(l)){var n=$CLJS.$c(l),q=$CLJS.E(n),u=$CLJS.Df(q);a:for(var v=0;;)if(v<q){var x=$CLJS.be(n,v);u.add(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fO,x,$CLJS.BY],null));v+=1}else{n=!0;break a}return n?$CLJS.If($CLJS.Kf(u),g($CLJS.ad(l))):$CLJS.If($CLJS.Kf(u),null)}u=$CLJS.C(l);return $CLJS.pf(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fO,u,$CLJS.BY],null),g($CLJS.zd(l)))}return null}},null,null)}(d)}()]))};
w8=function(a,b,c){var d=$CLJS.K(c,0,null),e=$CLJS.K(c,1,null);e=$CLJS.Uf(e);var f=$CLJS.M.h(e,$CLJS.bQ),g=$CLJS.M.h(e,$CLJS.bR),l=$CLJS.K(c,2,null);return $CLJS.C($CLJS.LV(function(n){$CLJS.K(n,0,null);n=$CLJS.K(n,1,null);$CLJS.K(n,0,null);$CLJS.K(n,1,null);n=$CLJS.K(n,2,null);return $CLJS.F.h($CLJS.C(n),d)&&$CLJS.F.h($CLJS.bQ.g($CLJS.Zd(n)),f)&&$CLJS.F.h($CLJS.bR.g($CLJS.Zd(n)),g)&&$CLJS.F.h($CLJS.$d(n),l)},$CLJS.hg($CLJS.$m,$CLJS.kR.g($CLJS.s0(a,b)))))};
mva=function(a,b,c,d){c=w8(a,b,c);return $CLJS.m(c)?$CLJS.t0(a,b,$CLJS.RZ,$CLJS.J([new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.kR,c,2,1],null),$CLJS.Rm.h(function(e){return $CLJS.oF($CLJS.dg($CLJS.Bb),e)},$CLJS.mn),d])):a};nva=function(a,b,c){c=w8(a,b,c);return $CLJS.m(c)?$CLJS.t0(a,b,c8,$CLJS.J([new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.kR],null),$CLJS.vu($CLJS.s0(a,b),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.kR,c],null))])):a};
z8=function(a,b,c,d,e,f){var g=$CLJS.t0(a,b,f,$CLJS.J([d,e])),l=Y7(e);return $CLJS.qi.h(a,g)?$CLJS.C($CLJS.A($CLJS.Ag($CLJS.Gb,function(n,q){try{if($CLJS.qe(q)&&1===$CLJS.E(q))try{var u=$CLJS.G(q,0);if($CLJS.O(u,$CLJS.aQ))return new $CLJS.R(null,1,5,$CLJS.S,[function(){var I=$CLJS.D_(e);I=x8.Z?x8.Z(g,b,c,$CLJS.IF,$CLJS.P,I):x8.call(null,g,b,c,$CLJS.IF,$CLJS.P,I);return y8.C?y8.C(I,b,c,l):y8.call(null,I,b,c,l)}()],null);throw $CLJS.Z;}catch(I){if(I instanceof Error)if(n=I,n===$CLJS.Z)try{u=$CLJS.G(q,
0);if($CLJS.O(u,$CLJS.ZO))return new $CLJS.R(null,1,5,$CLJS.S,[function(){var T=x8.Z?x8.Z(g,b,c,$CLJS.ZO,$CLJS.P,l):x8.call(null,g,b,c,$CLJS.ZO,$CLJS.P,l);return y8.C?y8.C(T,b,c,l):y8.call(null,T,b,c,l)}()],null);throw $CLJS.Z;}catch(T){if(T instanceof Error){var v=T;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw T;}else throw n;else throw I;}else throw $CLJS.Z;}catch(I){if(I instanceof Error)if(n=I,n===$CLJS.Z)try{if($CLJS.qe(q)&&1===$CLJS.E(q))try{var x=$CLJS.G(q,0);if($CLJS.O(x,$CLJS.SO))return new $CLJS.R(null,
1,5,$CLJS.S,[y8.C?y8.C(g,b,c,l):y8.call(null,g,b,c,l)],null);throw $CLJS.Z;}catch(T){if(T instanceof Error)if(v=T,v===$CLJS.Z)try{x=$CLJS.G(q,0);if($CLJS.O(x,$CLJS.AH))return new $CLJS.R(null,1,5,$CLJS.S,[y8.C?y8.C(g,b,c,l):y8.call(null,g,b,c,l)],null);throw $CLJS.Z;}catch(W){if(W instanceof Error){var z=W;if(z===$CLJS.Z)throw $CLJS.Z;throw z;}throw W;}else throw v;else throw T;}else throw $CLJS.Z;}catch(T){if(T instanceof Error)if(v=T,v===$CLJS.Z)try{if($CLJS.qe(q)&&3===$CLJS.E(q))try{var B=$CLJS.G(q,
0);if($CLJS.O(B,$CLJS.fO))try{var H=$CLJS.G(q,2);if($CLJS.O(H,$CLJS.AH))return new $CLJS.R(null,1,5,$CLJS.S,[y8.C?y8.C(g,b,c,l):y8.call(null,g,b,c,l)],null);throw $CLJS.Z;}catch(W){if(W instanceof Error){z=W;if(z===$CLJS.Z)throw $CLJS.Z;throw z;}throw W;}else throw $CLJS.Z;}catch(W){if(W instanceof Error){z=W;if(z===$CLJS.Z)throw $CLJS.Z;throw z;}throw W;}else throw $CLJS.Z;}catch(W){if(W instanceof Error){z=W;if(z===$CLJS.Z)return new $CLJS.R(null,1,5,$CLJS.S,[g],null);throw z;}throw W;}else throw v;
else throw T;}else throw n;else throw I;}}($CLJS.Rg,d)))):g};
x8=function(a,b,c,d,e,f){var g=$CLJS.s0(a,b),l=$CLJS.yg(function(n){var q=$CLJS.vu(g,n);return $CLJS.m(q)?$CLJS.ig(function(u){return $CLJS.C($CLJS.A($CLJS.Ag($CLJS.Gb,function B(x,z){try{if($CLJS.qe(z)&&3===$CLJS.E(z))try{var H=$CLJS.G(z,0);if($CLJS.F.h(H,d))try{var I=$CLJS.G(z,1);if($CLJS.je(e)||sua($CLJS.yi(e),$CLJS.yi(I)))try{var T=$CLJS.G(z,2);if($CLJS.F.h(T,f))return new $CLJS.R(null,1,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,[n,u],null)],null);throw $CLJS.Z;}catch(ba){if(ba instanceof Error){var W=
ba;if(W===$CLJS.Z)throw $CLJS.Z;throw W;}throw ba;}else throw $CLJS.Z;}catch(ba){if(ba instanceof Error){W=ba;if(W===$CLJS.Z)throw $CLJS.Z;throw W;}throw ba;}else throw $CLJS.Z;}catch(ba){if(ba instanceof Error){W=ba;if(W===$CLJS.Z)throw $CLJS.Z;throw W;}throw ba;}else throw $CLJS.Z;}catch(ba){if(ba instanceof Error){W=ba;if(W===$CLJS.Z)return $CLJS.WY(B,x,z);throw W;}throw ba;}}($CLJS.Rg,u))))},q):null},$CLJS.J([v8(a,b)]));return $CLJS.Tb(function(n,q){var u=$CLJS.K(q,0,null);q=$CLJS.K(q,1,null);
return z8(n,b,c,u,q,c8)},a,l)};y8=function(a,b,c,d){b=d8(c,b);if($CLJS.m(b)){var e=$CLJS.s0(c,b);c=$CLJS.ag(function(f){f=$CLJS.Uf(f);var g=$CLJS.M.h(f,$CLJS.J_),l=$CLJS.M.h(f,$CLJS.L1);return $CLJS.F.h($CLJS.U_,g)&&$CLJS.F.h(d,l)?$CLJS.$_.g(f):null},$CLJS.z5(c,b,e));return $CLJS.m(c)?x8(a,b,a,$CLJS.PP,$CLJS.P,c):a}return a};
A8=function(a,b,c,d,e){var f=$CLJS.zV.g(c),g=$CLJS.s0(a,b);c=$CLJS.LV(function(q){var u=$CLJS.vu(g,q);if($CLJS.m(u)){var v=Y7(f);return $CLJS.m($CLJS.ag($CLJS.Rm.j($CLJS.vi([v]),$CLJS.EK,$CLJS.Zd),u))?q:null}return null},v8(a,b));var l=(d=$CLJS.F.h($CLJS.cK,d))?$CLJS.zV.g(e):null;e=d?function(q,u,v){return Aua(q,u,v,l)}:c8;var n=$CLJS.F.h(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.SO],null),c);a=d&&n&&$CLJS.F.h($CLJS.C(f),$CLJS.C(l))&&$CLJS.F.h($CLJS.$d(f),$CLJS.$d(l))?mva(a,b,f,$CLJS.ri($CLJS.Zd(l),new $CLJS.R(null,
2,5,$CLJS.S,[$CLJS.bR,$CLJS.bQ],null))):n?nva(a,b,f):a;return $CLJS.m(c)?z8(a,b,a,c,f,e):a};ova=function(a,b,c){return function g(e,f){try{if(b8(f,$CLJS.PP)&&$CLJS.F.h($CLJS.C3(f),b))return $CLJS.D3(f,c);throw $CLJS.Z;}catch(n){if(n instanceof Error){var l=n;if(l===$CLJS.Z)return $CLJS.FZ(g,e,f);throw l;}throw n;}}($CLJS.Rg,a)};
pva=function(a,b,c){var d=$CLJS.fO.g(a),e=-1<b&&b<$CLJS.E(d)?new $CLJS.R(null,2,5,$CLJS.S,[b,$CLJS.vu(d,new $CLJS.R(null,2,5,$CLJS.S,[b,$CLJS.qI],null))],null):null;b=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);if($CLJS.m($CLJS.m(b)?$CLJS.qi.h(e,c):b)){var f=$CLJS.G2();X7(f,$CLJS.xg.h($CLJS.qI,d));c=f(c);return ova($CLJS.Bu(a,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fO,b,$CLJS.qI],null),c),e,c)}return a};
qva=function(a,b,c){if($CLJS.Ae(c))return c;var d=function(){var e=$CLJS.vi([c]);return"string"===typeof c?$CLJS.Rm.h(e,$CLJS.qI):e}();return $CLJS.ag(function(e){var f=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);return $CLJS.m(d.g?d.g(e):d.call(null,e))?f:null},$CLJS.hg($CLJS.$m,$CLJS.fO.g($CLJS.s0(a,b))))};
B8=function(a,b,c,d){b=$CLJS.vz.h($CLJS.yi($CLJS.z5(b,c,$CLJS.s0(b,c))),$CLJS.yi($CLJS.z5(a,c,$CLJS.s0(a,c))));return $CLJS.Tb(function(e,f){return $CLJS.Q.S(x8,e,c,a,d.g?d.g(f):d.call(null,f))},a,b)};rva=function(a,b,c){a=B8(a,b,c,function(d){return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,new $CLJS.k(null,1,[$CLJS.yP,$CLJS.B3.g(d)],null),$CLJS.Lk.g(d)],null)});c=d8(a,c);return $CLJS.m(c)?B8(a,b,c,function(d){return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,$CLJS.P,$CLJS.$_.g(d)],null)}):a};
sva=function(a,b,c){return $CLJS.Ae(c)?$CLJS.vu($CLJS.s0(a,b),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.fO,c,$CLJS.qI],null)):$CLJS.oe(c)?$CLJS.qI.g(c):c};C8=function(a,b,c,d){var e=sva(a,b,c);return $CLJS.m(e)?(c=function(){var f=$CLJS.O5(a,b,function(g){var l=$CLJS.fO.g(g);l=d.h?d.h(l,e):d.call(null,l,e);return $CLJS.sV(g,$CLJS.fO,l)});return $CLJS.O5(f,b,function(g){return $CLJS.SZ.j(g,$CLJS.fO,function(l){return $CLJS.Vm.h(function(n){return j8(f,b,n)},l)})})}(),rva(c,a,b)):a};
tva=function(a){return $CLJS.Wm.C(a,$CLJS.yY,$CLJS.mf,new $CLJS.k(null,1,[$CLJS.wl,$CLJS.bZ],null))};uva=function(a){if($CLJS.F.h(1,$CLJS.E($CLJS.yY.g(a))))throw $CLJS.Ej($CLJS.bH("Cannot drop the only stage"),new $CLJS.k(null,1,[$CLJS.yY,$CLJS.yY.g(a)],null));return $CLJS.Wm.j(a,$CLJS.yY,$CLJS.Rm.h($CLJS.Sg,$CLJS.zi))};
t8=function t8(a){switch(arguments.length){case 0:return t8.A();case 1:return t8.g(arguments[0]);case 2:return t8.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return t8.l(arguments[0],arguments[1],new $CLJS.y(c.slice(2),0,null))}};t8.A=function(){return null};t8.g=function(a){return a};
t8.h=function(a,b){return $CLJS.m($CLJS.m(a)?a:b)?$CLJS.Tb(function(c,d){var e=$CLJS.tc(d),f=$CLJS.uc(d);if($CLJS.Ie(c,e)){d=$CLJS.U.j;var g=$CLJS.M.h(c,e);f=$CLJS.oe(g)&&$CLJS.oe(f)?t8.h(g,f):f;c=d.call($CLJS.U,c,e,f)}else c=$CLJS.U.j(c,e,f);return c},$CLJS.m(a)?a:$CLJS.P,$CLJS.A(b)):null};t8.l=function(a,b,c){return $CLJS.Tb(t8,$CLJS.m(a)?a:$CLJS.P,$CLJS.pf(b,c))};t8.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);c=$CLJS.D(c);return this.l(b,a,c)};t8.v=2;
var D8=function D8(a){switch(arguments.length){case 2:return D8.h(arguments[0],arguments[1]);case 3:return D8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};D8.h=function(a,b){return D8.j(a,null,b)};D8.j=function(a,b,c){b=$CLJS.m(b)?b:-1;c=$CLJS.zV.g(c);return $CLJS.t0(a,b,$CLJS.Wm,$CLJS.J([$CLJS.mZ,$CLJS.gg($CLJS.mf,$CLJS.Rg),c]))};D8.v=3;
var E8=function E8(a){switch(arguments.length){case 1:return E8.g(arguments[0]);case 2:return E8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};E8.g=function(a){return E8.h(a,null)};E8.h=function(a,b){return $CLJS.Vf($CLJS.mZ.g($CLJS.s0(a,$CLJS.m(b)?b:-1)))};E8.v=2;
var F8=function F8(a){switch(arguments.length){case 1:return F8.g(arguments[0]);case 2:return F8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};F8.g=function(a){return F8.h(a,-1)};F8.h=function(a,b){var c=$CLJS.s0(a,b);a=$CLJS.z5(a,b,c);return $CLJS.Vf($CLJS.th.j($CLJS.Rg,$CLJS.En(function(d){var e=$CLJS.Vf(i8(d));return $CLJS.m(e)?$CLJS.U.j(d,$CLJS.U1,e):null}),a))};F8.v=2;
var G8=function G8(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return G8.l(arguments[0],arguments[1],2<c.length?new $CLJS.y(c.slice(2),0,null):null)};G8.l=function(a,b,c){return $CLJS.vV($CLJS.th.h(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.QU.g(a),$CLJS.P,$CLJS.zV.g(b)],null),$CLJS.xg.h($CLJS.zV,c)))};G8.v=2;G8.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);c=$CLJS.D(c);return this.l(b,a,c)};
var H8=function H8(a){switch(arguments.length){case 2:return H8.h(arguments[0],arguments[1]);case 3:return H8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};H8.h=function(a,b){return H8.j(a,-1,b)};
H8.j=function(a,b,c){var d=$CLJS.K(c,0,null);$CLJS.K(c,1,null);c=$CLJS.K(c,2,null);var e=$CLJS.s0(a,b);a=$CLJS.z5(a,b,e);a=$CLJS.Hz($CLJS.xg.h($CLJS.wV,a),a);c=g8(c,$CLJS.mi(a));c=$CLJS.LV(function(f){return $CLJS.F.h($CLJS.QU.g(f),d)},i8(a.g?a.g(c):a.call(null,c)));return $CLJS.m(c)?c:$CLJS.G1(d)};H8.v=3;
var I8=function I8(a){switch(arguments.length){case 2:return I8.h(arguments[0],arguments[1]);case 3:return I8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};I8.h=function(a,b){return I8.j(a,-1,b)};I8.j=function(a,b,c){var d=j8(a,b,c);return $CLJS.t0(a,b,$CLJS.Wm,$CLJS.J([$CLJS.fO,function(e){return $CLJS.mf.h($CLJS.Sg(e),d)}]))};I8.v=3;
var u8=function u8(a){switch(arguments.length){case 1:return u8.g(arguments[0]);case 2:return u8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};u8.g=function(a){return u8.h(a,-1)};u8.h=function(a,b){return $CLJS.Vf($CLJS.M.h($CLJS.s0(a,b),$CLJS.fO))};u8.v=2;
var J8=function J8(a){switch(arguments.length){case 1:return J8.g(arguments[0]);case 2:return J8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};J8.g=function(a){return J8.h(a,-1)};J8.h=function(a){a=$CLJS.v3($CLJS.v0(a));a=$CLJS.Ou.g(a);return $CLJS.th.j($CLJS.Rg,$CLJS.Rm.h($CLJS.zg($CLJS.fg($CLJS.Ie,a)),$CLJS.xg.g(l8)),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.OI,$CLJS.jH,$CLJS.yJ,$CLJS.SJ],null))};J8.v=2;
var K8=function K8(a){switch(arguments.length){case 3:return K8.j(arguments[0],arguments[1],arguments[2]);case 4:return K8.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};K8.j=function(a,b,c){return K8.C(a,-1,b,c)};
K8.C=function(a,b,c){var d=$CLJS.C3(c),e=$CLJS.th.j($CLJS.ui,$CLJS.Rm.h($CLJS.xg.g($CLJS.C3),yua(function(f){return $CLJS.qi.h(f,d)})),u8.h(a,b));return m8($CLJS.Um.h(function(f){f=$CLJS.C3(f);return $CLJS.m(f)?$CLJS.Ie(e,f):null},$CLJS.y5(a,b,$CLJS.s0(a,b),new $CLJS.k(null,1,[$CLJS.M0,!1],null))))};K8.v=4;
var L8=function L8(a){switch(arguments.length){case 3:return L8.j(arguments[0],arguments[1],arguments[2]);case 4:return L8.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};L8.j=function(a,b,c){return L8.C(a,-1,b,c)};L8.C=function(a,b,c){return m8($CLJS.y5(a,b,c,new $CLJS.k(null,1,[$CLJS.M0,!1],null)))};L8.v=4;
var M8=function M8(a){switch(arguments.length){case 3:return M8.j(arguments[0],arguments[1],arguments[2]);case 4:return M8.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};M8.j=function(a,b,c){return M8.C(a,-1,b,c)};M8.C=function(){return $CLJS.Gpa};M8.v=4;
var N8=function N8(a){switch(arguments.length){case 2:return N8.h(arguments[0],arguments[1]);case 3:return N8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};N8.h=function(a,b){return N8.j(a,-1,b)};N8.j=function(a,b,c){c=$CLJS.LV($CLJS.B1,$CLJS.z5(a,b,c));return $CLJS.m(c)?(a=Pua(a,b,c),$CLJS.m(a)?G8.l($CLJS.G1($CLJS.lm),a,$CLJS.J([c])):null):null};N8.v=3;
var O8=function O8(a){switch(arguments.length){case 2:return O8.h(arguments[0],arguments[1]);case 3:return O8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};O8.h=function(a,b){return O8.j(a,-1,b)};
O8.j=function(a,b,c){var d=0===$CLJS.r0(a,b);if(d){d=u8.h(a,b);var e=$CLJS.je(d);c=e?e:$CLJS.F.h($CLJS.LG(c),$CLJS.tY)?$CLJS.F.h($CLJS.qI.g(c),$CLJS.qI.g($CLJS.C(d))):null;c=$CLJS.m(c)?$CLJS.u0(a):c}else c=d;return $CLJS.m(c)?(c=$CLJS.u0(a),c=$CLJS.w0(a,c),$CLJS.z0.j(a,b,c)):$CLJS.bH("Previous results")};O8.v=3;
var P8=function P8(a){switch(arguments.length){case 2:return P8.h(arguments[0],arguments[1]);case 3:return P8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};P8.h=function(a,b){return P8.j(a,-1,b)};P8.j=function(a,b,c){for(;;)if($CLJS.F.h($CLJS.LG(c),$CLJS.yV))c=$CLJS.wV(c);else return e8(a,b,$CLJS.ZO,c)};P8.v=3;
var Q8=function Q8(a){switch(arguments.length){case 1:return Q8.g(arguments[0]);case 2:return Q8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};Q8.g=function(a){return Q8.h(a,-1)};Q8.h=function(a,b){return $CLJS.Vf($CLJS.ZO.g($CLJS.s0(a,b)))};Q8.v=2;
var R8=function R8(a){switch(arguments.length){case 1:return R8.g(arguments[0]);case 2:return R8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};R8.g=function(a){return R8.h(a,-1)};
R8.h=function(a,b){var c=function(){var f=$CLJS.Ou.g($CLJS.v3($CLJS.v0(a)));return $CLJS.m(f)?f:$CLJS.ui}(),d=$CLJS.s0(a,b),e=$CLJS.z5(a,b,d);return $CLJS.Vf($CLJS.th.j($CLJS.Rg,$CLJS.Rm.j($CLJS.zg(function(f){f=$CLJS.HV.g(f);var g=null==f;return g?g:c.g?c.g(f):c.call(null,f)}),$CLJS.En(function(f){f=$CLJS.Uf(f);var g=$CLJS.M.h(f,$CLJS.DV),l=$CLJS.M.h(f,$CLJS.BV);if($CLJS.Fb(g))return f;if($CLJS.F.h(l,$CLJS.Et))return $CLJS.U.j(f,$CLJS.G_,e);g=$CLJS.Vf($CLJS.tZ(function(n){return $CLJS.x1(l,n)},e));
return $CLJS.m(g)?$CLJS.U.j(f,$CLJS.G_,g):null}),$CLJS.xg.g(function(f){return $CLJS.U.j(f,$CLJS.wl,$CLJS.JV)})),$CLJS.KV))};R8.v=2;var S8=function S8(a){switch(arguments.length){case 1:return S8.g(arguments[0]);case 2:return S8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};
S8.g=function(a){if($CLJS.Fb($CLJS.DV.g(a)))return $CLJS.vV(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.QU.g(a),$CLJS.P],null));var b=$CLJS.QU.g(a);b=$CLJS.xa.h?$CLJS.xa.h("aggregation operator %s requires an argument",b):$CLJS.xa.call(null,"aggregation operator %s requires an argument",b);throw $CLJS.Ej(b,new $CLJS.k(null,1,[$CLJS.qra,a],null));};S8.h=function(a,b){return $CLJS.vV(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.QU.g(a),$CLJS.P,$CLJS.zV.g(b)],null))};S8.v=2;
var T8=function T8(a){switch(arguments.length){case 2:return T8.h(arguments[0],arguments[1]);case 3:return T8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};T8.h=function(a,b){return T8.j(a,-1,b)};T8.j=function(a,b,c){c=$CLJS.wV($CLJS.de(c)?c.h?c.h(a,b):c.call(null,a,b):c);return e8(a,b,$CLJS.SO,c)};T8.v=3;
var U8=function U8(a){switch(arguments.length){case 1:return U8.g(arguments[0]);case 2:return U8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};U8.g=function(a){return U8.h(a,-1)};U8.h=function(a,b){return $CLJS.Vf($CLJS.SO.g($CLJS.s0(a,b)))};U8.v=2;
var V8=function V8(a){switch(arguments.length){case 1:return V8.g(arguments[0]);case 2:return V8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};V8.g=function(a){return V8.h(a,-1)};
V8.h=function(a,b){var c=function(){var f=$CLJS.s0(a,b);return function n(l){return new $CLJS.Af(null,function(){for(;;){var q=$CLJS.A(l);if(q){if($CLJS.re(q)){var u=$CLJS.$c(q),v=$CLJS.E(u),x=$CLJS.Df(v);a:for(var z=0;;)if(z<v){var B=$CLJS.be(u,z);B=$CLJS.U.j(B,$CLJS.U4,$CLJS.wV(B));x.add(B);z+=1}else{u=!0;break a}return u?$CLJS.If($CLJS.Kf(x),n($CLJS.ad(q))):$CLJS.If($CLJS.Kf(x),null)}x=$CLJS.C(q);return $CLJS.pf($CLJS.U.j(x,$CLJS.U4,$CLJS.wV(x)),n($CLJS.zd(q)))}return null}},null,null)}($CLJS.z5(a,
b,f))}(),d=$CLJS.th.j($CLJS.P,$CLJS.No(function(f,g){g=h8(a,g,$CLJS.xg.h($CLJS.U4,c));return $CLJS.m(g)?new $CLJS.R(null,2,5,$CLJS.S,[g,f],null):null}),U8.h(a,b)),e=$CLJS.Vf(c);return null==e?null:$CLJS.th.j($CLJS.Rg,$CLJS.xg.g(function(f){var g=$CLJS.U4.g(f);g=d.g?d.g(g):d.call(null,g);f=$CLJS.m(g)?$CLJS.U.j(f,$CLJS.I0,g):f;return $CLJS.Jm.h(f,$CLJS.U4)}),e)};V8.v=2;
var W8=function W8(a){switch(arguments.length){case 3:return W8.j(arguments[0],arguments[1],arguments[2]);case 4:return W8.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};W8.j=function(a,b,c){return W8.C(a,-1,b,c)};
W8.C=function(a,b,c,d){b=$CLJS.m(b)?b:-1;if($CLJS.m(Zua(a,b,c)))throw $CLJS.Ej("Expression name conflicts with a column in the same query stage",new $CLJS.k(null,1,[$CLJS.wR,c],null));return $CLJS.t0(a,b,$ua,$CLJS.J([$CLJS.E2($CLJS.zV.g(d),c)]))};W8.v=4;var X8=function X8(a){switch(arguments.length){case 1:return X8.g(arguments[0]);case 2:return X8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};X8.g=function(a){return X8.h(a,-1)};
X8.h=function(a,b){return $CLJS.Vf($CLJS.aQ.g($CLJS.s0(a,b)))};X8.v=2;var Y8=function Y8(a){switch(arguments.length){case 2:return Y8.h(arguments[0],arguments[1]);case 3:return Y8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};Y8.h=function(a,b){return Y8.j(a,-1,b)};
Y8.j=function(a,b,c){var d=$CLJS.th.h($CLJS.P,$CLJS.hg(function(f,g){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.D_(g),f],null)},X8.h(a,b))),e=$CLJS.s0(a,b);a=$CLJS.z5(a,b,e);return $CLJS.Vf($CLJS.tZ(function(f){return $CLJS.Fb(c)||$CLJS.qi.h($CLJS.J_.g(f),$CLJS.X_)||$CLJS.M.h(d,$CLJS.V.g(f))<c},a))};Y8.v=3;
var Z8=function Z8(a){switch(arguments.length){case 1:return Z8.g(arguments[0]);case 2:return Z8.h(arguments[0],arguments[1]);case 3:return Z8.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};Z8.g=function(a){return function(b,c){return Z8.j(b,c,a)}};Z8.h=function(a,b){return Z8.j(a,-1,b)};
Z8.j=function(a,b,c){var d=$CLJS.Vf($CLJS.Vm.h($CLJS.wV,c));c=function(){return null==d?null:$CLJS.th.j(d,$CLJS.Um.g(function(e){return g8(e,d)}),ava(a,b))}();return $CLJS.t0(a,b,$CLJS.sV,$CLJS.J([$CLJS.AH,c]))};Z8.v=3;var $8=function $8(a){switch(arguments.length){case 1:return $8.g(arguments[0]);case 2:return $8.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$8.g=function(a){return $8.h(a,-1)};
$8.h=function(a,b){return $CLJS.AH.g($CLJS.s0(a,b))};$8.v=2;var a9=function a9(a){switch(arguments.length){case 1:return a9.g(arguments[0]);case 2:return a9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};a9.g=function(a){return a9.h(a,-1)};
a9.h=function(a,b){var c=$8.h(a,b),d=$CLJS.je(c)?$CLJS.eg(!0):function(e){var f=$CLJS.wV(e);return $CLJS.ye($CLJS.ag(function(g){var l=$CLJS.n0.h(f,g);return $CLJS.m(l)?l:$CLJS.n0.h(f8(f),f8(g))},c))};return $CLJS.Vm.h(function(e){return $CLJS.U.j(e,$CLJS.a0,d(e))},$CLJS.y5(a,b,$CLJS.s0(a,b),new $CLJS.k(null,3,[$CLJS.P0,!1,$CLJS.U0,!1,$CLJS.M0,!1],null)))};a9.v=2;o8.g=function(a){return o8.h(a,null)};
o8.h=function(a,b){a=$CLJS.Vf(cva(a));var c=$CLJS.Vf($CLJS.yi($CLJS.mi(b)));if($CLJS.m($CLJS.m(a)?a:c)){var d=$CLJS.vz.h(a,c);a=$CLJS.vz.h(c,a);if($CLJS.F.l(1,$CLJS.E(d),$CLJS.J([$CLJS.E(a)]))){a=$CLJS.C(a);d=$CLJS.C(d);c=$CLJS.M.h(b,a);var e=$CLJS.F.h($CLJS.YH.g(c),$CLJS.Y4.h($CLJS.X4,a))?$CLJS.Y4.h($CLJS.X4,d):$CLJS.YH.g(c);c=$CLJS.U.l($CLJS.Jm.l(c,$CLJS.xN,$CLJS.J([$CLJS.QQ])),$CLJS.YH,e,$CLJS.J([$CLJS.V,d]));b=$CLJS.U.j($CLJS.Jm.h(b,a),d,c)}else b=$CLJS.mn.l($CLJS.J([uua($CLJS.dg(a),b),tua($CLJS.V,
$CLJS.xg.h(dva,d))]));b=$CLJS.wu(b,eva)}else b=$CLJS.P;return b};o8.v=2;r8.h=function(a,b){return r8.C(a,b,null,null)};r8.C=function(a,b,c,d){var e=o8.g(b);return q8($CLJS.z3(a,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.vV(new $CLJS.k(null,4,[$CLJS.wl,$CLJS.hZ,$CLJS.SY,c,$CLJS.uQ,e,$CLJS.fQ,b],null))],null)),d)};r8.v=4;s8.h=function(a,b){return s8.j(a,b,null)};s8.j=function(a,b,c){$CLJS.s0(a,0);return q8($CLJS.z3(b,$CLJS.yY.g(a)),c)};s8.v=3;
var b9=function b9(a){switch(arguments.length){case 1:return b9.g(arguments[0]);case 2:return b9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};b9.g=function(a){return b9.h(a,$CLJS.KI)};b9.h=function(a,b){a=$CLJS.B7.g(a);b=$CLJS.m(b)?b:$CLJS.KI;return $CLJS.U.j($CLJS.Sg(a),0,b)};b9.v=2;
var c9=function c9(a){switch(arguments.length){case 2:return c9.h(arguments[0],arguments[1]);case 3:return c9.j(arguments[0],arguments[1],arguments[2]);case 4:return c9.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};c9.h=function(a,b){return c9.C(a,-1,b,null)};c9.j=function(a,b,c){return c9.C(a,-1,b,c)};
c9.C=function(a,b,c,d){b=$CLJS.m(b)?b:-1;var e=function(){var f=$CLJS.B7.g(c);return $CLJS.m(d)?$CLJS.U.j($CLJS.Sg(f),0,d):f}();return $CLJS.t0(a,b,$CLJS.Wm,$CLJS.J([$CLJS.kR,function(f){return $CLJS.mf.h($CLJS.Sg(f),e)}]))};c9.v=4;var d9=function d9(a){switch(arguments.length){case 1:return d9.g(arguments[0]);case 2:return d9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};d9.g=function(a){return d9.h(a,-1)};
d9.h=function(a,b){return $CLJS.Vf($CLJS.M.h($CLJS.s0(a,b),$CLJS.kR))};d9.v=2;var e9=function e9(a){switch(arguments.length){case 1:return e9.g(arguments[0]);case 2:return e9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};e9.g=function(a){return e9.h(a,-1)};
e9.h=function(a,b){function c(g){return $CLJS.ag(function(l){var n=$CLJS.K(l,0,null);l=$CLJS.K(l,1,null);var q=$CLJS.wV(g),u=$CLJS.n0.h(q,l);l=$CLJS.m(u)?u:$CLJS.n0.h(q,f8(l));return $CLJS.m(l)?n:null},d)}var d=$CLJS.hg(function(g,l){$CLJS.K(l,0,null);$CLJS.K(l,1,null);l=$CLJS.K(l,2,null);return new $CLJS.R(null,2,5,$CLJS.S,[g,l],null)},d9.h(a,b)),e=$CLJS.Vf($CLJS.J7(a,b)),f=$CLJS.Vf($CLJS.L7.h(a,b));e=$CLJS.m($CLJS.m(e)?e:f)?$CLJS.wg.h(e,f):function(){var g=$CLJS.s0(a,b);return $CLJS.z5(a,b,g)}();
e=$CLJS.Vf(e);return null==e?null:$CLJS.th.j($CLJS.Rg,$CLJS.Rm.h($CLJS.zg(kva),$CLJS.xg.g(function(g){var l=c(g);return $CLJS.m(l)?$CLJS.U.j(g,$CLJS.J0,l):g})),e)};e9.v=2;var f9=function f9(a){switch(arguments.length){case 3:return f9.j(arguments[0],arguments[1],arguments[2]);case 4:return f9.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};f9.j=function(a,b,c){return f9.C(a,-1,b,c)};
f9.C=function(a,b,c,d){c=qva(a,b,c);return $CLJS.m(c)?$CLJS.t0(a,b,pva,$CLJS.J([c,d])):a};f9.v=4;var g9=function g9(a){switch(arguments.length){case 2:return g9.h(arguments[0],arguments[1]);case 3:return g9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};g9.h=function(a,b){return g9.j(a,-1,b)};g9.j=function(a,b,c){return C8(a,b,c,function(d,e){return $CLJS.Vf($CLJS.tZ(function(f){return $CLJS.qi.h($CLJS.qI.g(f),e)},d))})};
g9.v=3;var h9=function h9(a){switch(arguments.length){case 3:return h9.j(arguments[0],arguments[1],arguments[2]);case 4:return h9.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};h9.j=function(a,b,c){return h9.C(a,-1,b,c)};h9.C=function(a,b,c,d){return null==d?g9.j(a,b,c):C8(a,b,c,function(e,f){return $CLJS.Vm.h(function(g){return $CLJS.F.h($CLJS.qI.g(g),f)?d:g},e)})};h9.v=4;
var i9=function i9(a){switch(arguments.length){case 3:return i9.j(arguments[0],arguments[1],arguments[2]);case 4:return i9.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};i9.j=function(a,b,c){return i9.C(a,-1,b,c)};i9.C=function(a,b,c,d){return $CLJS.oe(c)&&$CLJS.F.h($CLJS.wl.g(c),$CLJS.tY)?h9.C?h9.C(a,b,c,d):h9.call(null,a,b,c,d):A8(a,b,c,$CLJS.cK,d)};i9.v=4;
var j9=function j9(a){switch(arguments.length){case 2:return j9.h(arguments[0],arguments[1]);case 3:return j9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};j9.h=function(a,b){return j9.j(a,-1,b)};j9.j=function(a,b,c){return $CLJS.oe(c)&&$CLJS.F.h($CLJS.wl.g(c),$CLJS.tY)?g9.j?g9.j(a,b,c):g9.call(null,a,b,c):A8(a,b,c,$CLJS.Uta,null)};j9.v=3;$CLJS.vva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(P8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.k9=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(S8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.wva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Wua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.xva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Q8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.yva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(R8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.zva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Xua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.l9=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.K5,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Ava=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.A5,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Bva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.I7,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Cva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(T8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Dva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(V8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Eva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(U8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Fva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Vua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Gva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Uua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Hva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(zua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Iva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Yua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Jva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(W8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Kva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(X8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Lva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Y8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Mva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Nva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Z8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Ova=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(a9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Pva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(D8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Qva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(E8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Rva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(F8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Sva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Eua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Tva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(G8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Uva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(H8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Vva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(J8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Wva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(I8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Xva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.W7,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Yva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(K8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Zva=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(M8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.$va=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(L8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.awa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Mua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.bwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(k8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.cwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(O8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.dwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Nua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.ewa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Sua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.fwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(u8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.gwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(N8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.hwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.V7,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.iwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Oua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.jwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.U7,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.kwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.C0,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.lwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Cua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.mwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(bva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.m9=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.Mta,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.n9=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.Nta,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.nwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(r8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.owa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(iva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.pwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(gva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.qwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(jva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.rwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(hva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.swa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(p8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.twa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(fva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.uwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(q8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.vwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(s8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.wwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(o8,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.xwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(lva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.ywa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(c9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.zwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(b9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Awa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(d9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Bwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(e9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.o9=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.u3,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Cwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.a5,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Dwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.wV,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Ewa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(j9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Fwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(g9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Gwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(f9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Hwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(i9,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Iwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(tva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Jwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(uva,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Kwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.M1,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Lwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.R1,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Mwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h(Dua,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.p9=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.J5,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Nwa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.G7,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();
$CLJS.Owa=function(){function a(c){var d=null;if(0<arguments.length){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $CLJS.y(e,0,null)}return b.call(this,d)}function b(c){return $CLJS.Q.h($CLJS.F7,c)}a.v=0;a.B=function(c){c=$CLJS.A(c);return b(c)};a.l=b;return a}();