var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.shared.formatting.internal.numbers.js");require("./metabase.shared.formatting.internal.numbers_core.js");require("./metabase.util.js");
'use strict';var B4=function(a){var b=$CLJS.mn.l;var c=$CLJS.Uf(a);var d=$CLJS.M.h(c,$CLJS.u4);c=$CLJS.M.h(c,$CLJS.v4);if($CLJS.m($CLJS.m(d)?$CLJS.F.h(c,"currency"):d)){c=$CLJS.p4.g;d=$CLJS.Ui.g(d);var e=$CLJS.r($CLJS.m4);d=e.g?e.g(d):e.call(null,d);c=c.call($CLJS.p4,d);c=new $CLJS.k(null,2,[$CLJS.t4,c,$CLJS.w4,c],null)}else c=new $CLJS.k(null,1,[$CLJS.w4,2],null);b=b.call($CLJS.mn,$CLJS.J([c,a]));return $CLJS.m($CLJS.x4.g(a))?$CLJS.U.l($CLJS.Jm.h(b,$CLJS.x4),$CLJS.w4,$CLJS.x4.g(a),$CLJS.J([$CLJS.t4,
$CLJS.x4.g(a)])):b},C4=function(a,b){if(null!=a&&null!=a.wf)a=a.wf(a,b);else{var c=C4[$CLJS.Na(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=C4._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $CLJS.Ob("NumberFormatter.format-number-basic",a);}return a},Ora=function(a,b){var c=$CLJS.ZE(a.formatToParts(b),$CLJS.J([new $CLJS.k(null,1,[$CLJS.kk,!0],null)]));a=$CLJS.m($CLJS.ag(function(d){return $CLJS.F.h($CLJS.al.g(d),"exponentMinusSign")},c))?c:function(){var d=$CLJS.Hi(function(f){return $CLJS.qi.h($CLJS.al.g(f),
"exponentInteger")},c),e=$CLJS.K(d,0,null);d=$CLJS.K(d,1,null);return $CLJS.wg.l(e,new $CLJS.R(null,1,5,$CLJS.S,[new $CLJS.k(null,2,[$CLJS.al,"exponentPlusSign",$CLJS.vl,"+"],null)],null),$CLJS.J([d]))}();return $CLJS.Q.h($CLJS.p,$CLJS.xg.h(function(d){var e=$CLJS.Uf(d);d=$CLJS.M.h(e,$CLJS.al);e=$CLJS.M.h(e,$CLJS.vl);switch(d){case "exponentSeparator":return"e";default:return e}},a))},Pra=function(a,b){switch($CLJS.v4.g(b)){case "scientific":return function(c){return Ora(a,c)};default:return function(c){return a.format(c)}}},
D4=function(a,b,c,d,e){this.options=a;this.bh=b;this.eh=c;this.Le=d;this.Ni=e;this.D=393216;this.K=0},Qra=function(a,b){return $CLJS.Q.h($CLJS.p,function(){return function e(d){return new $CLJS.Af(null,function(){for(var f=d;;)if(f=$CLJS.A(f)){if($CLJS.re(f)){var g=$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);return function(){for(var v=0;;)if(v<l){var x=$CLJS.be(g,v),z=$CLJS.Uf(x);x=$CLJS.M.h(z,$CLJS.al);z=$CLJS.M.h(z,$CLJS.vl);var B=new $CLJS.ti(null,new $CLJS.k(null,2,["currency",null,"integer",null],
null),null);B=B.g?B.g(x):B.call(null,x);$CLJS.m(B)&&(x=$CLJS.F.h(x,"integer")?b:z,n.add(x));v+=1}else return!0}()?$CLJS.If($CLJS.Kf(n),e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}var q=$CLJS.C(f);q=$CLJS.Uf(q);var u=$CLJS.M.h(q,$CLJS.al);q=$CLJS.M.h(q,$CLJS.vl);if($CLJS.m(function(){var v=new $CLJS.ti(null,new $CLJS.k(null,2,["currency",null,"integer",null],null),null);return v.g?v.g(u):v.call(null,u)}()))return $CLJS.pf($CLJS.F.h(u,"integer")?b:q,e($CLJS.zd(f)));f=$CLJS.zd(f)}else return null},null,
null)}($CLJS.ZE(a.bh.formatToParts(1),$CLJS.J([$CLJS.kk,!0])))}())},E4=function(a){var b=$CLJS.F.h($CLJS.v4.g(a),"currency")?2:null;b=new Intl.NumberFormat("en",$CLJS.pn($CLJS.oF($CLJS.Gb,$CLJS.Yh([$CLJS.Lra,$CLJS.Dra,$CLJS.Gra,$CLJS.Ira,$CLJS.Nra,$CLJS.u4,$CLJS.Hra,$CLJS.Jra,$CLJS.Era,$CLJS.Fra],[$CLJS.w4.h(a,b),$CLJS.z4.g(a),$CLJS.y4.g(a),$CLJS.Kra.g(a),$CLJS.F.h($CLJS.v4.g(a),"scientific")?null:$CLJS.v4.h(a,"decimal"),$CLJS.u4.g(a),!0,$CLJS.t4.h(a,b),$CLJS.F.h($CLJS.v4.g(a),"scientific")?"scientific":
null,$CLJS.A4.g(a)]))));var c=$CLJS.z4.g(a);var d=$CLJS.u4.g(a);c=$CLJS.m(d)?null==c||$CLJS.F.h(c,"symbol"):d;d=Pra(b,a);return new D4(a,b,c,d,$CLJS.P)},F4=function(a,b){return E4(B4(b)).wf(null,a)},H4=function(a,b){var c=$CLJS.Jm.l(b,$CLJS.TF,$CLJS.J([$CLJS.v4])),d=Math.abs(a);if(0===a)return"0";if(1E3>d)return $CLJS.G4.h?$CLJS.G4.h(a,c):$CLJS.G4.call(null,a,c);b=$CLJS.C($CLJS.Ag(function(f){return d>=$CLJS.C(f)},Rra));var e=$CLJS.K(b,0,null);b=$CLJS.K(b,1,null);return[$CLJS.p.g(function(){var f=
a/e,g=$CLJS.mn.l($CLJS.J([c,new $CLJS.k(null,2,[$CLJS.t4,1,$CLJS.w4,1],null)]));return $CLJS.G4.h?$CLJS.G4.h(f,g):$CLJS.G4.call(null,f,g)}()),$CLJS.p.g(b)].join("")},Sra=function(a,b){var c=B4(b);if($CLJS.m(I4.g(c)))b=I4.g(c);else if($CLJS.Fb($CLJS.x4.g(c))&&$CLJS.Fb($CLJS.t4.g(c))&&$CLJS.qi.h($CLJS.v4.g(c),"currency")&&Math.abs(a)<($CLJS.F.h($CLJS.v4.g(c),"percent")?.01:1)){b=$CLJS.U.j;var d=$CLJS.Jm.h(c,$CLJS.w4);c=$CLJS.A4.h(c,0);b=E4(b.call($CLJS.U,d,$CLJS.y4,2>c?2:c))}else b=E4(c);return C4(b,
a)};D4.prototype.O=function(a,b){return new D4(this.options,this.bh,this.eh,this.Le,b)};D4.prototype.M=function(){return this.Ni};
D4.prototype.wf=function(a,b){a=this.Le.g?this.Le.g(b):this.Le.call(null,b);var c=$CLJS.Mra.g(this.options);$CLJS.m($CLJS.m(c)?$CLJS.qi.h(c,".,"):c)&&(b=$CLJS.C(c),c=$CLJS.Zd(c),a=$CLJS.zu(a,/[\.,]/,new $CLJS.k(null,2,[",",$CLJS.m(c)?c:"",".",b],null)));$CLJS.m(this.eh)&&(b=$CLJS.u4.g(this.options),c=$CLJS.n4(b),a=$CLJS.zu($CLJS.zu(a,[$CLJS.Ai(b)," "].join(""),c),$CLJS.Ai(b),c));return a};
var I4=new $CLJS.N(null,"number-formatter","number-formatter",929788393),J4=new $CLJS.N(null,"scale","scale",-230427353),K4=new $CLJS.N(null,"negative-in-parentheses","negative-in-parentheses",-1676084141),Tra=new $CLJS.N(null,"scientific","scientific",316285837);var L4=new $CLJS.k(null,1,[$CLJS.z4,"symbol"],null),Ura=$CLJS.pn(L4),Rra=new $CLJS.R(null,4,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,[1E12,"T"],null),new $CLJS.R(null,2,5,$CLJS.S,[1E9,"B"],null),new $CLJS.R(null,2,5,$CLJS.S,[1E6,"M"],null),new $CLJS.R(null,2,5,$CLJS.S,[1E3,"k"],null)],null),M4=function(){var a=$CLJS.ij.g($CLJS.P),b=$CLJS.ij.g($CLJS.P),c=$CLJS.ij.g($CLJS.P),d=$CLJS.ij.g($CLJS.P),e=$CLJS.M.j($CLJS.P,$CLJS.Vk,$CLJS.rj.A?$CLJS.rj.A():$CLJS.rj.call(null));return new $CLJS.Aj($CLJS.$i.h("metabase.shared.formatting.numbers",
"format-number-compact*"),function(f,g){f=$CLJS.Uf(g);return $CLJS.M.h(f,$CLJS.v4)},$CLJS.Uj,e,a,b,c,d)}();M4.o(null,$CLJS.Uj,function(a,b){return H4(a,b)});M4.o(null,"percent",function(a,b){return[$CLJS.p.g(H4(100*a,b)),"%"].join("")});M4.o(null,"currency",function(a,b){b=$CLJS.mn.l($CLJS.J([b,L4]));var c=E4(b);return 1E3>Math.abs(a)?c.wf(null,a):Qra(c,H4(a,b))});M4.o(null,"scientific",function(a,b){return F4(a,$CLJS.mn.l($CLJS.J([b,new $CLJS.k(null,2,[$CLJS.w4,1,$CLJS.t4,1],null)])))});
$CLJS.G4=function G4(a,b){b=$CLJS.xF(b);var d=$CLJS.Uf(b);b=$CLJS.M.h(d,$CLJS.TF);var e=$CLJS.M.h(d,K4),f=$CLJS.M.h(d,$CLJS.v4),g=$CLJS.M.h(d,J4);return $CLJS.m($CLJS.m(g)?!isNaN(g):g)?(b=g*a,f=$CLJS.Jm.h(d,J4),G4.h?G4.h(b,f):G4.call(null,b,f)):$CLJS.m(function(){var l=0>a;return l?e:l}())?["(",$CLJS.p.g(function(){var l=-a,n=$CLJS.U.j(d,K4,!1);return G4.h?G4.h(l,n):G4.call(null,l,n)}()),")"].join(""):$CLJS.m(b)?M4.h(a,B4($CLJS.Jm.h(d,$CLJS.TF))):$CLJS.F.h($CLJS.Ui.g(f),Tra)?F4(a,d):Sra(a,d)};
module.exports={compact_currency_options_js:Ura,format_number:$CLJS.G4};