var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.data.js");require("./clojure.set.js");require("./clojure.string.js");require("./malli.core.js");require("./malli.error.js");require("./medley.core.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.options.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.util.js");require("./metabase.util.js");require("./metabase.util.log.js");
'use strict';var y2,iqa,z2,A2,jqa,kqa,B2,C2,lqa,mqa,nqa,oqa,pqa,qqa,rqa,J2,K2,L2,M2,O2,tqa,P2,Q2,uqa,D2,F2;y2=function(a,b){return $CLJS.oe(a)?$CLJS.M.h(a,b):a};
iqa=function(){return function(){function a(g,l,n){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.al.j?$CLJS.al.j(g,l,n):$CLJS.al.call(null,g,l,n),$CLJS.sn.j?$CLJS.sn.j(g,l,n):$CLJS.sn.call(null,g,l,n)],null)}function b(g,l){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.al.h?$CLJS.al.h(g,l):$CLJS.al.call(null,g,l),$CLJS.sn.h?$CLJS.sn.h(g,l):$CLJS.sn.call(null,g,l)],null)}function c(g){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.al.g?$CLJS.al.g(g):$CLJS.al.call(null,g),$CLJS.sn.g?$CLJS.sn.g(g):$CLJS.sn.call(null,
g)],null)}function d(){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.al.A?$CLJS.al.A():$CLJS.al.call(null),$CLJS.sn.A?$CLJS.sn.A():$CLJS.sn.call(null)],null)}var e=null,f=function(){function g(n,q,u,v){var x=null;if(3<arguments.length){x=0;for(var z=Array(arguments.length-3);x<z.length;)z[x]=arguments[x+3],++x;x=new $CLJS.y(z,0,null)}return l.call(this,n,q,u,x)}function l(n,q,u,v){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Q.S($CLJS.al,n,q,u,v),$CLJS.Q.S($CLJS.sn,n,q,u,v)],null)}g.v=3;g.B=function(n){var q=
$CLJS.C(n);n=$CLJS.D(n);var u=$CLJS.C(n);n=$CLJS.D(n);var v=$CLJS.C(n);n=$CLJS.zd(n);return l(q,u,v,n)};g.l=l;return g}();e=function(g,l,n,q){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,g);case 2:return b.call(this,g,l);case 3:return a.call(this,g,l,n);default:var u=null;if(3<arguments.length){u=0;for(var v=Array(arguments.length-3);u<v.length;)v[u]=arguments[u+3],++u;u=new $CLJS.y(v,0,null)}return f.l(g,l,n,u)}throw Error("Invalid arity: "+arguments.length);};e.v=
3;e.B=f.B;e.A=d;e.g=c;e.h=b;e.j=a;e.l=f.l;return e}()};z2=function(a,b){return $CLJS.le(a)||$CLJS.me(a)?$CLJS.M.h(a,b):$CLJS.ne(a)?$CLJS.M.h($CLJS.Sg(a),b):null};A2=function(a,b){var c=$CLJS.A(b);for(a=$CLJS.A($CLJS.qg(a,b));;)if(a)c=$CLJS.D(c),a=$CLJS.D(a);else return c};jqa=function(a,b,c){return $CLJS.Tb(function(d,e){var f=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);return null==e?d:$CLJS.U.j(d,f,e)},null==b?a:$CLJS.U.j(a,$CLJS.ZO,b),$CLJS.fu(2,2,c))};
kqa=function(){var a=$CLJS.Wp.h($CLJS.pZ,null),b=$CLJS.hy(a,$CLJS.lba,function(c){return $CLJS.Wo(c,$CLJS.Rg)});return function(){function c(f,g,l){return(g=$CLJS.A(b.j?b.j(f,g,l):b.call(null,f,g,l)))?new $CLJS.k(null,3,[$CLJS.hm,a,$CLJS.vl,f,$CLJS.Nt,g],null):null}function d(f){return e.j(f,$CLJS.Rg,$CLJS.Rg)}var e=null;e=function(f,g,l){switch(arguments.length){case 1:return d.call(this,f);case 3:return c.call(this,f,g,l)}throw Error("Invalid arity: "+arguments.length);};e.g=d;e.j=c;return e}()};
B2=function(a){return kqa()(a,$CLJS.Rg,$CLJS.Rg)};C2=function(a,b,c,d){d=$CLJS.m(d)?d:$CLJS.cs($CLJS.hm.g(a));if($CLJS.m(b)){var e=y2($CLJS.Yu.g(b),c);$CLJS.m(e)?(e=$CLJS.gs(e,d),a=e.h?e.h(a,d):e.call(null,a,d)):a=null;return $CLJS.m(a)?a:y2($CLJS.Wu.g(b),c)}return null};
lqa=function(a,b){a=$CLJS.Uf(a);var c=$CLJS.M.h(a,$CLJS.hm),d=$CLJS.M.h(a,$CLJS.al);b=$CLJS.Uf(b);var e=$CLJS.M.j(b,$CLJS.Nt,$CLJS.Mba),f=$CLJS.M.j(b,$CLJS.Hba,!0),g=$CLJS.M.h(b,$CLJS.gv),l=$CLJS.M.j(b,$CLJS.ev,$CLJS.cv),n=C2(a,$CLJS.is.g(c),g,b);if($CLJS.m(n))return n;n=C2(a,$CLJS.cu.g(c),g,b);if($CLJS.m(n))return n;n=C2(a,e.g?e.g(d):e.call(null,d),g,b);if($CLJS.m(n))return n;n=C2(a,function(){var q=$CLJS.Ep.g(c);return e.g?e.g(q):e.call(null,q)}(),g,b);if($CLJS.m(n))return n;n=C2(a,$CLJS.is.g(c),
l,b);if($CLJS.m(n))return n;n=C2(a,$CLJS.cu.g(c),l,b);if($CLJS.m(n))return n;d=C2(a,e.g?e.g(d):e.call(null,d),l,b);if($CLJS.m(d))return d;d=C2(a,function(){var q=$CLJS.Ep.g(c);return e.g?e.g(q):e.call(null,q)}(),l,b);if($CLJS.m(d))return d;g=$CLJS.m(f)?C2(a,e.g?e.g($CLJS.av):e.call(null,$CLJS.av),g,b):f;return $CLJS.m(g)?g:$CLJS.m(f)?C2(a,e.g?e.g($CLJS.av):e.call(null,$CLJS.av),l,b):f};
mqa=function(a,b,c){a=$CLJS.S;var d=$CLJS.th.h;var e=$CLJS.sn.g(b);var f=$CLJS.Uf(b);var g=$CLJS.M.h(f,$CLJS.hm),l=$CLJS.Uf(c);f=$CLJS.M.h(l,$CLJS.gv);l=$CLJS.M.j(l,$CLJS.ev,$CLJS.cv);g=$CLJS.is.g(g);f=y2($CLJS.dv.g(g),f);f=$CLJS.m(f)?f:y2($CLJS.dv.g(g),l);d=d.call($CLJS.th,e,f);return new $CLJS.R(null,2,5,a,[d,lqa(b,c)],null)};
nqa=function(a){var b=$CLJS.Uf(a),c=$CLJS.M.h(b,$CLJS.vl);a=$CLJS.M.h(b,$CLJS.Nt);var d=$CLJS.Uf(null),e=$CLJS.M.j(d,$CLJS.Iba,$CLJS.Dk),f=$CLJS.M.j(d,$CLJS.Kba,mqa);return $CLJS.m(a)?$CLJS.Tb(function(g,l){var n=f.j?f.j(b,l,d):f.call(null,b,l,d),q=$CLJS.K(n,0,null);n=$CLJS.K(n,1,null);l=$CLJS.U.j(l,$CLJS.Dk,n);l=e.g?e.g(l):e.call(null,l);return D2(g,c,q,l)},null,a):null};
$CLJS.E2=function(a,b){return $CLJS.Bu($CLJS.C_(a)?a:new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.vl,new $CLJS.k(null,2,[$CLJS.EK,$CLJS.p.g($CLJS.IK()),$CLJS.qk,$CLJS.LK(a)],null),a],null),new $CLJS.R(null,2,5,$CLJS.S,[1,$CLJS.VK],null),b)};$CLJS.G2=function(){return $CLJS.Rm.h(F2,$CLJS.NZ($CLJS.J([$CLJS.OZ,$CLJS.tF,$CLJS.PZ,function(a,b){return F2.g([$CLJS.p.g(a),"_",$CLJS.p.g(b)].join(""))}])))};
oqa=function(a,b,c){var d=new $CLJS.ti(null,new $CLJS.k(null,2,[$CLJS.It,null,$CLJS.wn,null],null),null),e=$CLJS.m(d.g?d.g(b):d.call(null,b))?$CLJS.xu(2,c):$CLJS.xu(1,c);b=$CLJS.m(d.g?d.g(b):d.call(null,b))?A2(2,c):A2(1,c);var f=$CLJS.K(b,0,null);return $CLJS.A(e)?$CLJS.RZ.j(a,e,function(g){var l=$CLJS.U.j(g,f,null);return $CLJS.qe(g)?$CLJS.th.j($CLJS.Rg,$CLJS.Um.g($CLJS.Bb),l):$CLJS.oe(g)?$CLJS.oF($CLJS.Gb,l):l}):$CLJS.Jm.h(a,f)};
pqa=function(a){for(var b=0;;){var c=$CLJS.G($CLJS.yY.g(a),b);a:{var d=c;for(var e=$CLJS.Rg;;){var f=$CLJS.C($CLJS.xg.h(iqa(),$CLJS.Ag($CLJS.Rm.j(H2,$CLJS.C,$CLJS.sn),$CLJS.Nt.g(B2(d)))));if($CLJS.m(f)){var g=f;f=$CLJS.K(g,0,null);g=$CLJS.K(g,1,null);var l=oqa(d,f,g),n=$CLJS.mF($CLJS.PD);if($CLJS.m($CLJS.qF("metabase.lib.convert",n))){var q=$CLJS.UF.l($CLJS.J([$CLJS.KE,$CLJS.gj.l($CLJS.J([g]))])),u=$CLJS.UF,v=u.l,x=$CLJS.gj,z=x.l;var B=f;B=$CLJS.m(B)?B:nqa(B2(d));$CLJS.rF("metabase.lib.convert",n,
$CLJS.z_("Clean: Removing bad clause in %s due to error %s:\n%s",$CLJS.J([q,v.call(u,$CLJS.J([$CLJS.KE,z.call(x,$CLJS.J([B]))])),$CLJS.UF.l($CLJS.J([$CLJS.zE,$CLJS.B_($CLJS.C($CLJS.sz(d,l)))]))])),null)}if($CLJS.F.h(l,d))break a;d=l;e=$CLJS.mf.h(e,new $CLJS.R(null,2,5,$CLJS.S,[f,g],null))}else break a}}if($CLJS.F.h(c,d)){if($CLJS.F.h(b,$CLJS.E($CLJS.yY.g(a))-1))return a;b+=1}else a=$CLJS.Wm.S(a,$CLJS.yY,$CLJS.U,b,d)}};
qqa=function(a){var b=$CLJS.G2();return $CLJS.Vm.h(function(c){return $CLJS.F.h($CLJS.qI.g(c),"__join")?$CLJS.Wm.j(c,$CLJS.qI,b):c},a)};rqa=function(a){return"string"===typeof $CLJS.kP.g(a)?$CLJS.Jm.h($CLJS.U.j(a,$CLJS.XY,$CLJS.I_($CLJS.kP.g(a))),$CLJS.kP):a};J2=function(a,b){var c=$CLJS.M.j(a,b,I2);if($CLJS.F.h(c,I2))throw $CLJS.Ej(["Unable to find ",$CLJS.gj.l($CLJS.J([b]))," in map."].join(""),new $CLJS.k(null,2,[sqa,a,$CLJS.Ru,b],null));return c};
K2=function(){return $CLJS.Um.g(function(a){var b=$CLJS.K(a,0,null);$CLJS.K(a,1,null);return $CLJS.zf(b)&&$CLJS.F.h($CLJS.sf(b),"lib")})};L2=function(a){return $CLJS.th.j($CLJS.P,K2(),a)};M2=function(a){return $CLJS.Vf($CLJS.th.j($CLJS.P,$CLJS.Rm.h(K2(),$CLJS.Um.g(function(b){var c=$CLJS.K(b,0,null);$CLJS.K(b,1,null);return $CLJS.F.h(c,$CLJS.qk)})),a))};
O2=function(a){var b=$CLJS.A(a);a=$CLJS.C(b);var c=$CLJS.D(b);b=$CLJS.C(c);c=$CLJS.D(c);var d=$CLJS.th.j(new $CLJS.R(null,1,5,$CLJS.S,[a],null),$CLJS.xg.g($CLJS.N2),c);a=$CLJS.F.h(a,$CLJS.dI)&&$CLJS.D(c)?$CLJS.mf.h($CLJS.ie(d),new $CLJS.k(null,1,[$CLJS.Uj,$CLJS.he(d)],null)):d;b=$CLJS.Vf(M2(b));return $CLJS.m(b)?new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.yN,a,b],null):a};tqa=function(a){return $CLJS.th.j($CLJS.Rg,$CLJS.Rm.h($CLJS.xg.g(function(b){return $CLJS.pF(b,$CLJS.YF)}),$CLJS.xg.g($CLJS.N2)),$CLJS.G_.g(a))};
P2=function(a){a=$CLJS.Uf(a);a=$CLJS.M.h(a,$CLJS.yY);a=$CLJS.C($CLJS.Tb(function(b,c){var d=$CLJS.K(b,0,null),e=$CLJS.K(b,1,null);b=$CLJS.S;var f=$CLJS.N2.g(c);d=$CLJS.m(d)?$CLJS.U.j(f,$CLJS.xQ,d):f;d=$CLJS.m(e)?$CLJS.U.j(d,$CLJS.$O,tqa(e)):d;return new $CLJS.R(null,2,5,b,[d,$CLJS.SY.g(c)],null)},null,a));return $CLJS.m($CLJS.fQ.g(a))?$CLJS.ZM(a,new $CLJS.k(null,1,[$CLJS.fQ,$CLJS.GN],null)):a};
Q2=function(a,b,c){var d=$CLJS.F.h($CLJS.E($CLJS.M.h(a,b)),1)?$CLJS.SZ.j(a,b,$CLJS.Rm.h($CLJS.N2,$CLJS.C)):a;a=1<$CLJS.E($CLJS.M.h(a,b))?$CLJS.SZ.j(d,b,function(e){return $CLJS.th.j(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.Qj],null),$CLJS.xg.g($CLJS.N2),e)}):d;return $CLJS.ZM(a,$CLJS.Tf([b,c]))};uqa=function(a){var b=$CLJS.XY.g(a);return $CLJS.m(b)?$CLJS.U.j($CLJS.Jm.h(a,$CLJS.XY),$CLJS.kP,["card__",$CLJS.p.g(b)].join("")):a};
D2=function D2(a,b,c,d){var f=$CLJS.A(c);c=$CLJS.C(f);var g=$CLJS.D(f),l=z2(b,c);f=$CLJS.m(a)?a:$CLJS.ne(b)?$CLJS.Rg:$CLJS.pe(b)?$CLJS.P:$CLJS.ae(b);return $CLJS.m($CLJS.m(c)?$CLJS.bv.g($CLJS.ge(f)):c)?a:$CLJS.m(c)?(b=z2(f,c),d=D2.C?D2.C(b,l,g,d):D2.call(null,b,l,g,d),$CLJS.Be(c)&&$CLJS.ne(f)&&c>$CLJS.E(f)&&(b=$CLJS.tg(c-$CLJS.E(f),null),b=$CLJS.wg.h(f,b),f=null==f||$CLJS.we(f)?b:$CLJS.th.h($CLJS.ae(f),b)),null==f||$CLJS.me(f)?$CLJS.U.j(f,c,d):$CLJS.le(f)?$CLJS.mf.h(f,d):$CLJS.Q.h($CLJS.Y,$CLJS.U.j($CLJS.Sg(f),
c,d))):$CLJS.oe(a)?(c=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.Jba],null),D2.C?D2.C(f,b,c,d):D2.call(null,f,b,c,d)):$CLJS.m($CLJS.bv.g($CLJS.ge(f)))?$CLJS.mf.h(f,d):$CLJS.qe($CLJS.Vf(f))?f:$CLJS.fe(new $CLJS.R(null,1,5,$CLJS.S,[d],null),new $CLJS.k(null,1,[$CLJS.bv,!0],null))};F2=function F2(a){switch(arguments.length){case 1:return F2.g(arguments[0]);case 2:return F2.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};
F2.g=function(a){return F2.h(a,60)};F2.h=function(a,b){if((new TextEncoder).encode(a).length<=b)return a;var c;a:for(c=($CLJS.AV.str(a,0)>>>0).toString(16);;)if(8>$CLJS.E(c))c=["0",$CLJS.p.g(c)].join("");else break a;b=new Uint8Array(b-9);b=(new TextEncoder).encodeInto(a,b);return[a.substring(0,b.read),"_",$CLJS.p.g(c)].join("")};F2.v=2;
var I2=new $CLJS.N("metabase.lib.convert","not-found","metabase.lib.convert/not-found",967996550),R2=new $CLJS.N("metabase.lib.convert","aggregation-or-expression","metabase.lib.convert/aggregation-or-expression",1924029672),S2=new $CLJS.N("metabase.lib.convert","expression","metabase.lib.convert/expression",1648102782),sqa=new $CLJS.N(null,"m","m",1632677161),T2=new $CLJS.N("metabase.lib.convert","aggregation","metabase.lib.convert/aggregation",108290790);var U2,V2,H2,vqa,wqa,xqa,yqa,zqa,Aqa,Bqa,Cqa,Dqa,Eqa;U2=$CLJS.P;V2=$CLJS.P;H2=new $CLJS.ti(null,new $CLJS.k(null,7,[$CLJS.mZ,null,$CLJS.AH,null,$CLJS.fO,null,$CLJS.aQ,null,$CLJS.SO,null,$CLJS.kR,null,$CLJS.ZO,null],null),null);vqa=$CLJS.ij.g($CLJS.P);wqa=$CLJS.ij.g($CLJS.P);xqa=$CLJS.ij.g($CLJS.P);yqa=$CLJS.ij.g($CLJS.P);zqa=$CLJS.M.j(new $CLJS.k(null,1,[$CLJS.Vk,$CLJS.MG],null),$CLJS.Vk,$CLJS.rj.A?$CLJS.rj.A():$CLJS.rj.call(null));
$CLJS.W2=new $CLJS.Aj($CLJS.$i.h("metabase.lib.convert","-\x3epMBQL"),$CLJS.LG,$CLJS.Uj,zqa,vqa,wqa,xqa,yqa);$CLJS.W2.o(null,$CLJS.Uj,function(a){if($CLJS.qe(a)&&$CLJS.C(a)instanceof $CLJS.N){var b=$CLJS.he(a);var c=$CLJS.oe(b);a=c?$CLJS.ie(a):a;var d=$CLJS.A(a);a=$CLJS.C(d);d=$CLJS.D(d);b=$CLJS.vV($CLJS.th.j(new $CLJS.R(null,2,5,$CLJS.S,[a,c?b:$CLJS.P],null),$CLJS.xg.g($CLJS.W2),d))}else b=a;return b});$CLJS.W2.o(null,$CLJS.lZ,function(a){return a});
$CLJS.W2.o(null,$CLJS.bZ,function(a){var b=$CLJS.W2.g($CLJS.ZO.g(a)),c=$CLJS.Vf($CLJS.Vm.h(function(g){var l=$CLJS.K(g,0,null);g=$CLJS.K(g,1,null);return $CLJS.E2($CLJS.W2.g(g),l)},$CLJS.aQ.g(a))),d=V2;V2=$CLJS.th.j($CLJS.P,$CLJS.No(function(g,l){$CLJS.K(l,0,null);l=$CLJS.K(l,1,null);l=$CLJS.Uf(l);l=$CLJS.M.h(l,$CLJS.EK);return new $CLJS.R(null,2,5,$CLJS.S,[g,l],null)}),b);try{var e=jqa(rqa(a),b,$CLJS.J([$CLJS.aQ,c])),f=$CLJS.Tb(function(g,l){return $CLJS.Fb($CLJS.M.h(g,l))?g:$CLJS.Wm.j(g,l,$CLJS.W2)},
e,$CLJS.Km.l(H2,$CLJS.ZO,$CLJS.J([$CLJS.aQ])));return $CLJS.m($CLJS.fO.g(f))?$CLJS.Wm.j(f,$CLJS.fO,qqa):f}finally{V2=d}});$CLJS.W2.o(null,$CLJS.hZ,function(a){return $CLJS.SZ.C(a,$CLJS.uQ,$CLJS.wu,function(b){return $CLJS.SZ.j(b,$CLJS.vN,$CLJS.W2)})});
$CLJS.W2.o(null,$CLJS.tY,function(a){a=$CLJS.Wm.j($CLJS.Wm.j(a,$CLJS.BY,$CLJS.W2),$CLJS.yY,$CLJS.W2);var b=$CLJS.m($CLJS.AH.g(a))?$CLJS.Wm.j(a,$CLJS.AH,function(c){return $CLJS.xe(c)?$CLJS.Vm.h($CLJS.W2,c):$CLJS.Ui.g(c)}):a;return $CLJS.Fb($CLJS.qI.g(a))?$CLJS.U.j(b,$CLJS.qI,"__join"):b});$CLJS.W2.o(null,$CLJS.FF,function(a){return $CLJS.Vm.h($CLJS.W2,a)});
$CLJS.W2.o(null,$CLJS.HF,function(a){return $CLJS.m($CLJS.al.g(a))?pqa($CLJS.Wm.j($CLJS.H_(a),$CLJS.yY,function(b){return $CLJS.Vm.h($CLJS.W2,b)})):$CLJS.wu(a,$CLJS.W2)});$CLJS.W2.o(null,$CLJS.PP,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);a=$CLJS.oe(b)?new $CLJS.R(null,2,5,$CLJS.S,[a,b],null):new $CLJS.R(null,2,5,$CLJS.S,[b,a],null);b=$CLJS.K(a,0,null);a=$CLJS.K(a,1,null);return $CLJS.vV(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,a,b],null))});
$CLJS.W2.o(null,$CLJS.vl,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);a=$CLJS.ZM(a,new $CLJS.k(null,3,[$CLJS.yI,$CLJS.LF,$CLJS.OO,$CLJS.Pl,$CLJS.sR,$CLJS.BK],null));var c=$CLJS.U.j;var d=$CLJS.qk.g(a);$CLJS.m(d)||(d=$CLJS.LF.g(a),d=$CLJS.m(d)?d:$CLJS.LK(b));a=c.call($CLJS.U,a,$CLJS.qk,d);return $CLJS.vV(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.vl,a,b],null))});
$CLJS.W2.o(null,$CLJS.dI,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null),c=$CLJS.K(a,2,null);a=$CLJS.Uj.g(c);b=new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.dI,$CLJS.Jm.h(c,$CLJS.Uj),$CLJS.Vm.h($CLJS.W2,b)],null);b=$CLJS.vV(b);return null!=a?$CLJS.mf.h(b,$CLJS.W2.g(a)):b});$CLJS.W2.o(null,$CLJS.IF,function(a){var b=$CLJS.K(a,0,null),c=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return $CLJS.vV(new $CLJS.R(null,3,5,$CLJS.S,[b,a,c],null))});
$CLJS.W2.o(null,$CLJS.ZO,function(a){var b=$CLJS.K(a,0,null),c=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return $CLJS.vV(new $CLJS.R(null,3,5,$CLJS.S,[b,a,J2(V2,c)],null))});$CLJS.W2.o(null,$CLJS.yN,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);b=$CLJS.W2.g(b);var c=$CLJS.A(b);b=$CLJS.C(c);var d=$CLJS.D(c);c=$CLJS.C(d);d=$CLJS.D(d);return $CLJS.th.h(new $CLJS.R(null,2,5,$CLJS.S,[b,$CLJS.mn.l($CLJS.J([c,a]))],null),d)});Aqa=$CLJS.ij.g($CLJS.P);Bqa=$CLJS.ij.g($CLJS.P);Cqa=$CLJS.ij.g($CLJS.P);
Dqa=$CLJS.ij.g($CLJS.P);Eqa=$CLJS.M.j(new $CLJS.k(null,1,[$CLJS.Vk,$CLJS.MG],null),$CLJS.Vk,$CLJS.rj.A?$CLJS.rj.A():$CLJS.rj.call(null));$CLJS.N2=new $CLJS.Aj($CLJS.$i.h("metabase.lib.convert","-\x3elegacy-MBQL"),$CLJS.LG,$CLJS.Uj,Eqa,Aqa,Bqa,Cqa,Dqa);
$CLJS.N2.o(null,$CLJS.Uj,function(a){if($CLJS.qe(a)&&$CLJS.C(a)instanceof $CLJS.N){a=$CLJS.A(a);var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);var d=$CLJS.D(c);if($CLJS.oe(a)){c=$CLJS.th.h;b=new $CLJS.R(null,1,5,$CLJS.S,[b],null);var e=$CLJS.wg.h;d=$CLJS.xg.h($CLJS.N2,d);a=M2(a);a=c.call($CLJS.th,b,e.call($CLJS.wg,d,$CLJS.m(a)?new $CLJS.R(null,1,5,$CLJS.S,[a],null):null))}else a=$CLJS.th.h(new $CLJS.R(null,1,5,$CLJS.S,[b],null),$CLJS.xg.h($CLJS.N2,$CLJS.pf(a,d)))}else a=$CLJS.oe(a)?$CLJS.wu(L2(a),$CLJS.N2):
a;return a});for(var X2=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[T2,S2],null)),Y2=null,Z2=0,$2=0;;)if($2<Z2){var Fqa=Y2.aa(null,$2);$CLJS.BU(Fqa,R2);$2+=1}else{var a3=$CLJS.A(X2);if(a3){var b3=a3;if($CLJS.re(b3)){var c3=$CLJS.$c(b3),Gqa=$CLJS.ad(b3),Hqa=c3,Iqa=$CLJS.E(c3);X2=Gqa;Y2=Hqa;Z2=Iqa}else{var Jqa=$CLJS.C(b3);$CLJS.BU(Jqa,R2);X2=$CLJS.D(b3);Y2=null;Z2=0}$2=0}else break}
for(var d3=$CLJS.A(new $CLJS.R(null,12,5,$CLJS.S,[$CLJS.cD,$CLJS.HI,$CLJS.kJ,$CLJS.SH,$CLJS.cm,$CLJS.BJ,$CLJS.vk,$CLJS.rI,$CLJS.dJ,$CLJS.GJ,$CLJS.zJ,$CLJS.VJ],null)),e3=null,f3=0,g3=0;;)if(g3<f3){var Kqa=e3.aa(null,g3);$CLJS.BU(Kqa,T2);g3+=1}else{var h3=$CLJS.A(d3);if(h3){var i3=h3;if($CLJS.re(i3)){var j3=$CLJS.$c(i3),Lqa=$CLJS.ad(i3),Mqa=j3,Nqa=$CLJS.E(j3);d3=Lqa;e3=Mqa;f3=Nqa}else{var Oqa=$CLJS.C(i3);$CLJS.BU(Oqa,T2);d3=$CLJS.D(i3);e3=null;f3=0}g3=0}else break}
for(var k3=$CLJS.A($CLJS.Ng([$CLJS.rm,$CLJS.hu,$CLJS.sm,$CLJS.XJ,$CLJS.dI,$CLJS.WI,$CLJS.yH,$CLJS.ZJ,$CLJS.fH,$CLJS.tI,$CLJS.pH,$CLJS.LI,$CLJS.aJ,$CLJS.rH,$CLJS.mI,$CLJS.wI,$CLJS.QD,$CLJS.LH,$CLJS.II,$CLJS.zH,$CLJS.iJ,$CLJS.KH,$CLJS.eH,$CLJS.gJ,$CLJS.DJ,$CLJS.mJ,$CLJS.JH,$CLJS.$J,$CLJS.jJ,$CLJS.RJ,$CLJS.tH,$CLJS.hH,$CLJS.cK,$CLJS.oW,$CLJS.UI,$CLJS.aD,$CLJS.IJ,$CLJS.NJ,$CLJS.fK,$CLJS.Eu,$CLJS.Su],!0)),l3=null,m3=0,n3=0;;)if(n3<m3){var Pqa=l3.aa(null,n3);$CLJS.BU(Pqa,S2);n3+=1}else{var o3=$CLJS.A(k3);
if(o3){var p3=o3;if($CLJS.re(p3)){var q3=$CLJS.$c(p3),Qqa=$CLJS.ad(p3),Rqa=q3,Sqa=$CLJS.E(q3);k3=Qqa;l3=Rqa;m3=Sqa}else{var Tqa=$CLJS.C(p3);$CLJS.BU(Tqa,S2);k3=$CLJS.D(p3);l3=null;m3=0}n3=0}else break}$CLJS.N2.o(null,R2,function(a){return O2(a)});$CLJS.N2.o(null,$CLJS.HF,function(a){return $CLJS.th.j($CLJS.P,$CLJS.Rm.h(K2(),$CLJS.xg.g(function(b){var c=$CLJS.K(b,0,null);b=$CLJS.K(b,1,null);return new $CLJS.R(null,2,5,$CLJS.S,[c,$CLJS.N2.g(b)],null)})),a)});
$CLJS.N2.o(null,$CLJS.ZO,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null),c=$CLJS.K(a,2,null);return $CLJS.oe(b)?(a=M2(b),c=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.ZO,J2(U2,c)],null),$CLJS.m(a)?$CLJS.mf.h(c,a):c):a});$CLJS.N2.o(null,$CLJS.FF,function(a){return $CLJS.Vm.h($CLJS.N2,a)});
$CLJS.N2.o(null,$CLJS.PP,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);a=null==b||$CLJS.oe(b)?new $CLJS.R(null,2,5,$CLJS.S,[b,a],null):new $CLJS.R(null,2,5,$CLJS.S,[a,b],null);b=$CLJS.K(a,0,null);a=$CLJS.K(a,1,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,$CLJS.N2.g(a),M2(b)],null)});
$CLJS.N2.o(null,$CLJS.vl,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);b=M2($CLJS.ZM(b,new $CLJS.k(null,3,[$CLJS.LF,$CLJS.yI,$CLJS.Pl,$CLJS.OO,$CLJS.BK,$CLJS.sR],null)));return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.vl,a,b],null)});
$CLJS.N2.o(null,$CLJS.tY,function(a){var b=L2(a);a=0==$CLJS.qI.g(a).lastIndexOf("__join",0)?$CLJS.Jm.h(b,$CLJS.qI):b;return $CLJS.mn.l($CLJS.J([$CLJS.wu($CLJS.Jm.l(a,$CLJS.yY,$CLJS.J([$CLJS.BY])),$CLJS.N2),Q2($CLJS.ri(a,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.BY],null)),$CLJS.BY,$CLJS.mR),P2(a)]))});
$CLJS.N2.o(null,$CLJS.bZ,function(a){var b=U2;U2=$CLJS.th.j($CLJS.P,$CLJS.No(function(c,d){$CLJS.K(d,0,null);d=$CLJS.K(d,1,null);d=$CLJS.Uf(d);d=$CLJS.M.h(d,$CLJS.EK);return new $CLJS.R(null,2,5,$CLJS.S,[d,c],null)}),$CLJS.ZO.g(a));try{return $CLJS.Tb(function(c,d){return $CLJS.SZ.j(c,d,$CLJS.N2)},Q2($CLJS.SZ.j($CLJS.SZ.j(uqa(L2(a)),$CLJS.ZO,function(c){return $CLJS.Vm.h(O2,c)}),$CLJS.aQ,function(c){return $CLJS.th.h($CLJS.P,function(){return function f(e){return new $CLJS.Af(null,function(){for(;;){var g=
$CLJS.A(e);if(g){if($CLJS.re(g)){var l=$CLJS.$c(g),n=$CLJS.E(l),q=$CLJS.Df(n);a:for(var u=0;;)if(u<n){var v=$CLJS.be(l,u),x=$CLJS.N2.g(v);v=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.D_(v),$CLJS.F.h($CLJS.vl,$CLJS.C(x))?$CLJS.Zd(x):x],null);q.add(v);u+=1}else{l=!0;break a}return l?$CLJS.If($CLJS.Kf(q),f($CLJS.ad(g))):$CLJS.If($CLJS.Kf(q),null)}q=$CLJS.C(g);l=$CLJS.N2.g(q);return $CLJS.pf(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.D_(q),$CLJS.F.h($CLJS.vl,$CLJS.C(l))?$CLJS.Zd(l):l],null),f($CLJS.zd(g)))}return null}},
null,null)}(c)}())}),$CLJS.mZ,$CLJS.TN),$CLJS.Km.l(H2,$CLJS.ZO,$CLJS.J([$CLJS.mZ,$CLJS.aQ])))}finally{U2=b}});$CLJS.N2.o(null,$CLJS.hZ,function(a){return $CLJS.wu(L2(a),$CLJS.N2)});
$CLJS.N2.o(null,$CLJS.lZ,function(a){var b=L2(a),c=$CLJS.YN.g(b),d=P2(b),e=$CLJS.F.h($CLJS.wl.g($CLJS.$d($CLJS.yY.g(a))),$CLJS.hZ)?$CLJS.fQ:$CLJS.GN;a=$CLJS.mn.l;b=$CLJS.wu($CLJS.Jm.l(b,$CLJS.yY,$CLJS.J([$CLJS.YN])),$CLJS.N2);d=$CLJS.Tf([$CLJS.al,e,e,d]);c=$CLJS.A(c)?$CLJS.U.j(d,$CLJS.YN,c):d;return a.call($CLJS.mn,$CLJS.J([b,c]))});