var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.common.js");require("./metabase.lib.equality.js");require("./metabase.lib.filter.operator.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.options.js");require("./metabase.lib.ref.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.filter.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.lib.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.malli.js");
'use strict';var S1,T1,V1,W1;$CLJS.Q1=function(a){if("number"===typeof a)return a;switch(a instanceof $CLJS.N?a.N:null){case "current":return 0;case "next":return 1;case "last":return-1;default:return 0}};
$CLJS.R1=function(a,b){a=$CLJS.Q1(a);b=$CLJS.m(b)?b:$CLJS.oz;return 0===a?$CLJS.F.h(b,$CLJS.oz)?$CLJS.bH("Today"):$CLJS.aH("This {0}",$CLJS.J([$CLJS.M1.g(b)])):$CLJS.F.h(a,1)?$CLJS.F.h(b,$CLJS.oz)?$CLJS.bH("Tomorrow"):$CLJS.aH("Next {0}",$CLJS.J([$CLJS.M1.g(b)])):$CLJS.F.h(a,-1)?$CLJS.F.h(b,$CLJS.oz)?$CLJS.bH("Yesterday"):$CLJS.aH("Previous {0}",$CLJS.J([$CLJS.M1.g(b)])):0>a?$CLJS.aH("Previous {0} {1}",$CLJS.J([Math.abs(a),$CLJS.M1.h(Math.abs(a),b)])):0<a?$CLJS.aH("Next {0} {1}",$CLJS.J([a,$CLJS.M1.h(a,
b)])):null};S1=new $CLJS.N("metabase.lib.filter","unary","metabase.lib.filter/unary",-336199667);T1=new $CLJS.N("metabase.lib.filter","varargs","metabase.lib.filter/varargs",1417033079);$CLJS.U1=new $CLJS.N(null,"operators","operators",-2064102509);V1=new $CLJS.N("metabase.lib.filter","compound","metabase.lib.filter/compound",1924103780);W1=new $CLJS.N("metabase.lib.filter","binary","metabase.lib.filter/binary",-1921360491);for(var X1=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Qj,$CLJS.Gk],null)),Y1=null,Z1=0,$1=0;;)if($1<Z1){var Ppa=Y1.aa(null,$1);$CLJS.BU(Ppa,V1);$1+=1}else{var a2=$CLJS.A(X1);if(a2){var b2=a2;if($CLJS.re(b2)){var c2=$CLJS.$c(b2),Qpa=$CLJS.ad(b2),Rpa=c2,Spa=$CLJS.E(c2);X1=Qpa;Y1=Rpa;Z1=Spa}else{var Tpa=$CLJS.C(b2);$CLJS.BU(Tpa,V1);X1=$CLJS.D(b2);Y1=null;Z1=0}$1=0}else break}
for(var d2=$CLJS.A(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.lm,$CLJS.JJ],null)),e2=null,f2=0,g2=0;;)if(g2<f2){var Upa=e2.aa(null,g2);$CLJS.BU(Upa,T1);g2+=1}else{var h2=$CLJS.A(d2);if(h2){var i2=h2;if($CLJS.re(i2)){var j2=$CLJS.$c(i2),Vpa=$CLJS.ad(i2),Wpa=j2,Xpa=$CLJS.E(j2);d2=Vpa;e2=Wpa;f2=Xpa}else{var Ypa=$CLJS.C(i2);$CLJS.BU(Ypa,T1);d2=$CLJS.D(i2);e2=null;f2=0}g2=0}else break}
for(var k2=$CLJS.A(new $CLJS.R(null,8,5,$CLJS.S,[$CLJS.mm,$CLJS.zm,$CLJS.pm,$CLJS.ym,$CLJS.zI,$CLJS.sJ,$CLJS.QI,$CLJS.AI],null)),l2=null,m2=0,n2=0;;)if(n2<m2){var Zpa=l2.aa(null,n2);$CLJS.BU(Zpa,W1);n2+=1}else{var o2=$CLJS.A(k2);if(o2){var p2=o2;if($CLJS.re(p2)){var q2=$CLJS.$c(p2),$pa=$CLJS.ad(p2),aqa=q2,bqa=$CLJS.E(q2);k2=$pa;l2=aqa;m2=bqa}else{var cqa=$CLJS.C(p2);$CLJS.BU(cqa,W1);k2=$CLJS.D(p2);l2=null;m2=0}n2=0}else break}
for(var r2=$CLJS.A(new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.DH,$CLJS.sI,$CLJS.QH,$CLJS.eI,$CLJS.Yk],null)),s2=null,t2=0,u2=0;;)if(u2<t2){var dqa=s2.aa(null,u2);$CLJS.BU(dqa,S1);u2+=1}else{var v2=$CLJS.A(r2);if(v2){var w2=v2;if($CLJS.re(w2)){var x2=$CLJS.$c(w2),eqa=$CLJS.ad(w2),fqa=x2,gqa=$CLJS.E(x2);r2=eqa;s2=fqa;t2=gqa}else{var hqa=$CLJS.C(w2);$CLJS.BU(hqa,S1);r2=$CLJS.D(w2);s2=null;t2=0}u2=0}else break}
$CLJS.Y0.o(null,$CLJS.mZ,function(a,b){var c=$CLJS.Vf($CLJS.mZ.g($CLJS.s0(a,b)));return $CLJS.m(c)?$CLJS.aH("Filtered by {0}",$CLJS.J([$CLJS.K1($CLJS.bH("and"),function(){return function f(e){return new $CLJS.Af(null,function(){for(;;){var g=$CLJS.A(e);if(g){if($CLJS.re(g)){var l=$CLJS.$c(g),n=$CLJS.E(l),q=$CLJS.Df(n);a:for(var u=0;;)if(u<n){var v=$CLJS.be(l,u);v=$CLJS.z0.C(a,b,v,$CLJS.A0);q.add(v);u+=1}else{l=!0;break a}return l?$CLJS.If($CLJS.Kf(q),f($CLJS.ad(g))):$CLJS.If($CLJS.Kf(q),null)}q=$CLJS.C(g);
return $CLJS.pf($CLJS.z0.C(a,b,q,$CLJS.A0),f($CLJS.zd(g)))}return null}},null,null)}(c)}())])):null});
$CLJS.V0.o(null,V1,function(a,b,c,d){c=$CLJS.A(c);var e=$CLJS.C(c);c=$CLJS.D(c);$CLJS.C(c);var f=$CLJS.D(c);return $CLJS.K1(function(){var g=e instanceof $CLJS.N?e.N:null;switch(g){case "and":return $CLJS.bH("and");case "or":return $CLJS.bH("or");default:throw Error(["No matching clause: ",$CLJS.p.g(g)].join(""));}}(),function(){return function n(l){return new $CLJS.Af(null,function(){for(;;){var q=$CLJS.A(l);if(q){if($CLJS.re(q)){var u=$CLJS.$c(q),v=$CLJS.E(u),x=$CLJS.Df(v);a:for(var z=0;;)if(z<
v){var B=$CLJS.be(u,z);B=$CLJS.z0.C(a,b,B,d);x.add(B);z+=1}else{u=!0;break a}return u?$CLJS.If($CLJS.Kf(x),n($CLJS.ad(q))):$CLJS.If($CLJS.Kf(x),null)}x=$CLJS.C(q);return $CLJS.pf($CLJS.z0.C(a,b,x,d),n($CLJS.zd(q)))}return null}},null,null)}(f)}())});
$CLJS.V0.o(null,T1,function(a,b,c,d){var e=$CLJS.A(c);c=$CLJS.C(e);e=$CLJS.D(e);$CLJS.C(e);var f=$CLJS.D(e);e=$CLJS.xg.h(function(g){return $CLJS.z0.C(a,b,g,d)},f);if($CLJS.F.h($CLJS.E(f),2))switch(f=$CLJS.K(e,0,null),e=$CLJS.K(e,1,null),c=c instanceof $CLJS.N?c.N:null,c){case "\x3d":return $CLJS.aH("{0} equals {1}",$CLJS.J([f,e]));case "!\x3d":return $CLJS.aH("{0} does not equal {1}",$CLJS.J([f,e]));default:throw Error(["No matching clause: ",$CLJS.p.g(c)].join(""));}else switch(f=$CLJS.C(e),e=$CLJS.K1($CLJS.bH("or"),
$CLJS.zd(e)),c=c instanceof $CLJS.N?c.N:null,c){case "\x3d":return $CLJS.aH("{0} equals any of {1}",$CLJS.J([f,e]));case "!\x3d":return $CLJS.aH("{0} does not equal any of {1}",$CLJS.J([f,e]));default:throw Error(["No matching clause: ",$CLJS.p.g(c)].join(""));}});
$CLJS.V0.o(null,W1,function(a,b,c,d){var e=$CLJS.K(c,0,null);$CLJS.K(c,1,null);var f=$CLJS.K(c,2,null);c=$CLJS.K(c,3,null);f=$CLJS.z0.C(a,b,f,d);a=$CLJS.z0.C(a,b,c,d);e=e instanceof $CLJS.N?e.N:null;switch(e){case "\x3c":return $CLJS.aH("{0} is less than {1}",$CLJS.J([f,a]));case "\x3c\x3d":return $CLJS.aH("{0} is less than or equal to {1}",$CLJS.J([f,a]));case "\x3e":return $CLJS.aH("{0} is greater than {1}",$CLJS.J([f,a]));case "\x3e\x3d":return $CLJS.aH("{0} is greater than or equal to {1}",$CLJS.J([f,
a]));case "starts-with":return $CLJS.aH("{0} starts with {1}",$CLJS.J([f,a]));case "ends-with":return $CLJS.aH("{0} ends with {1}",$CLJS.J([f,a]));case "contains":return $CLJS.aH("{0} contains {1}",$CLJS.J([f,a]));case "does-not-contain":return $CLJS.aH("{0} does not contain {1}",$CLJS.J([f,a]));default:throw Error(["No matching clause: ",$CLJS.p.g(e)].join(""));}});
$CLJS.V0.o(null,$CLJS.PH,function(a,b,c,d){$CLJS.K(c,0,null);$CLJS.K(c,1,null);var e=$CLJS.K(c,2,null),f=$CLJS.K(c,3,null);c=$CLJS.K(c,4,null);return $CLJS.aH("{0} is between {1} and {2}",$CLJS.J([$CLJS.z0.C(a,b,e,d),$CLJS.z0.C(a,b,f,d),$CLJS.z0.C(a,b,c,d)]))});
$CLJS.V0.o(null,$CLJS.ZH,function(a,b,c,d){$CLJS.K(c,0,null);var e=$CLJS.K(c,1,null),f=$CLJS.K(c,2,null),g=$CLJS.K(c,3,null),l=$CLJS.K(c,4,null),n=$CLJS.K(c,5,null),q=$CLJS.K(c,6,null);c=$CLJS.K(c,7,null);return $CLJS.z0.C(a,b,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.Qj,e,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.PH,e,f,q,l],null),new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.PH,e,g,n,c],null)],null),d)});
$CLJS.V0.o(null,S1,function(a,b,c,d){var e=$CLJS.K(c,0,null);$CLJS.K(c,1,null);c=$CLJS.K(c,2,null);a=$CLJS.z0.C(a,b,c,d);e=e instanceof $CLJS.N?e.N:null;switch(e){case "is-null":return $CLJS.aH("{0} is empty",$CLJS.J([a]));case "not-null":return $CLJS.aH("{0} is not empty",$CLJS.J([a]));case "is-empty":return $CLJS.aH("{0} is empty",$CLJS.J([a]));case "not-empty":return $CLJS.aH("{0} is not empty",$CLJS.J([a]));case "not":return $CLJS.aH("not {0}",$CLJS.J([a]));default:throw Error(["No matching clause: ",
$CLJS.p.g(e)].join(""));}});$CLJS.V0.o(null,$CLJS.wJ,function(a,b,c,d){$CLJS.K(c,0,null);$CLJS.K(c,1,null);var e=$CLJS.K(c,2,null),f=$CLJS.K(c,3,null);c=$CLJS.K(c,4,null);return $CLJS.aH("{0} is within {1}",$CLJS.J([$CLJS.z0.C(a,b,e,d),$CLJS.R1(f,c).toLowerCase()]))});