var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./metabase.mbql.predicates.js");require("./metabase.mbql.schema.js");require("./metabase.mbql.schema.helpers.js");require("./metabase.mbql.util.match.js");require("./metabase.shared.util.i18n.js");require("./schema.core.js");
'use strict';var sZ,AZ,BZ,CZ,DZ,IZ,Zna,$na,aoa,KZ,boa,coa,doa,eoa,foa,goa,hoa,QZ,yZ,TZ,UZ,ioa,WZ,XZ,joa,koa,loa,YZ,moa,ZZ,noa,$Z,ooa,poa,a_,b_,c_,qoa,roa,d_,soa,toa,uoa,voa,e_,woa,f_,g_,h_,i_,j_;$CLJS.rZ=function(a){return a instanceof Error?a.message:null};sZ=function(a,b){a.schema$utils$schema=b};$CLJS.tZ=function(a,b){return $CLJS.Vc($CLJS.Tb(function(c,d){return $CLJS.m(a.g?a.g(d):a.call(null,d))?$CLJS.Uc(c,d):c},$CLJS.Tc($CLJS.Rg),b))};
$CLJS.uZ=function(a,b){return $CLJS.Qe(function(c,d){c=a.g?a.g(c):a.call(null,c);d=a.g?a.g(d):a.call(null,d);var e=$CLJS.Oe($CLJS.Me);return e.h?e.h(c,d):e.call(null,c,d)},b)};
$CLJS.vZ=function(a,b,c){if($CLJS.kf(c)){var d=$CLJS.Q.h($CLJS.Y,$CLJS.xg.h(a,c));return b.g?b.g(d):b.call(null,d)}return $CLJS.Og(c)?(d=new $CLJS.Ke(function(){var e=$CLJS.tc(c);return a.g?a.g(e):a.call(null,e)}(),function(){var e=$CLJS.uc(c);return a.g?a.g(e):a.call(null,e)}()),b.g?b.g(d):b.call(null,d)):$CLJS.we(c)?(d=$CLJS.Ii($CLJS.xg.h(a,c)),b.g?b.g(d):b.call(null,d)):$CLJS.pe(c)?(d=$CLJS.Tb(function(e,f){return $CLJS.mf.h(e,a.g?a.g(f):a.call(null,f))},c,c),b.g?b.g(d):b.call(null,d)):$CLJS.ke(c)?
(d=$CLJS.th.h($CLJS.ae(c),$CLJS.xg.h(a,c)),b.g?b.g(d):b.call(null,d)):b.g?b.g(c):b.call(null,c)};$CLJS.xZ=function(a){function b(c){var d=$CLJS.K(c,0,null);c=$CLJS.K(c,1,null);return"string"===typeof d?new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Ui.g(d),c],null):new $CLJS.R(null,2,5,$CLJS.S,[d,c],null)}return wZ(function(c){return $CLJS.oe(c)?$CLJS.th.h($CLJS.P,$CLJS.xg.h(b,c)):c},a)};
$CLJS.zZ=function(a,b,c){a=$CLJS.zu(a,/''/,"'");var d=$CLJS.cz(a,yZ);d=$CLJS.F.h($CLJS.E(d),1)?new $CLJS.R(null,2,5,$CLJS.S,[a,""],null):d;a=$CLJS.Ki(/.*\{0\}.*/,a);return $CLJS.az.ngettext($CLJS.az.msgid($CLJS.pn(d),$CLJS.m(a)?c:""),$CLJS.zu($CLJS.zu(b,/''/,"'"),yZ,$CLJS.p.g(c)),c)};
AZ=function(a){var b=$CLJS.Hi(function(c){return c instanceof $CLJS.qM},a);a=$CLJS.K(b,0,null);b=$CLJS.K(b,1,null);return $CLJS.wg.h($CLJS.xg.h(function(c){return $CLJS.XL(c.X)},a),$CLJS.A(b)?new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Nk,$CLJS.Vm.h($CLJS.XL,b)],null):null)};BZ=function(a,b,c,d,e){this.Dc=a;this.oc=b;this.F=c;this.m=d;this.G=e;this.D=2230716170;this.K=139264};CZ=function(a,b){return new BZ(a,b,null,null,null)};
DZ=function(a){return $CLJS.A(a)?$CLJS.$d(a)instanceof $CLJS.qM?$CLJS.E(a):Number.MAX_VALUE:0};$CLJS.EZ=function(a){if($CLJS.de(a))return a;throw $CLJS.Ej("Invalid pattern: don't know how to handle symbol.",new $CLJS.k(null,1,[$CLJS.sk,a],null));};
$CLJS.FZ=function(a,b,c){return $CLJS.oe(c)?$CLJS.th.h(c,function(){return function f(e){return new $CLJS.Af(null,function(){for(;;){var g=$CLJS.A(e);if(g){if($CLJS.re(g)){var l=$CLJS.$c(g),n=$CLJS.E(l),q=$CLJS.Df(n);return function(){for(var z=0;;)if(z<n){var B=$CLJS.be(l,z),H=$CLJS.K(B,0,null),I=$CLJS.K(B,1,null);B=q;var T=$CLJS.S,W=H;H=$CLJS.mf.h(b,H);H=a.h?a.h(H,I):a.call(null,H,I);B.add(new $CLJS.R(null,2,5,T,[W,H],null));z+=1}else return!0}()?$CLJS.If($CLJS.Kf(q),f($CLJS.ad(g))):$CLJS.If($CLJS.Kf(q),
null)}var u=$CLJS.C(g),v=$CLJS.K(u,0,null),x=$CLJS.K(u,1,null);return $CLJS.pf(new $CLJS.R(null,2,5,$CLJS.S,[v,function(){var z=$CLJS.mf.h(b,v),B=x;return a.h?a.h(z,B):a.call(null,z,B)}()],null),f($CLJS.zd(g)))}return null}},null,null)}(c)}()):$CLJS.ne(c)?$CLJS.Vm.h($CLJS.fg(a,$CLJS.C(c)instanceof $CLJS.N?$CLJS.mf.h(b,$CLJS.C(c)):b),c):c};$CLJS.GZ=function(a){var b=(b=a instanceof $CLJS.N)?$CLJS.sf(a):b;return $CLJS.m(b)?[$CLJS.sf(a),"/",$CLJS.Ai(a)].join(""):$CLJS.Ai(a)};
$CLJS.HZ=function(a,b){var c=$CLJS.ne(b)&&!$CLJS.Og(b)&&$CLJS.C(b)instanceof $CLJS.N;return c?$CLJS.ke(a)?(b=$CLJS.C(b),a=$CLJS.yi(a),a.g?a.g(b):a.call(null,b)):$CLJS.F.h(a,$CLJS.C(b)):c};
IZ=function(a,b){return $CLJS.yg(function(c){var d=$CLJS.Ag;a:try{if($CLJS.qe(c)&&1<=$CLJS.E(c))try{var e=$CLJS.an.j(c,0,1);if($CLJS.qe(e)&&1===$CLJS.E(e))try{var f=$CLJS.G(e,0);if($CLJS.m($CLJS.fg($CLJS.F,a)(f))){var g=$CLJS.an.h(c,1);var l=new $CLJS.R(null,1,5,$CLJS.S,[g],null)}else throw $CLJS.Z;}catch(q){if(q instanceof Error){var n=q;if(n===$CLJS.Z)throw $CLJS.Z;throw n;}throw q;}else throw $CLJS.Z;}catch(q){if(q instanceof Error){n=q;if(n===$CLJS.Z)throw $CLJS.Z;throw n;}throw q;}else throw $CLJS.Z;
}catch(q){if(q instanceof Error){n=q;if(n===$CLJS.Z){l=new $CLJS.R(null,1,5,$CLJS.S,[new $CLJS.R(null,1,5,$CLJS.S,[c],null)],null);break a}throw n;}throw q;}return $CLJS.C($CLJS.A(d($CLJS.Gb,l)))},$CLJS.J([b]))};
$CLJS.JZ=function(a){return function e(c,d){try{if($CLJS.m(function(){var iu=$CLJS.EZ($CLJS.we);return iu.g?iu.g(d):iu.call(null,d)}()))return e(c,$CLJS.Sg(d));throw $CLJS.Z;}catch(iu){if(iu instanceof Error){var f=iu;if(f===$CLJS.Z)try{if(null===d)return null;throw $CLJS.Z;}catch(yQ){if(yQ instanceof Error)if(f=yQ,f===$CLJS.Z)try{if($CLJS.qe(d)&&0<=$CLJS.E(d))try{var g=$CLJS.an.j(d,0,0);if($CLJS.qe(g)&&0===$CLJS.E(g))try{var l=$CLJS.an.h(d,0);if($CLJS.m($CLJS.fg($CLJS.$f,$CLJS.Bb)(l)))return null;
throw $CLJS.Z;}catch(om){if(om instanceof Error){var n=om;if(n===$CLJS.Z)throw $CLJS.Z;throw n;}throw om;}else throw $CLJS.Z;}catch(om){if(om instanceof Error){n=om;if(n===$CLJS.Z)throw $CLJS.Z;throw n;}throw om;}else throw $CLJS.Z;}catch(om){if(om instanceof Error)if(n=om,n===$CLJS.Z)try{if($CLJS.qe(d)&&0===$CLJS.E(d))return null;throw $CLJS.Z;}catch(zQ){if(zQ instanceof Error)if(g=zQ,g===$CLJS.Z)try{if($CLJS.qe(d)&&1===$CLJS.E(d))try{var q=$CLJS.G(d,0);if($CLJS.O(q,$CLJS.Qj))return null;throw $CLJS.Z;
}catch(ju){if(ju instanceof Error)if(g=ju,g===$CLJS.Z)try{q=$CLJS.G(d,0);if($CLJS.O(q,$CLJS.Gk))return null;throw $CLJS.Z;}catch(Ff){if(Ff instanceof Error){var u=Ff;if(u===$CLJS.Z)throw $CLJS.Z;throw u;}throw Ff;}else throw g;else throw ju;}else throw $CLJS.Z;}catch(ju){if(ju instanceof Error)if(g=ju,g===$CLJS.Z)try{if($CLJS.qe(d)&&1<=$CLJS.E(d))try{var v=$CLJS.an.j(d,0,1);if($CLJS.qe(v)&&1===$CLJS.E(v))try{var x=$CLJS.G(v,0);if($CLJS.m(function(){var Ff=new $CLJS.ti(null,new $CLJS.k(null,2,[$CLJS.Gk,
null,$CLJS.Qj,null],null),null);return Ff.g?Ff.g(x):Ff.call(null,x)}()))try{var z=$CLJS.an.h(d,1);if($CLJS.m($CLJS.fg($CLJS.ag,$CLJS.Bb)(z))){var B=$CLJS.an.h(d,1),H=$CLJS.G(v,0);return e(c,$CLJS.Q.j($CLJS.$m,H,$CLJS.tZ($CLJS.Gb,B)))}throw $CLJS.Z;}catch(Ff){if(Ff instanceof Error){u=Ff;if(u===$CLJS.Z)throw $CLJS.Z;throw u;}throw Ff;}else throw $CLJS.Z;}catch(Ff){if(Ff instanceof Error){u=Ff;if(u===$CLJS.Z)throw $CLJS.Z;throw u;}throw Ff;}else throw $CLJS.Z;}catch(Ff){if(Ff instanceof Error){u=Ff;
if(u===$CLJS.Z)throw $CLJS.Z;throw u;}throw Ff;}else throw $CLJS.Z;}catch(Ff){if(Ff instanceof Error)if(u=Ff,u===$CLJS.Z)try{if($CLJS.qe(d)&&2===$CLJS.E(d))try{var I=$CLJS.G(d,0);if($CLJS.O(I,$CLJS.Yk))try{var T=$CLJS.G(d,1);if($CLJS.qe(T)&&1<=$CLJS.E(T))try{var W=$CLJS.an.j(T,0,1);if($CLJS.qe(W)&&1===$CLJS.E(W))try{var ba=$CLJS.G(W,0);if($CLJS.O(ba,$CLJS.Qj))return B=$CLJS.an.h(T,1),e(c,$CLJS.Q.j($CLJS.$m,$CLJS.Gk,$CLJS.xg.h(function(ng){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Yk,ng],null)},B)));
throw $CLJS.Z;}catch(ng){if(ng instanceof Error){var ha=ng;if(ha===$CLJS.Z)try{ba=$CLJS.G(W,0);if($CLJS.O(ba,$CLJS.Gk))return B=$CLJS.an.h(T,1),e(c,$CLJS.Q.j($CLJS.$m,$CLJS.Qj,$CLJS.xg.h(function(ff){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Yk,ff],null)},B)));throw $CLJS.Z;}catch(ff){if(ff instanceof Error){var pa=ff;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw ff;}else throw ha;}else throw ng;}else throw $CLJS.Z;}catch(ng){if(ng instanceof Error){ha=ng;if(ha===$CLJS.Z)throw $CLJS.Z;throw ha;}throw ng;
}else throw $CLJS.Z;}catch(ng){if(ng instanceof Error){ha=ng;if(ha===$CLJS.Z)throw $CLJS.Z;throw ha;}throw ng;}else throw $CLJS.Z;}catch(ng){if(ng instanceof Error)if(ha=ng,ha===$CLJS.Z)try{I=$CLJS.G(d,0);if($CLJS.O(I,$CLJS.Qj)){var Ga=$CLJS.G(d,1);return e(c,Ga)}throw $CLJS.Z;}catch(ff){if(ff instanceof Error)if(pa=ff,pa===$CLJS.Z)try{I=$CLJS.G(d,0);if($CLJS.O(I,$CLJS.Gk))return Ga=$CLJS.G(d,1),e(c,Ga);throw $CLJS.Z;}catch(Je){if(Je instanceof Error){var eb=Je;if(eb===$CLJS.Z)throw $CLJS.Z;throw eb;
}throw Je;}else throw pa;else throw ff;}else throw ha;else throw ng;}else throw $CLJS.Z;}catch(ng){if(ng instanceof Error)if(ha=ng,ha===$CLJS.Z)try{if($CLJS.qe(d)&&1<=$CLJS.E(d))try{var Hb=$CLJS.an.j(d,0,1);if($CLJS.qe(Hb)&&1===$CLJS.E(Hb))try{var Rb=$CLJS.G(Hb,0);if($CLJS.O(Rb,$CLJS.Qj))try{var Zb=$CLJS.an.h(d,1);if($CLJS.m($CLJS.fg($CLJS.ag,$CLJS.fg($CLJS.HZ,$CLJS.Qj))(Zb)))return B=$CLJS.an.h(d,1),e(c,$CLJS.Q.j($CLJS.$m,$CLJS.Qj,IZ($CLJS.Qj,B)));throw $CLJS.Z;}catch(ff){if(ff instanceof Error){pa=
ff;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw ff;}else throw $CLJS.Z;}catch(ff){if(ff instanceof Error)if(pa=ff,pa===$CLJS.Z)try{if(Rb=$CLJS.G(Hb,0),$CLJS.O(Rb,$CLJS.Gk))try{Zb=$CLJS.an.h(d,1);if($CLJS.m($CLJS.fg($CLJS.ag,$CLJS.fg($CLJS.HZ,$CLJS.Gk))(Zb)))return B=$CLJS.an.h(d,1),e(c,$CLJS.Q.j($CLJS.$m,$CLJS.Gk,IZ($CLJS.Gk,B)));throw $CLJS.Z;}catch(Je){if(Je instanceof Error){eb=Je;if(eb===$CLJS.Z)throw $CLJS.Z;throw eb;}throw Je;}else throw $CLJS.Z;}catch(Je){if(Je instanceof Error)if(eb=Je,eb===
$CLJS.Z)try{if(Rb=$CLJS.G(Hb,0),$CLJS.m(function(){var Gf=new $CLJS.ti(null,new $CLJS.k(null,2,[$CLJS.Gk,null,$CLJS.Qj,null],null),null);return Gf.g?Gf.g(Rb):Gf.call(null,Rb)}()))try{Zb=$CLJS.an.h(d,1);if($CLJS.Fb($CLJS.Q.h($CLJS.Cu,Zb))){B=$CLJS.an.h(d,1);var qc=$CLJS.G(Hb,0);return e(c,$CLJS.Q.j($CLJS.$m,qc,$CLJS.on.g(B)))}throw $CLJS.Z;}catch(Gf){if(Gf instanceof Error){var Eb=Gf;if(Eb===$CLJS.Z)throw $CLJS.Z;throw Eb;}throw Gf;}else throw $CLJS.Z;}catch(Gf){if(Gf instanceof Error){Eb=Gf;if(Eb===
$CLJS.Z)throw $CLJS.Z;throw Eb;}throw Gf;}else throw eb;else throw Je;}else throw pa;else throw ff;}else throw $CLJS.Z;}catch(ff){if(ff instanceof Error){pa=ff;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw ff;}else throw $CLJS.Z;}catch(ff){if(ff instanceof Error)if(pa=ff,pa===$CLJS.Z)try{if($CLJS.qe(d)&&2===$CLJS.E(d))try{var Sb=$CLJS.G(d,0);if($CLJS.O(Sb,$CLJS.Yk))try{var Hd=$CLJS.G(d,1);if($CLJS.qe(Hd)&&2===$CLJS.E(Hd))try{var Ct=$CLJS.G(Hd,0);if($CLJS.O(Ct,$CLJS.Yk))return Ga=$CLJS.G(Hd,1),e(c,
Ga);throw $CLJS.Z;}catch(Je){if(Je instanceof Error){eb=Je;if(eb===$CLJS.Z)throw $CLJS.Z;throw eb;}throw Je;}else throw $CLJS.Z;}catch(Je){if(Je instanceof Error){eb=Je;if(eb===$CLJS.Z)throw $CLJS.Z;throw eb;}throw Je;}else throw $CLJS.Z;}catch(Je){if(Je instanceof Error){eb=Je;if(eb===$CLJS.Z)throw $CLJS.Z;throw eb;}throw Je;}else throw $CLJS.Z;}catch(Je){if(Je instanceof Error)if(eb=Je,eb===$CLJS.Z)try{if($CLJS.qe(d)&&1<=$CLJS.E(d))try{var uh=$CLJS.an.j(d,0,1);if($CLJS.qe(uh)&&1===$CLJS.E(uh))try{var mg=
$CLJS.G(uh,0);if($CLJS.O(mg,$CLJS.Ju))return a;throw $CLJS.Z;}catch(Gf){if(Gf instanceof Error){Eb=Gf;if(Eb===$CLJS.Z)throw $CLJS.Z;throw Eb;}throw Gf;}else throw $CLJS.Z;}catch(Gf){if(Gf instanceof Error){Eb=Gf;if(Eb===$CLJS.Z)throw $CLJS.Z;throw Eb;}throw Gf;}else throw $CLJS.Z;}catch(Gf){if(Gf instanceof Error){Eb=Gf;if(Eb===$CLJS.Z)return $CLJS.FZ(e,c,d);throw Eb;}throw Gf;}else throw eb;else throw Je;}else throw pa;else throw ff;}else throw ha;else throw ng;}else throw u;else throw Ff;}else throw g;
else throw ju;}else throw g;else throw zQ;}else throw n;else throw om;}else throw f;else throw yQ;}else throw f;}else throw iu;}}($CLJS.Rg,a)};
Zna=function(a){return function e(c,d){try{if($CLJS.qe(d)&&7===$CLJS.E(d))try{var f=$CLJS.G(d,0);if($CLJS.O(f,$CLJS.ZH)){var g=$CLJS.G(d,1),l=$CLJS.G(d,2),n=$CLJS.G(d,3),q=$CLJS.G(d,4),u=$CLJS.G(d,5),v=$CLJS.G(d,6);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Qj,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,g,u,n],null),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,l,q,v],null)],null)}throw $CLJS.Z;}catch(x){if(x instanceof Error){f=x;if(f===$CLJS.Z)throw $CLJS.Z;throw f;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof
Error){f=x;if(f===$CLJS.Z)return $CLJS.FZ(e,c,d);throw f;}throw x;}}($CLJS.Rg,a)};
$na=function(a){return function e(c,d){try{if($CLJS.qe(d)&&2===$CLJS.E(d))try{var f=$CLJS.G(d,0);if($CLJS.O(f,$CLJS.DH)){var g=$CLJS.G(d,1);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.lm,g,null],null)}throw $CLJS.Z;}catch(n){if(n instanceof Error){var l=n;if(l===$CLJS.Z)try{f=$CLJS.G(d,0);if($CLJS.O(f,$CLJS.sI))return g=$CLJS.G(d,1),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.JJ,g,null],null);throw $CLJS.Z;}catch(q){if(q instanceof Error){f=q;if(f===$CLJS.Z)throw $CLJS.Z;throw f;}throw q;}else throw l;}else throw n;
}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)return $CLJS.FZ(e,c,d);throw l;}throw n;}}($CLJS.Rg,a)};
aoa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&2===$CLJS.E(d))try{var f=$CLJS.G(d,0);if($CLJS.O(f,$CLJS.QH)){var g=$CLJS.G(d,1);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Gk,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.lm,g,null],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.lm,g,""],null)],null)}throw $CLJS.Z;}catch(n){if(n instanceof Error){var l=n;if(l===$CLJS.Z)try{f=$CLJS.G(d,0);if($CLJS.O(f,$CLJS.eI))return g=$CLJS.G(d,1),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Qj,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.JJ,
g,null],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.JJ,g,""],null)],null);throw $CLJS.Z;}catch(q){if(q instanceof Error){f=q;if(f===$CLJS.Z)throw $CLJS.Z;throw f;}throw q;}else throw l;}else throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)return $CLJS.FZ(e,c,d);throw l;}throw n;}}($CLJS.Rg,a)};
KZ=function(a,b){return function f(d,e){try{if($CLJS.qe(e)&&3===$CLJS.E(e))try{var g=$CLJS.G(e,0);if($CLJS.O(g,$CLJS.PP)){var l=$CLJS.G(e,1),n=$CLJS.G(e,2);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,l,$CLJS.U.j(n,$CLJS.bQ,b)],null)}throw $CLJS.Z;}catch(v){if(v instanceof Error){g=v;if(g===$CLJS.Z)throw $CLJS.Z;throw g;}throw v;}else throw $CLJS.Z;}catch(v){if(v instanceof Error)if(g=v,g===$CLJS.Z)try{if($CLJS.qe(e)&&2===$CLJS.E(e))try{var q=$CLJS.G(e,0);if($CLJS.O(q,$CLJS.IF)){var u=$CLJS.G(e,
1);return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.IF,u],null)}throw $CLJS.Z;}catch(x){if(x instanceof Error){q=x;if(q===$CLJS.Z)throw $CLJS.Z;throw q;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){q=x;if(q===$CLJS.Z)return $CLJS.FZ(f,d,e);throw q;}throw x;}else throw g;else throw v;}}($CLJS.Rg,a)};
boa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&4===$CLJS.E(d))try{var f=$CLJS.G(d,0);if($CLJS.O(f,$CLJS.wJ)){var g=$CLJS.G(d,1),l=$CLJS.G(d,2),n=$CLJS.G(d,3);return e(c,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.wJ,g,l,n,null],null))}throw $CLJS.Z;}catch(T){if(T instanceof Error){f=T;if(f===$CLJS.Z)throw $CLJS.Z;throw f;}throw T;}else throw $CLJS.Z;}catch(T){if(T instanceof Error)if(f=T,f===$CLJS.Z)try{if($CLJS.qe(d)&&5===$CLJS.E(d))try{var q=$CLJS.G(d,0);if($CLJS.O(q,$CLJS.wJ))try{var u=$CLJS.G(d,
2);if($CLJS.O(u,$CLJS.eB)){g=$CLJS.G(d,1);n=$CLJS.G(d,3);var v=$CLJS.G(d,4);return e(c,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.wJ,g,0,n,v],null))}throw $CLJS.Z;}catch(W){if(W instanceof Error){var x=W;if(x===$CLJS.Z)try{u=$CLJS.G(d,2);if($CLJS.O(u,$CLJS.gD))return g=$CLJS.G(d,1),n=$CLJS.G(d,3),v=$CLJS.G(d,4),e(c,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.wJ,g,-1,n,v],null));throw $CLJS.Z;}catch(ba){if(ba instanceof Error)if(q=ba,q===$CLJS.Z)try{u=$CLJS.G(d,2);if($CLJS.O(u,$CLJS.WH))return g=$CLJS.G(d,1),n=$CLJS.G(d,
3),v=$CLJS.G(d,4),e(c,new $CLJS.R(null,5,5,$CLJS.S,[$CLJS.wJ,g,1,n,v],null));throw $CLJS.Z;}catch(ha){if(ha instanceof Error)if(v=ha,v===$CLJS.Z)try{if(u=$CLJS.G(d,2),$CLJS.m(function(){var pa=new $CLJS.ti(null,new $CLJS.k(null,1,[-1,null],null),null);return pa.g?pa.g(u):pa.call(null,u)}()))try{var z=$CLJS.G(d,4);if($CLJS.m($CLJS.EJ.g(z)))return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,3),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null),new $CLJS.R(null,
3,5,$CLJS.S,[$CLJS.wI,0,n],null)],null);throw $CLJS.Z;}catch(pa){if(pa instanceof Error){var B=pa;if(B===$CLJS.Z)throw $CLJS.Z;throw B;}throw pa;}else throw $CLJS.Z;}catch(pa){if(pa instanceof Error)if(B=pa,B===$CLJS.Z)try{if(u=$CLJS.G(d,2),$CLJS.m(function(){var Ga=new $CLJS.ti(null,new $CLJS.k(null,1,[1,null],null),null);return Ga.g?Ga.g(u):Ga.call(null,u)}()))try{z=$CLJS.G(d,4);if($CLJS.m($CLJS.EJ.g(z)))return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,3),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,
KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,0,n],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null)],null);throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){var H=Ga;if(H===$CLJS.Z)throw $CLJS.Z;throw H;}throw Ga;}else throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error)if(H=Ga,H===$CLJS.Z)try{u=$CLJS.G(d,2);if($CLJS.m(function(){var eb=new $CLJS.ti(null,new $CLJS.k(null,3,[0,null,1,null,-1,null],null),null);return eb.g?eb.g(u):eb.call(null,u)}()))return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,
3),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.lm,KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null)],null);throw $CLJS.Z;}catch(eb){if(eb instanceof Error)if(B=eb,B===$CLJS.Z)try{if(u=$CLJS.G(d,2),0>u)try{z=$CLJS.G(d,4);if($CLJS.m($CLJS.EJ.g(z)))return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,3),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,0,n],null)],null);throw $CLJS.Z;}catch(Hb){if(Hb instanceof Error){var I=
Hb;if(I===$CLJS.Z)return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,3),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,-1,n],null)],null);throw I;}throw Hb;}else throw $CLJS.Z;}catch(Hb){if(Hb instanceof Error)if(I=Hb,I===$CLJS.Z)try{z=$CLJS.G(d,4);if($CLJS.m($CLJS.EJ.g(z)))return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,3),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,0,
n],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null)],null);throw $CLJS.Z;}catch(Rb){if(Rb instanceof Error){z=Rb;if(z===$CLJS.Z)return l=$CLJS.G(d,2),g=$CLJS.G(d,1),n=$CLJS.G(d,3),new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.PH,KZ(g,n),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,1,n],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,l,n],null)],null);throw z;}throw Rb;}else throw I;else throw Hb;}else throw B;else throw eb;}else throw H;else throw Ga;}else throw B;else throw pa;}else throw v;else throw ha;}else throw q;
else throw ba;}else throw x;}else throw W;}else throw $CLJS.Z;}catch(W){if(W instanceof Error){x=W;if(x===$CLJS.Z)throw $CLJS.Z;throw x;}throw W;}else throw $CLJS.Z;}catch(W){if(W instanceof Error){x=W;if(x===$CLJS.Z)return $CLJS.FZ(e,c,d);throw x;}throw W;}else throw f;else throw T;}}($CLJS.Rg,a)};
coa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&1<=$CLJS.E(d))try{var f=$CLJS.an.j(d,0,1);if($CLJS.qe(f)&&1===$CLJS.E(f))try{var g=$CLJS.G(f,0);if($CLJS.O(g,$CLJS.AI)){var l=$CLJS.an.h(d,1);return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Yk,$CLJS.th.h(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.QI],null),l)],null)}throw $CLJS.Z;}catch(q){if(q instanceof Error){var n=q;if(n===$CLJS.Z)throw $CLJS.Z;throw n;}throw q;}else throw $CLJS.Z;}catch(q){if(q instanceof Error){n=q;if(n===$CLJS.Z)throw $CLJS.Z;
throw n;}throw q;}else throw $CLJS.Z;}catch(q){if(q instanceof Error){n=q;if(n===$CLJS.Z)return $CLJS.FZ(e,c,d);throw n;}throw q;}}($CLJS.Rg,a)};
doa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&4<=$CLJS.E(d))try{var f=$CLJS.an.j(d,0,4);if($CLJS.qe(f)&&4===$CLJS.E(f))try{var g=$CLJS.G(f,0);if($CLJS.O(g,$CLJS.lm)){var l=$CLJS.G(f,1),n=$CLJS.G(f,2),q=$CLJS.G(f,3),u=$CLJS.an.h(d,4);return $CLJS.Q.j($CLJS.$m,$CLJS.Gk,function(){return function B(z){return new $CLJS.Af(null,function(){for(;;){var H=$CLJS.A(z);if(H){if($CLJS.re(H)){var I=$CLJS.$c(H),T=$CLJS.E(I),W=$CLJS.Df(T);a:for(var ba=0;;)if(ba<T){var ha=$CLJS.be(I,ba);W.add(new $CLJS.R(null,
3,5,$CLJS.S,[$CLJS.lm,l,ha],null));ba+=1}else{I=!0;break a}return I?$CLJS.If($CLJS.Kf(W),B($CLJS.ad(H))):$CLJS.If($CLJS.Kf(W),null)}W=$CLJS.C(H);return $CLJS.pf(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.lm,l,W],null),B($CLJS.zd(H)))}return null}},null,null)}($CLJS.wg.h(new $CLJS.R(null,2,5,$CLJS.S,[n,q],null),u))}())}throw $CLJS.Z;}catch(x){if(x instanceof Error){var v=x;if(v===$CLJS.Z)try{g=$CLJS.G(f,0);if($CLJS.O(g,$CLJS.JJ))return l=$CLJS.G(f,1),n=$CLJS.G(f,2),q=$CLJS.G(f,3),u=$CLJS.an.h(d,4),$CLJS.Q.j($CLJS.$m,
$CLJS.Qj,function(){return function H(B){return new $CLJS.Af(null,function(){for(;;){var I=$CLJS.A(B);if(I){if($CLJS.re(I)){var T=$CLJS.$c(I),W=$CLJS.E(T),ba=$CLJS.Df(W);a:for(var ha=0;;)if(ha<W){var pa=$CLJS.be(T,ha);ba.add(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.JJ,l,pa],null));ha+=1}else{T=!0;break a}return T?$CLJS.If($CLJS.Kf(ba),H($CLJS.ad(I))):$CLJS.If($CLJS.Kf(ba),null)}ba=$CLJS.C(I);return $CLJS.pf(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.JJ,l,ba],null),H($CLJS.zd(I)))}return null}},null,null)}($CLJS.wg.h(new $CLJS.R(null,
2,5,$CLJS.S,[n,q],null),u))}());throw $CLJS.Z;}catch(z){if(z instanceof Error){f=z;if(f===$CLJS.Z)throw $CLJS.Z;throw f;}throw z;}else throw v;}else throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)return $CLJS.FZ(e,c,d);throw v;}throw x;}}($CLJS.Rg,a)};
eoa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&2<=$CLJS.E(d))try{var f=$CLJS.an.j(d,0,2);if($CLJS.qe(f)&&2===$CLJS.E(f))try{var g=$CLJS.an.h(d,2);if($CLJS.m($CLJS.fg($CLJS.ag,$CLJS.fg($CLJS.F,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.wI,$CLJS.eB],null)))(g))){var l=$CLJS.an.h(d,2),n=$CLJS.G(f,0),q=$CLJS.G(f,1),u=function(){var x=$CLJS.C($CLJS.A($CLJS.Ag($CLJS.Gb,function I(B,H){try{if($CLJS.qe(H)&&3===$CLJS.E(H))try{var T=$CLJS.G(H,0);if($CLJS.O(T,$CLJS.PP))try{var W=$CLJS.G(H,2);if(null!=W?
W.D&256||$CLJS.t===W.He||(W.D?0:$CLJS.Mb($CLJS.kc,W)):$CLJS.Mb($CLJS.kc,W))try{var ba=$CLJS.M.j(W,$CLJS.bQ,$CLJS.lP);if($CLJS.qi.h(ba,$CLJS.lP)){var ha=$CLJS.M.h(W,$CLJS.bQ);return new $CLJS.R(null,1,5,$CLJS.S,[ha],null)}throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){var pa=Ga;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw Ga;}else throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){pa=Ga;if(pa===$CLJS.Z)throw $CLJS.Z;throw pa;}throw Ga;}else throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){pa=Ga;if(pa===
$CLJS.Z)throw $CLJS.Z;throw pa;}throw Ga;}else throw $CLJS.Z;}catch(Ga){if(Ga instanceof Error){pa=Ga;if(pa===$CLJS.Z)return $CLJS.WY(I,B,H);throw pa;}throw Ga;}}($CLJS.Rg,q))));return $CLJS.m(x)?x:$CLJS.Uj}();return $CLJS.th.h(new $CLJS.R(null,2,5,$CLJS.S,[n,q],null),function H(z,B){try{if($CLJS.qe(B)&&2===$CLJS.E(B))try{var I=$CLJS.G(B,0);if($CLJS.O(I,$CLJS.wI))try{var T=$CLJS.G(B,1);if($CLJS.O(T,$CLJS.eB))return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.wI,0,u],null);throw $CLJS.Z;}catch(ba){if(ba instanceof
Error){var W=ba;if(W===$CLJS.Z)throw $CLJS.Z;throw W;}throw ba;}else throw $CLJS.Z;}catch(ba){if(ba instanceof Error){W=ba;if(W===$CLJS.Z)throw $CLJS.Z;throw W;}throw ba;}else throw $CLJS.Z;}catch(ba){if(ba instanceof Error){W=ba;if(W===$CLJS.Z)return $CLJS.FZ(H,z,B);throw W;}throw ba;}}($CLJS.Rg,l))}throw $CLJS.Z;}catch(x){if(x instanceof Error){var v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;
}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)return $CLJS.FZ(e,c,d);throw v;}throw x;}}($CLJS.Rg,a)};
foa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&2<=$CLJS.E(d))try{var f=$CLJS.an.j(d,0,2);if($CLJS.qe(f)&&2===$CLJS.E(f))try{var g=$CLJS.G(f,0);if($CLJS.m(LZ.g?LZ.g(g):LZ.call(null,g))){var l=$CLJS.G(f,0),n=$CLJS.G(f,1),q=$CLJS.an.h(d,2);f=$CLJS.S;var u=new $CLJS.R(null,2,5,$CLJS.S,[l,$CLJS.C(q)],null);var v=MZ.g?MZ.g(u):MZ.call(null,u);return new $CLJS.R(null,3,5,f,[$CLJS.uJ,n,v],null)}throw $CLJS.Z;}catch(z){if(z instanceof Error){var x=z;if(x===$CLJS.Z)throw $CLJS.Z;throw x;}throw z;
}else throw $CLJS.Z;}catch(z){if(z instanceof Error){x=z;if(x===$CLJS.Z)throw $CLJS.Z;throw x;}throw z;}else throw $CLJS.Z;}catch(z){if(z instanceof Error){x=z;if(x===$CLJS.Z)return $CLJS.FZ(e,c,d);throw x;}throw z;}}($CLJS.Rg,a)};
goa=function(a){return function e(c,d){try{if($CLJS.qe(d)&&4<=$CLJS.E(d))try{var f=$CLJS.an.j(d,0,4);if($CLJS.qe(f)&&4===$CLJS.E(f))try{var g=$CLJS.G(f,0);if($CLJS.O(g,$CLJS.XJ)){var l=$CLJS.G(f,1),n=$CLJS.G(f,2),q=$CLJS.G(f,3),u=$CLJS.an.h(d,4);return e(c,$CLJS.th.h(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.XJ,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.XJ,l,n],null)],null),$CLJS.pf(q,u)))}throw $CLJS.Z;}catch(x){if(x instanceof Error){var v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;
}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)return $CLJS.FZ(e,c,d);throw v;}throw x;}}($CLJS.Rg,a)};hoa=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return $CLJS.NZ(0<b.length?new $CLJS.y(b.slice(0),0,null):null)};
$CLJS.NZ=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.j(a,$CLJS.OZ,$CLJS.Ze),c=$CLJS.M.j(a,$CLJS.PZ,function(f,g){return[$CLJS.p.g(f),"_",$CLJS.p.g(g)].join("")}),d=$CLJS.ij.g($CLJS.P),e=$CLJS.ij.g($CLJS.P);return function(){function f(n,q){for(;;){var u=b.g?b.g(q):b.call(null,q),v=function(){var z=new $CLJS.R(null,2,5,$CLJS.S,[n,u],null),B=$CLJS.r(d);return B.g?B.g(z):B.call(null,z)}();if($CLJS.m(v))return v;var x=$CLJS.M.h($CLJS.jj.C(e,$CLJS.Wm,u,$CLJS.gg($CLJS.pu,0)),u);if($CLJS.F.h(x,1))return $CLJS.jj.C(d,
$CLJS.U,new $CLJS.R(null,2,5,$CLJS.S,[n,u],null),q),q;q=function(){var z=q,B=$CLJS.p.g(x);return c.h?c.h(z,B):c.call(null,z,B)}()}}function g(n){var q=l,u=q.h;null==QZ&&(QZ=$CLJS.ij.g(0));var v=$CLJS.$i.g([$CLJS.p.g("G__"),$CLJS.p.g($CLJS.jj.h(QZ,$CLJS.pu))].join(""));return u.call(q,v,n)}var l=null;l=function(n,q){switch(arguments.length){case 1:return g.call(this,n);case 2:return f.call(this,n,q)}throw Error("Invalid arity: "+arguments.length);};l.g=g;l.h=f;return l}()};QZ=null;yZ=/\{0\}/;
$CLJS.RZ=function RZ(a){switch(arguments.length){case 3:return RZ.j(arguments[0],arguments[1],arguments[2]);case 4:return RZ.C(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return RZ.S(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return RZ.Z(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return RZ.l(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],new $CLJS.y(c.slice(6),0,null))}};$CLJS.RZ.j=function(a,b,c){var d=$CLJS.A(b);b=$CLJS.C(d);if(d=$CLJS.D(d))a=$CLJS.U.j(a,b,$CLJS.RZ.j($CLJS.M.h(a,b),d,c));else{d=$CLJS.U.j;var e=$CLJS.M.h(a,b);c=c.g?c.g(e):c.call(null,e);a=d.call($CLJS.U,a,b,c)}return a};
$CLJS.RZ.C=function(a,b,c,d){var e=$CLJS.A(b);b=$CLJS.C(e);if(e=$CLJS.D(e))a=$CLJS.U.j(a,b,$CLJS.RZ.C($CLJS.M.h(a,b),e,c,d));else{e=$CLJS.U.j;var f=$CLJS.M.h(a,b);c=c.h?c.h(f,d):c.call(null,f,d);a=e.call($CLJS.U,a,b,c)}return a};$CLJS.RZ.S=function(a,b,c,d,e){var f=$CLJS.A(b);b=$CLJS.C(f);if(f=$CLJS.D(f))a=$CLJS.U.j(a,b,$CLJS.RZ.S($CLJS.M.h(a,b),f,c,d,e));else{f=$CLJS.U.j;var g=$CLJS.M.h(a,b);c=c.j?c.j(g,d,e):c.call(null,g,d,e);a=f.call($CLJS.U,a,b,c)}return a};
$CLJS.RZ.Z=function(a,b,c,d,e,f){var g=$CLJS.A(b);b=$CLJS.C(g);if(g=$CLJS.D(g))a=$CLJS.U.j(a,b,$CLJS.RZ.Z($CLJS.M.h(a,b),g,c,d,e,f));else{g=$CLJS.U.j;var l=$CLJS.M.h(a,b);c=c.C?c.C(l,d,e,f):c.call(null,l,d,e,f);a=g.call($CLJS.U,a,b,c)}return a};$CLJS.RZ.l=function(a,b,c,d,e,f,g){var l=$CLJS.A(b);b=$CLJS.C(l);return(l=$CLJS.D(l))?$CLJS.U.j(a,b,$CLJS.Q.l($CLJS.RZ,$CLJS.M.h(a,b),l,c,d,$CLJS.J([e,f,g]))):$CLJS.U.j(a,b,$CLJS.Q.l(c,$CLJS.M.h(a,b),d,e,f,$CLJS.J([g])))};
$CLJS.RZ.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);var d=$CLJS.D(c);c=$CLJS.C(d);var e=$CLJS.D(d);d=$CLJS.C(e);var f=$CLJS.D(e);e=$CLJS.C(f);var g=$CLJS.D(f);f=$CLJS.C(g);g=$CLJS.D(g);return this.l(b,a,c,d,e,f,g)};$CLJS.RZ.v=6;
$CLJS.SZ=function SZ(a){switch(arguments.length){case 3:return SZ.j(arguments[0],arguments[1],arguments[2]);case 4:return SZ.C(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return SZ.S(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return SZ.Z(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return SZ.l(arguments[0],arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],new $CLJS.y(c.slice(6),0,null))}};$CLJS.SZ.j=function(a,b,c){var d=$CLJS.Le(a,b);if($CLJS.m(d)){var e=$CLJS.U.j;d=$CLJS.uc(d);c=c.g?c.g(d):c.call(null,d);a=e.call($CLJS.U,a,b,c)}return a};$CLJS.SZ.C=function(a,b,c,d){var e=$CLJS.Le(a,b);if($CLJS.m(e)){var f=$CLJS.U.j;e=$CLJS.uc(e);c=c.h?c.h(e,d):c.call(null,e,d);a=f.call($CLJS.U,a,b,c)}return a};
$CLJS.SZ.S=function(a,b,c,d,e){var f=$CLJS.Le(a,b);if($CLJS.m(f)){var g=$CLJS.U.j;f=$CLJS.uc(f);c=c.j?c.j(f,d,e):c.call(null,f,d,e);a=g.call($CLJS.U,a,b,c)}return a};$CLJS.SZ.Z=function(a,b,c,d,e,f){var g=$CLJS.Le(a,b);if($CLJS.m(g)){var l=$CLJS.U.j;g=$CLJS.uc(g);c=c.C?c.C(g,d,e,f):c.call(null,g,d,e,f);a=l.call($CLJS.U,a,b,c)}return a};$CLJS.SZ.l=function(a,b,c,d,e,f,g){var l=$CLJS.Le(a,b);return $CLJS.m(l)?$CLJS.U.j(a,b,$CLJS.Q.l(c,$CLJS.uc(l),d,e,f,$CLJS.J([g]))):a};
$CLJS.SZ.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);var d=$CLJS.D(c);c=$CLJS.C(d);var e=$CLJS.D(d);d=$CLJS.C(e);var f=$CLJS.D(e);e=$CLJS.C(f);var g=$CLJS.D(f);f=$CLJS.C(g);g=$CLJS.D(g);return this.l(b,a,c,d,e,f,g)};$CLJS.SZ.v=6;var wZ=function wZ(a,b){return $CLJS.vZ($CLJS.fg(wZ,a),a,b)};$CLJS.h=BZ.prototype;$CLJS.h.ka=function(a,b){return this.U(null,b,null)};
$CLJS.h.U=function(a,b,c){switch(b instanceof $CLJS.N?b.N:null){case "output-schema":return this.Dc;case "input-schemas":return this.oc;default:return $CLJS.M.j(this.m,b,c)}};$CLJS.h.va=function(a,b,c){return $CLJS.Tb(function(d,e){var f=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);return b.j?b.j(d,f,e):b.call(null,d,f,e)},c,this)};
$CLJS.h.W=function(a,b,c){return $CLJS.Oi(b,function(d){return $CLJS.Oi(b,$CLJS.Ti,""," ","",c,d)},"#schema.core.FnSchema{",", ","}",c,$CLJS.wg.h(new $CLJS.R(null,2,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.wM,this.Dc],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.uM,this.oc],null)],null),this.m))};$CLJS.h.oa=function(){return new $CLJS.jh(this,2,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.wM,$CLJS.uM],null),$CLJS.m(this.m)?$CLJS.fd(this.m):$CLJS.Xf())};$CLJS.h.M=function(){return this.F};
$CLJS.h.ea=function(){return 2+$CLJS.E(this.m)};$CLJS.h.ca=function(){var a=this.G;return null!=a?a:this.G=a=-2054647546^$CLJS.Ed(this)};$CLJS.h.T=function(a,b){return null!=b&&this.constructor===b.constructor&&$CLJS.F.h(this.Dc,b.Dc)&&$CLJS.F.h(this.oc,b.oc)&&$CLJS.F.h(this.m,b.m)};
$CLJS.h.za=function(a,b){return $CLJS.Ie(new $CLJS.ti(null,new $CLJS.k(null,2,[$CLJS.wM,null,$CLJS.uM,null],null),null),b)?$CLJS.Jm.h($CLJS.Dc($CLJS.th.h($CLJS.P,this),this.F),b):new BZ(this.Dc,this.oc,this.F,$CLJS.Vf($CLJS.Jm.h(this.m,b)),null)};$CLJS.h.ta=function(a,b){switch(b instanceof $CLJS.N?b.N:null){case "output-schema":case "input-schemas":return!0;default:return $CLJS.Ie(this.m,b)}};
$CLJS.h.$=function(a,b,c){return $CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.wM,b):$CLJS.O.call(null,$CLJS.wM,b))?new BZ(c,this.oc,this.F,this.m,null):$CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.uM,b):$CLJS.O.call(null,$CLJS.uM,b))?new BZ(this.Dc,c,this.F,this.m,null):new BZ(this.Dc,this.oc,this.F,$CLJS.U.j(this.m,b,c),null)};$CLJS.h.da=function(){return $CLJS.A($CLJS.wg.h(new $CLJS.R(null,2,5,$CLJS.S,[new $CLJS.Ke($CLJS.wM,this.Dc),new $CLJS.Ke($CLJS.uM,this.oc)],null),this.m))};
$CLJS.h.O=function(a,b){return new BZ(this.Dc,this.oc,b,this.m,this.G)};$CLJS.h.ja=function(a,b){return $CLJS.qe(b)?this.$(null,$CLJS.be(b,0),$CLJS.be(b,1)):$CLJS.Tb($CLJS.dc,this,b)};$CLJS.h.Ab=function(){return $CLJS.BL($CLJS.tL(this,$CLJS.ze,function(a){return new $CLJS.jf(null,$CLJS.Sj,new $CLJS.jf(null,a,null,1,null),2,null)}))};
$CLJS.h.Ea=function(){if(1<$CLJS.E(this.oc)){var a=$CLJS.XL(this.Dc);var b=$CLJS.xg.h(AZ,this.oc);a=$CLJS.pf($CLJS.uha,$CLJS.pf(a,b))}else a=$CLJS.XL(this.Dc),b=AZ($CLJS.C(this.oc)),a=$CLJS.pf($CLJS.zha,$CLJS.pf(a,b));return a};$CLJS.h.ma=$CLJS.t;$CLJS.h.W=function(a,b){return $CLJS.Qc(b,this.Ea(null))};ioa=new $CLJS.N(null,"index","index",-1531685915);WZ=new $CLJS.w("s","maybe","s/maybe",1326133944,null);XZ=new $CLJS.w(null,"new-clause","new-clause",-910348391,null);
joa=new $CLJS.N(null,"found","found",-584700170);koa=new $CLJS.w(null,"outer-query","outer-query",-395069361,null);loa=new $CLJS.w(null,"names","names",-302543131,null);YZ=new $CLJS.w(null,"inner-query","inner-query",-907556093,null);moa=new $CLJS.w("schema.helpers","NonBlankString","schema.helpers/NonBlankString",1984244415,null);$CLJS.PZ=new $CLJS.N(null,"unique-alias-fn","unique-alias-fn",32555420);ZZ=new $CLJS.w(null,"aggregation-\x3ename-fn","aggregation-\x3ename-fn",596978962,null);
noa=new $CLJS.N(null,"invalid-query","invalid-query",-1009703371);$Z=new $CLJS.w("schema.core","Any","schema.core/Any",-1891898271,null);ooa=new $CLJS.w(null,"named-aggregations","named-aggregations",-771029585,null);poa=new $CLJS.w(null,"join","join",881669637,null);a_=new $CLJS.w(null,"aggregations","aggregations",559417189,null);b_=new $CLJS.w(null,"filter-clause","filter-clause",-1237814159,null);c_=new $CLJS.w(null,"arg0","arg0",-1024593414,null);
qoa=new $CLJS.w(null,"arg1","arg1",-1702536411,null);roa=new $CLJS.w("mbql.s","FieldOrExpressionDef","mbql.s/FieldOrExpressionDef",-1851966074,null);d_=new $CLJS.w("mbql.s","Filter","mbql.s/Filter",650308569,null);$CLJS.OZ=new $CLJS.N(null,"name-key-fn","name-key-fn",-1634839199);soa=new $CLJS.w(null,"nesting-level","nesting-level",-2057556677,null);toa=new $CLJS.N(null,"tried","tried",-1728444308);uoa=new $CLJS.w(null,"NamedAggregation","NamedAggregation",1856050571,null);
voa=new $CLJS.w("s","Keyword","s/Keyword",-850066400,null);e_=new $CLJS.w(null,"query","query",352022017,null);woa=new $CLJS.w(null,"expression-name","expression-name",-157919182,null);f_=new $CLJS.w(null,"index","index",108845612,null);g_=new $CLJS.w("mbql.s","MBQLQuery","mbql.s/MBQLQuery",-332777720,null);h_=new $CLJS.w("schema.helpers","IntGreaterThanOrEqualToZero","schema.helpers/IntGreaterThanOrEqualToZero",-1218348852,null);
i_=new $CLJS.w("mbql.s","Aggregation","mbql.s/Aggregation",124504849,null);j_=new $CLJS.w("mbql.s","Query","mbql.s/Query",1061827921,null);var xoa;xoa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M($CLJS.Qha,$CLJS.fe(new $CLJS.w(null,"token","token",429068312,null),new $CLJS.k(null,1,[$CLJS.hm,new $CLJS.w("schema.helpers","KeywordOrString","schema.helpers/KeywordOrString",-360677001,null)],null)))],null);$CLJS.k_=function(a){return $CLJS.Ui.g($CLJS.zu($CLJS.GZ(a).toLowerCase(),/_/,"-"))};sZ($CLJS.k_,CZ($CLJS.PM,new $CLJS.R(null,1,5,$CLJS.S,[xoa],null)));
var yoa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.KM,$CLJS.fe(b_,new $CLJS.k(null,1,[$CLJS.hm,$Z],null))),$CLJS.KM],null);TZ=function zoa(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return zoa.l(arguments[0],1<c.length?new $CLJS.y(c.slice(1),0,null):null)};TZ.l=function(a,b){return $CLJS.JZ($CLJS.pf($CLJS.Qj,$CLJS.pf(a,b)))};TZ.v=1;TZ.B=function(a){var b=$CLJS.C(a);a=$CLJS.D(a);return this.l(b,a)};sZ(TZ,CZ($CLJS.dT,new $CLJS.R(null,1,5,$CLJS.S,[yoa],null)));
var Aoa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.hU,$CLJS.fe(YZ,new $CLJS.k(null,1,[$CLJS.hm,g_],null))),$CLJS.$M($CLJS.jN($CLJS.dT),$CLJS.fe(XZ,new $CLJS.k(null,1,[$CLJS.hm,$CLJS.Y(WZ,d_)],null)))],null),l_;l_=function(a,b){return $CLJS.Fb(b)?a:$CLJS.Wm.C(a,$CLJS.TN,TZ,b)};sZ(l_,CZ($CLJS.hU,new $CLJS.R(null,1,5,$CLJS.S,[Aoa],null)));
var Boa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.rU,$CLJS.fe(koa,new $CLJS.k(null,1,[$CLJS.hm,j_],null))),$CLJS.$M($CLJS.jN($CLJS.dT),$CLJS.fe(XZ,new $CLJS.k(null,1,[$CLJS.hm,$CLJS.Y(WZ,d_)],null)))],null);sZ(function(a,b){return $CLJS.Wm.C(a,$CLJS.GN,l_,b)},CZ($CLJS.rU,new $CLJS.R(null,1,5,$CLJS.S,[Boa],null)));
var MZ=$CLJS.Yh([new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$J,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.KH,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.iJ,$CLJS.vI],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.iJ,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.DJ,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.gJ,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.mJ,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.eH,null],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.pJ,null],null),new $CLJS.R(null,2,5,
$CLJS.S,[$CLJS.iJ,$CLJS.BH],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.iJ,$CLJS.NI],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.JH,null],null)],[$CLJS.lk,$CLJS.jI,$CLJS.bK,$CLJS.bI,$CLJS.gk,$CLJS.zl,$CLJS.Wk,$CLJS.fm,$CLJS.rk,$CLJS.bI,$CLJS.gK,$CLJS.OH]),LZ=$CLJS.yi($CLJS.xg.h($CLJS.C,$CLJS.mi(MZ))),Coa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M($CLJS.GT,$CLJS.fe($CLJS.bO,new $CLJS.k(null,1,[$CLJS.hm,roa],null)))],null),m_;m_=function(a){return goa(a)};
sZ(m_,CZ($CLJS.GT,new $CLJS.R(null,1,5,$CLJS.S,[Coa],null)));var Doa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M($CLJS.dT,$CLJS.fe(b_,new $CLJS.k(null,1,[$CLJS.hm,d_],null)))],null),n_;n_=function(a){a=foa($CLJS.JZ(Zna(aoa($na(boa(coa(doa(eoa(a)))))))));return $CLJS.m((0,$CLJS.Yna)(a))?m_(a):a};sZ(n_,CZ($CLJS.dT,new $CLJS.R(null,1,5,$CLJS.S,[Doa],null)));
var o_,Eoa=$CLJS.ij.g($CLJS.P),Foa=$CLJS.ij.g($CLJS.P),Goa=$CLJS.ij.g($CLJS.P),Hoa=$CLJS.ij.g($CLJS.P),Ioa=$CLJS.M.j($CLJS.P,$CLJS.Vk,$CLJS.rj.A?$CLJS.rj.A():$CLJS.rj.call(null));o_=new $CLJS.Aj($CLJS.$i.h("metabase.mbql.util","negate*"),$CLJS.C,$CLJS.Uj,Ioa,Eoa,Foa,Goa,Hoa);o_.o(null,$CLJS.Yk,function(a){$CLJS.K(a,0,null);return $CLJS.K(a,1,null)});o_.o(null,$CLJS.Qj,function(a){a=$CLJS.A(a);$CLJS.C(a);a=$CLJS.D(a);return $CLJS.th.h(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.Gk],null),$CLJS.xg.h(o_,a))});
o_.o(null,$CLJS.Gk,function(a){a=$CLJS.A(a);$CLJS.C(a);a=$CLJS.D(a);return $CLJS.th.h(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.Qj],null),$CLJS.xg.h(o_,a))});o_.o(null,$CLJS.lm,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.JJ,b,a],null)});o_.o(null,$CLJS.JJ,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.lm,b,a],null)});
o_.o(null,$CLJS.pm,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.zm,b,a],null)});o_.o(null,$CLJS.mm,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.ym,b,a],null)});o_.o(null,$CLJS.ym,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.mm,b,a],null)});
o_.o(null,$CLJS.zm,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.pm,b,a],null)});o_.o(null,$CLJS.PH,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null),c=$CLJS.K(a,2,null);a=$CLJS.K(a,3,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Gk,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.mm,b,c],null),new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.pm,b,a],null)],null)});o_.o(null,$CLJS.QI,function(a){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Yk,a],null)});
o_.o(null,$CLJS.zI,function(a){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Yk,a],null)});o_.o(null,$CLJS.sJ,function(a){return new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Yk,a],null)});var Joa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M($CLJS.dT,$CLJS.fe(b_,new $CLJS.k(null,1,[$CLJS.hm,d_],null)))],null);sZ(function(a){return $CLJS.JZ(o_.g(n_(a)))},CZ($CLJS.dT,new $CLJS.R(null,1,5,$CLJS.S,[Joa],null)));var Koa=$CLJS.jN($CLJS.WM),Loa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M($CLJS.KM,c_)],null),p_;
p_=function(a){for(;;){var b=$CLJS.Uf(a);a=b;var c=$CLJS.M.h(b,$CLJS.GN);c=$CLJS.Uf(c);var d=$CLJS.M.h(c,$CLJS.kP),e=$CLJS.M.h(c,$CLJS.xQ);b=$CLJS.M.h(b,$CLJS.al);if($CLJS.qi.h(b,$CLJS.GN)||$CLJS.m(function(){var f=null==d;return f?(f=e,$CLJS.m(f)?$CLJS.fQ.g(e):f):f}()))return null;if($CLJS.m(function(){var f=null==d;return f?e:f}()))a=$CLJS.U.j(a,$CLJS.GN,e);else{if($CLJS.m($CLJS.Sm.h($CLJS.Jb,$CLJS.fg($CLJS.Ji,$CLJS.kU))(d)))throw $CLJS.Ej($CLJS.bH("Error: query''s source query has not been resolved. You probably need to `preprocess` the query first."),
$CLJS.P);return d}}};sZ(p_,CZ(Koa,new $CLJS.R(null,1,5,$CLJS.S,[Loa],null)));var Moa=$CLJS.jN($CLJS.WM),Noa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M($CLJS.KM,$CLJS.fe(poa,new $CLJS.k(null,1,[$CLJS.hm,$Z],null)))],null);sZ(function(a){return p_(new $CLJS.k(null,2,[$CLJS.al,$CLJS.GN,$CLJS.GN,a],null))},CZ(Moa,new $CLJS.R(null,1,5,$CLJS.S,[Noa],null)));var Ooa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.hU,$CLJS.fe(YZ,new $CLJS.k(null,1,[$CLJS.hm,g_],null))),$CLJS.$M($CLJS.bU,qoa)],null);
sZ(function(a,b){$CLJS.K(b,0,null);var c=$CLJS.K(b,1,null);$CLJS.K(c,0,null);c=$CLJS.K(c,1,null);var d=$CLJS.yi(function(){return function g(f){return new $CLJS.Af(null,function(){for(;;){var l=$CLJS.A(f);if(l){if($CLJS.re(l)){var n=$CLJS.$c(l),q=$CLJS.E(n),u=$CLJS.Df(q);a:for(var v=0;;)if(v<q){var x=$CLJS.be(n,v);$CLJS.K(x,0,null);x=$CLJS.K(x,1,null);$CLJS.K(x,0,null);x=$CLJS.K(x,1,null);u.add(x);v+=1}else{n=!0;break a}return n?$CLJS.If($CLJS.Kf(u),g($CLJS.ad(l))):$CLJS.If($CLJS.Kf(u),null)}u=$CLJS.C(l);
$CLJS.K(u,0,null);u=$CLJS.K(u,1,null);$CLJS.K(u,0,null);u=$CLJS.K(u,1,null);return $CLJS.pf(u,g($CLJS.zd(l)))}return null}},null,null)}($CLJS.kR.g(a))}());return $CLJS.m(d.g?d.g(c):d.call(null,c))?a:$CLJS.Wm.C(a,$CLJS.kR,$CLJS.Rm.j($CLJS.Sg,$CLJS.on,$CLJS.mf),b)},CZ($CLJS.hU,new $CLJS.R(null,1,5,$CLJS.S,[Ooa],null)));
var Poa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.KM,$CLJS.fe(YZ,new $CLJS.k(null,1,[$CLJS.hm,$Z],null))),$CLJS.$M($CLJS.SM($CLJS.J([$CLJS.PM,$CLJS.TM])),$CLJS.fe(woa,new $CLJS.k(null,1,[$CLJS.hm,$CLJS.Y($CLJS.GP,voa,moa)],null)))],null);
sZ(function(a,b){var c=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.GZ(b),$CLJS.Ui.g(b)],null),d=$CLJS.Uf(a);$CLJS.M.h(d,$CLJS.aQ);$CLJS.M.h(d,$CLJS.xQ);for(var e=$CLJS.ui;;){a=$CLJS.Uf(a);d=$CLJS.M.h(a,$CLJS.aQ);a=$CLJS.M.h(a,$CLJS.xQ);var f=$CLJS.ag($CLJS.fg($CLJS.M,d),c);if($CLJS.m(f))return f;d=$CLJS.th.h(e,$CLJS.mi(d));if($CLJS.m(a))e=d;else throw $CLJS.Ej($CLJS.aH("No expression named ''{0}''",$CLJS.J([$CLJS.GZ(b)])),new $CLJS.k(null,4,[$CLJS.al,noa,$CLJS.wR,b,toa,c,joa,d],null));}},CZ($CLJS.GT,new $CLJS.R(null,
1,5,$CLJS.S,[Poa],null)));var Qoa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.KM,$CLJS.fe(e_,new $CLJS.k(null,1,[$CLJS.hm,$Z],null))),$CLJS.$M($CLJS.KM,$CLJS.fe(f_,new $CLJS.k(null,1,[$CLJS.hm,$Z],null)))],null),Roa=new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.$M($CLJS.rU,$CLJS.fe(e_,new $CLJS.k(null,1,[$CLJS.hm,j_],null))),$CLJS.$M($CLJS.XM,$CLJS.fe(f_,new $CLJS.k(null,1,[$CLJS.hm,h_],null))),$CLJS.$M($CLJS.XM,$CLJS.fe(soa,new $CLJS.k(null,1,[$CLJS.hm,h_],null)))],null);
UZ=function q_(a){switch(arguments.length){case 2:return q_.h(arguments[0],arguments[1]);case 3:return q_.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};UZ.h=function(a,b){return UZ.j(a,b,0)};
UZ.j=function(a,b,c){for(;;){if(0===c){a=$CLJS.G($CLJS.vu(a,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.GN,$CLJS.ZO],null)),b);if($CLJS.m(a))return a;throw $CLJS.Ej($CLJS.aH("No aggregation at index: {0}",$CLJS.J([b])),new $CLJS.k(null,1,[ioa,b],null));}a=new $CLJS.k(null,1,[$CLJS.GN,$CLJS.vu(a,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.GN,$CLJS.xQ],null))],null);--c}};UZ.v=3;var r_,Soa=$CLJS.hS,s_=new $CLJS.R(null,2,5,$CLJS.S,[Qoa,Roa],null);
if(!$CLJS.A(s_))throw Error($CLJS.eL("Function must have at least one input schema"));if(!$CLJS.$f($CLJS.qe,s_))throw Error($CLJS.eL("Each arity must be a vector."));if(!$CLJS.m($CLJS.Q.h($CLJS.Cu,$CLJS.xg.h(DZ,s_))))throw Error($CLJS.eL("Arities must be distinct"));r_=new BZ(Soa,$CLJS.uZ(DZ,s_),null,null,null);sZ(UZ,r_);
var Toa=$CLJS.fM(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.LM],null),$CLJS.Cu,"sequence of unique strings"),Uoa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.LM],null),$CLJS.fe(loa,new $CLJS.k(null,1,[$CLJS.hm,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.bP],null)],null)))],null),t_;t_=function(a){return $CLJS.xg.h(hoa(),a)};sZ(t_,CZ(Toa,new $CLJS.R(null,1,5,$CLJS.S,[Uoa],null)));
var u_=$CLJS.fM($CLJS.ZT,function(a){return $CLJS.V.g($CLJS.G(a,2))},"`:aggregation-options` with a `:name`"),v_=$CLJS.fM(new $CLJS.R(null,1,5,$CLJS.S,[u_],null),function(a){return $CLJS.Q.h($CLJS.Cu,function(){return function d(c){return new $CLJS.Af(null,function(){for(;;){var e=$CLJS.A(c);if(e){if($CLJS.re(e)){var f=$CLJS.$c(e),g=$CLJS.E(f),l=$CLJS.Df(g);a:for(var n=0;;)if(n<g){var q=$CLJS.be(f,n);$CLJS.K(q,0,null);$CLJS.K(q,1,null);q=$CLJS.K(q,2,null);q=$CLJS.Uf(q);q=$CLJS.M.h(q,$CLJS.V);l.add(q);
n+=1}else{f=!0;break a}return f?$CLJS.If($CLJS.Kf(l),d($CLJS.ad(e))):$CLJS.If($CLJS.Kf(l),null)}l=$CLJS.C(e);$CLJS.K(l,0,null);$CLJS.K(l,1,null);l=$CLJS.K(l,2,null);l=$CLJS.Uf(l);l=$CLJS.M.h(l,$CLJS.V);return $CLJS.pf(l,d($CLJS.zd(e)))}return null}},null,null)}(a)}())},"sequence of named aggregations with unique names"),Voa=new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.$M(new $CLJS.R(null,1,5,$CLJS.S,[u_],null),$CLJS.fe(ooa,new $CLJS.k(null,1,[$CLJS.hm,new $CLJS.R(null,1,5,$CLJS.S,[uoa],null)],null)))],null),
w_;
w_=function(a){var b=t_(function(){return function e(d){return new $CLJS.Af(null,function(){for(;;){var f=$CLJS.A(d);if(f){if($CLJS.re(f)){var g=$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);a:for(var q=0;;)if(q<l){var u=$CLJS.be(g,q);$CLJS.K(u,0,null);$CLJS.K(u,1,null);u=$CLJS.K(u,2,null);u=$CLJS.Uf(u);u=$CLJS.M.h(u,$CLJS.V);n.add(u);q+=1}else{g=!0;break a}return g?$CLJS.If($CLJS.Kf(n),e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}n=$CLJS.C(f);$CLJS.K(n,0,null);$CLJS.K(n,1,null);n=$CLJS.K(n,2,null);n=$CLJS.Uf(n);n=
$CLJS.M.h(n,$CLJS.V);return $CLJS.pf(n,e($CLJS.zd(f)))}return null}},null,null)}(a)}());return $CLJS.xg.j(function(c,d){$CLJS.K(c,0,null);var e=$CLJS.K(c,1,null);c=$CLJS.K(c,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.yN,e,$CLJS.U.j(c,$CLJS.V,d)],null)},a,b)};sZ(w_,CZ(v_,new $CLJS.R(null,1,5,$CLJS.S,[Voa],null)));
var Woa=new $CLJS.R(null,1,5,$CLJS.S,[u_],null),Xoa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.bM($CLJS.de,$CLJS.$i.g($CLJS.gL($CLJS.de))),$CLJS.fe(ZZ,new $CLJS.k(null,1,[$CLJS.hm,$CLJS.Y($CLJS.BP,$CLJS.Ak)],null))),$CLJS.$M(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.hS],null),$CLJS.fe(a_,new $CLJS.k(null,1,[$CLJS.hm,new $CLJS.R(null,1,5,$CLJS.S,[i_],null)],null)))],null),x_;
x_=function(a,b){return function f(d,e){try{if($CLJS.qe(e)&&3===$CLJS.E(e))try{var g=$CLJS.G(e,0);if($CLJS.O(g,$CLJS.yN))try{var l=$CLJS.G(e,2);if($CLJS.m($CLJS.V.g(l)))return e;throw $CLJS.Z;}catch(z){if(z instanceof Error){var n=z;if(n===$CLJS.Z){var q=$CLJS.G(e,2),u=$CLJS.G(e,1);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.yN,u,$CLJS.U.j(q,$CLJS.V,a.g?a.g(u):a.call(null,u))],null)}throw n;}throw z;}else throw $CLJS.Z;}catch(z){if(z instanceof Error){n=z;if(n===$CLJS.Z)throw $CLJS.Z;throw n;}throw z;
}else throw $CLJS.Z;}catch(z){if(z instanceof Error)if(n=z,n===$CLJS.Z)try{if($CLJS.qe(e)&&1<=$CLJS.E(e))try{var v=$CLJS.an.j(e,0,1);if($CLJS.qe(v)&&1===$CLJS.E(v))try{if($CLJS.G(v,0)instanceof $CLJS.N)return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.yN,e,new $CLJS.k(null,1,[$CLJS.V,a.g?a.g(e):a.call(null,e)],null)],null);throw $CLJS.Z;}catch(B){if(B instanceof Error){var x=B;if(x===$CLJS.Z)throw $CLJS.Z;throw x;}throw B;}else throw $CLJS.Z;}catch(B){if(B instanceof Error){x=B;if(x===$CLJS.Z)throw $CLJS.Z;
throw x;}throw B;}else throw $CLJS.Z;}catch(B){if(B instanceof Error){x=B;if(x===$CLJS.Z)return $CLJS.FZ(f,d,e);throw x;}throw B;}else throw n;else throw z;}}($CLJS.Rg,b)};sZ(x_,CZ(Woa,new $CLJS.R(null,1,5,$CLJS.S,[Xoa],null)));
var Yoa=new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.$M($CLJS.bM($CLJS.de,$CLJS.$i.g($CLJS.gL($CLJS.de))),$CLJS.fe(ZZ,new $CLJS.k(null,1,[$CLJS.hm,$CLJS.Y($CLJS.BP,$CLJS.Ak)],null))),$CLJS.$M(new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.hS],null),$CLJS.fe(a_,new $CLJS.k(null,1,[$CLJS.hm,new $CLJS.R(null,1,5,$CLJS.S,[i_],null)],null)))],null);sZ(function(a,b){return w_(x_(a,b))},CZ(v_,new $CLJS.R(null,1,5,$CLJS.S,[Yoa],null)));
var y_=function y_(a){return $CLJS.oe(a)?$CLJS.Vf($CLJS.th.h($CLJS.P,function(){return function e(d){return new $CLJS.Af(null,function(){for(var f=d;;)if(f=$CLJS.A(f)){if($CLJS.re(f)){var g=$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);a:for(var q=0;;)if(q<l){var u=$CLJS.be(g,q),v=$CLJS.K(u,0,null);u=$CLJS.K(u,1,null);u=y_.g?y_.g(u):y_.call(null,u);null!=u&&n.add(new $CLJS.R(null,2,5,$CLJS.S,[v,u],null));q+=1}else{g=!0;break a}return g?$CLJS.If($CLJS.Kf(n),e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}g=$CLJS.C(f);
n=$CLJS.K(g,0,null);g=$CLJS.K(g,1,null);g=y_.g?y_.g(g):y_.call(null,g);if(null!=g)return $CLJS.pf(new $CLJS.R(null,2,5,$CLJS.S,[n,g],null),e($CLJS.zd(f)));f=$CLJS.zd(f)}else return null},null,null)}(a)}())):$CLJS.ne(a)?$CLJS.Vf($CLJS.th.h($CLJS.ae(a),$CLJS.Ag($CLJS.Gb,$CLJS.xg.h(y_,a)))):a},Zoa=new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.$M($CLJS.ZR,c_),$CLJS.$M($CLJS.KM,$CLJS.fe($CLJS.Qk,new $CLJS.k(null,1,[$CLJS.hm,$Z],null))),$CLJS.KM],null);
$CLJS.VZ=function $oa(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $oa.l(arguments[0],arguments[1],2<c.length?new $CLJS.y(c.slice(2),0,null):null)};$CLJS.VZ.l=function(a,b,c){var d=$CLJS.K(a,0,null),e=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);b=$CLJS.Vf(y_($CLJS.Q.j(b,a,c)));return $CLJS.m(b)?new $CLJS.R(null,3,5,$CLJS.S,[d,e,b],null):$CLJS.F.h(d,$CLJS.PP)?new $CLJS.R(null,3,5,$CLJS.S,[d,e,null],null):new $CLJS.R(null,2,5,$CLJS.S,[d,e],null)};
$CLJS.VZ.v=2;$CLJS.VZ.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);c=$CLJS.D(c);return this.l(b,a,c)};sZ($CLJS.VZ,CZ($CLJS.ZR,new $CLJS.R(null,1,5,$CLJS.S,[Zoa],null)));