var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./medley.core.js");require("./metabase.lib.convert.js");require("./metabase.lib.core.js");require("./metabase.lib.join.js");require("./metabase.lib.js.metadata.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.protocols.js");require("./metabase.lib.stage.js");require("./metabase.mbql.js.js");require("./metabase.mbql.normalize.js");require("./metabase.util.js");require("./metabase.util.log.js");
'use strict';var rxa=function(a){return $CLJS.Vc($CLJS.Tb(function(b,c){return $CLJS.xh.j(b,c,$CLJS.M.j(b,c,0)+1)},$CLJS.Tc($CLJS.P),a))},H9=function(a,b){return new $CLJS.dj(function(){try{return $CLJS.E9.h(a,b)}catch(e){if(e instanceof Error){var c=e,d=$CLJS.mF($CLJS.Nu);$CLJS.m($CLJS.qF("metabase.lib.js.metadata",d))&&(c instanceof Error?$CLJS.rF("metabase.lib.js.metadata",d,$CLJS.z_("Error parsing %s objects: %s",$CLJS.J([a,$CLJS.rZ(c)])),c):$CLJS.rF("metabase.lib.js.metadata",d,$CLJS.z_(c,$CLJS.J(["Error parsing %s objects: %s",
a,$CLJS.rZ(c)])),null));return null}throw e;}})},sxa=function(a,b){return function e(d){return new $CLJS.Af(null,function(){for(var f=d;;)if(f=$CLJS.A(f)){if($CLJS.re(f)){var g=$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);return function(){for(var x=0;;)if(x<l){var z=$CLJS.be(g,x);$CLJS.K(z,0,null);var B=$CLJS.K(z,1,null),H=function(){var I=B;return null==I?null:$CLJS.r(I)}();$CLJS.m(function(){var I=H;return $CLJS.m(I)?$CLJS.F.h($CLJS.N_.g(H),b):I}())&&n.add(H);x+=1}else return!0}()?$CLJS.If($CLJS.Kf(n),
e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}var q=$CLJS.C(f);$CLJS.K(q,0,null);var u=$CLJS.K(q,1,null),v=function(){var x=u;return null==x?null:$CLJS.r(x)}();if($CLJS.m(function(){var x=v;return $CLJS.m(x)?$CLJS.F.h($CLJS.N_.g(v),b):x}()))return $CLJS.pf(v,e($CLJS.zd(f)));f=$CLJS.zd(f)}else return null},null,null)}(function(){var d=null==a?null:$CLJS.AH.g(a);return null==d?null:$CLJS.r(d)}())},txa=function(a,b){return function e(d){return new $CLJS.Af(null,function(){for(var f=d;;)if(f=$CLJS.A(f)){if($CLJS.re(f)){var g=
$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);return function(){for(var x=0;;)if(x<l){var z=$CLJS.be(g,x);$CLJS.K(z,0,null);var B=$CLJS.K(z,1,null),H=function(){var I=B;return null==I?null:$CLJS.r(I)}();$CLJS.m(function(){var I=H;return $CLJS.m(I)?$CLJS.F.h($CLJS.N_.g(H),b):I}())&&n.add(H);x+=1}else return!0}()?$CLJS.If($CLJS.Kf(n),e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}var q=$CLJS.C(f);$CLJS.K(q,0,null);var u=$CLJS.K(q,1,null),v=function(){var x=u;return null==x?null:$CLJS.r(x)}();if($CLJS.m(function(){var x=
v;return $CLJS.m(x)?$CLJS.F.h($CLJS.N_.g(v),b):x}()))return $CLJS.pf(v,e($CLJS.zd(f)));f=$CLJS.zd(f)}else return null},null,null)}(function(){var d=null==a?null:$CLJS.A9.g(a);return null==d?null:$CLJS.r(d)}())},I9=function(a,b,c,d){this.Ig=a;this.jj=b;this.bd=c;this.Oi=d;this.D=393216;this.K=0},J9=function(a,b){if($CLJS.S_(b))a=b;else{var c=new $CLJS.k(null,6,[$CLJS.D9,H9($CLJS.YP,b),$CLJS.M_,H9($CLJS.O_,b),$CLJS.AH,H9($CLJS.PP,b),$CLJS.z9,H9($CLJS.ZN,b),$CLJS.A9,H9($CLJS.mP,b),$CLJS.B9,H9($CLJS.sH,
b)],null),d=$CLJS.mF($CLJS.ND);$CLJS.m($CLJS.qF("metabase.lib.js.metadata",d))&&$CLJS.rF("metabase.lib.js.metadata",d,$CLJS.MB.l($CLJS.J(["Created metadata provider for metadata"])),null);a=new I9(a,b,c,$CLJS.P)}return a},K9=function(a,b){return $CLJS.SZ.j($CLJS.SZ.j((0,$CLJS.u7)($CLJS.G9($CLJS.$E(a))),$CLJS.fQ,function(c){return $CLJS.mn.l($CLJS.J([new $CLJS.k(null,1,[$CLJS.uQ,$CLJS.P],null),c]))}),$CLJS.GN,function(c){var d=function(){var e=$CLJS.AH.g(c);return $CLJS.m(e)?e:function l(g){return new $CLJS.Af(null,
function(){for(;;){var n=$CLJS.A(g);if(n){if($CLJS.re(n)){var q=$CLJS.$c(n),u=$CLJS.E(q),v=$CLJS.Df(u);a:for(var x=0;;)if(x<u){var z=$CLJS.be(q,x);v.add(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,z,null],null));x+=1}else{q=!0;break a}return q?$CLJS.If($CLJS.Kf(v),l($CLJS.ad(n))):$CLJS.If($CLJS.Kf(v),null)}v=$CLJS.C(n);return $CLJS.pf(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,v,null],null),l($CLJS.zd(n)))}return null}},null,null)}(b)}();return $CLJS.U.j(c,$CLJS.AH,rxa(d))})};$CLJS.h=I9.prototype;
$CLJS.h.O=function(a,b){return new I9(this.Ig,this.jj,this.bd,b)};$CLJS.h.M=function(){return this.Oi};$CLJS.h.Pi=$CLJS.t;$CLJS.h.Yg=function(a,b){a=this.bd;a=null==a?null:$CLJS.A9.g(a);a=null==a?null:$CLJS.r(a);b=null==a?null:$CLJS.M.h(a,b);return null==b?null:$CLJS.r(b)};$CLJS.h.Zg=function(a,b){return txa(this.bd,b)};$CLJS.h.ah=function(a,b){a=this.bd;a=null==a?null:$CLJS.M_.g(a);a=null==a?null:$CLJS.r(a);b=null==a?null:$CLJS.M.h(a,b);return null==b?null:$CLJS.r(b)};
$CLJS.h.Xg=function(a,b){return sxa(this.bd,b)};$CLJS.h.Wg=function(a,b){a=this.bd;a=null==a?null:$CLJS.AH.g(a);a=null==a?null:$CLJS.r(a);b=null==a?null:$CLJS.M.h(a,b);return null==b?null:$CLJS.r(b)};$CLJS.h.Ug=function(a,b){a=this.bd;a=null==a?null:$CLJS.z9.g(a);a=null==a?null:$CLJS.r(a);b=null==a?null:$CLJS.M.h(a,b);return null==b?null:$CLJS.r(b)};$CLJS.h.$g=function(a,b){a=this.bd;a=null==a?null:$CLJS.B9.g(a);a=null==a?null:$CLJS.r(a);b=null==a?null:$CLJS.M.h(a,b);return null==b?null:$CLJS.r(b)};
$CLJS.h.Vg=function(){var a=this.bd,b=this.Ig;a=null==a?null:$CLJS.D9.g(a);a=null==a?null:$CLJS.r(a);b=null==a?null:$CLJS.M.h(a,b);return null==b?null:$CLJS.r(b)};var L9=function L9(a){switch(arguments.length){case 1:return L9.g(arguments[0]);case 2:return L9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.extract_template_tags",L9);L9.g=function(a){return L9.h(a,$CLJS.P)};L9.h=function(a,b){return $CLJS.n9.l($CLJS.J([$CLJS.wwa.l($CLJS.J([a,$CLJS.m9.l($CLJS.J([b]))]))]))};L9.v=2;
var M9=function M9(a){return $CLJS.zf(a)?[$CLJS.sf(a),"/",$CLJS.Ai(a)].join(""):$CLJS.oe(a)?$CLJS.wu(a,M9):$CLJS.ne(a)?$CLJS.xg.h(M9,a):a},N9=function N9(a){switch(arguments.length){case 1:return N9.g(arguments[0]);case 2:return N9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.order_by_clause",N9);N9.g=function(a){return N9.h(a,$CLJS.KI)};
N9.h=function(a,b){return $CLJS.zwa.l($CLJS.J([$CLJS.o9.l($CLJS.J([$CLJS.ZE(a,$CLJS.J([$CLJS.kk,!0]))])),$CLJS.Ui.g(b)]))};N9.v=2;var O9=function O9(a){switch(arguments.length){case 2:return O9.h(arguments[0],arguments[1]);case 3:return O9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.available_binning_strategies",O9);O9.h=function(a,b){return $CLJS.Pe($CLJS.l9.l($CLJS.J([a,b])))};
O9.j=function(a,b,c){return $CLJS.Pe($CLJS.l9.l($CLJS.J([a,b,c])))};O9.v=3;var P9=function P9(a){switch(arguments.length){case 2:return P9.h(arguments[0],arguments[1]);case 3:return P9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.available_temporal_buckets",P9);P9.h=function(a,b){return $CLJS.Pe($CLJS.p9.l($CLJS.J([a,b])))};P9.j=function(a,b,c){return $CLJS.Pe($CLJS.p9.l($CLJS.J([a,b,c])))};
P9.v=3;var Q9=function Q9(a){switch(arguments.length){case 2:return Q9.h(arguments[0],arguments[1]);case 3:return Q9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.query_EQ_",Q9);Q9.h=function(a,b){return Q9.j(a,b,null)};Q9.j=function(a,b,c){a=K9(a,c);b=K9(b,c);return $CLJS.F.h(a,b)};Q9.v=3;
var R9=function R9(a){switch(arguments.length){case 1:return R9.g(arguments[0]);case 2:return R9.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.aggregation_clause",R9);R9.g=function(a){return $CLJS.k9.l($CLJS.J([a]))};R9.h=function(a,b){return $CLJS.k9.l($CLJS.J([a,b]))};R9.v=2;
var S9=function S9(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return S9.l(arguments[0],arguments[1],2<c.length?new $CLJS.y(c.slice(2),0,null):null)};$CLJS.Ra("metabase.lib.js.filter_clause",S9);S9.l=function(a,b,c){return $CLJS.Q.C($CLJS.Tva,a,b,c)};S9.v=2;S9.B=function(a){var b=$CLJS.C(a),c=$CLJS.D(a);a=$CLJS.C(c);c=$CLJS.D(c);return this.l(b,a,c)};
var T9=function T9(a){switch(arguments.length){case 2:return T9.h(arguments[0],arguments[1]);case 3:return T9.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.expressionable_columns",T9);T9.h=function(a,b){return T9.h(a,b)};T9.j=function(a,b,c){return $CLJS.Pe($CLJS.Lva.l($CLJS.J([a,b,c])))};T9.v=3;
var U9=function U9(a){switch(arguments.length){case 3:return U9.j(arguments[0],arguments[1],arguments[2]);case 4:return U9.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.Ra("metabase.lib.js.with_different_database",U9);U9.j=function(a,b,c){return U9.C(a,b,c,null)};U9.C=function(a,b,c,d){return $CLJS.vwa.l($CLJS.J([a,J9(b,c),$CLJS.ZE(d,$CLJS.J([$CLJS.kk,!0]))]))};U9.v=4;
module.exports={extract_template_tags:L9,filter_operator:function(a,b,c){return $CLJS.Uva.l($CLJS.J([a,b,c]))},binning:function(a){return $CLJS.Ava.l($CLJS.J([a]))},query:function(a,b,c){c=$CLJS.ZE(c,$CLJS.J([$CLJS.kk,!0]));c=$CLJS.m($CLJS.al.g(c))?c:$CLJS.U.j(c,$CLJS.al,$CLJS.GN);c=(0,$CLJS.u7)(c);c=$CLJS.W2.g(c);var d=$CLJS.mF($CLJS.ND);$CLJS.m($CLJS.qF("metabase.lib.js",d))&&$CLJS.rF("metabase.lib.js",d,$CLJS.z_("query map: %s",$CLJS.J([$CLJS.gj.l($CLJS.J([c]))])),null);return $CLJS.Cwa.l($CLJS.J([J9(a,
b),c]))},columns_group_columns:function(a){return $CLJS.Pe($CLJS.Fva.l($CLJS.J([a])))},join_fields:function(a){a=$CLJS.bwa.l($CLJS.J([a]));return a instanceof $CLJS.N?$CLJS.sF(a):$CLJS.Pe(a)},aggregate:function(a,b,c){return $CLJS.vva.l($CLJS.J([a,b,$CLJS.ZE(c,$CLJS.J([$CLJS.kk,!0]))]))},join_conditions:function(a){return $CLJS.Pe($CLJS.awa.l($CLJS.J([a])))},query_EQ_:Q9,temporal_bucket:function(a){return $CLJS.Nwa.l($CLJS.J([a]))},remove_clause:function(a,b,c){return $CLJS.Ewa.l($CLJS.J([a,b,$CLJS.o9.l($CLJS.J([$CLJS.ZE(c,
$CLJS.J([$CLJS.kk,!0]))]))]))},suggested_join_condition:function(a,b,c){return $CLJS.gwa.l($CLJS.J([a,b,c]))},replace_clause:function(a,b,c,d){return $CLJS.Hwa.l($CLJS.J([a,b,$CLJS.o9.l($CLJS.J([$CLJS.ZE(c,$CLJS.J([$CLJS.kk,!0]))])),$CLJS.o9.l($CLJS.J([$CLJS.ZE(d,$CLJS.J([$CLJS.kk,!0]))]))]))},drop_stage:function(a){return $CLJS.Jwa.l($CLJS.J([a]))},join_lhs_display_name:function(a,b,c){return $CLJS.cwa.l($CLJS.J([a,b,c]))},native_extras:function(a){return $CLJS.pn($CLJS.twa.l($CLJS.J([a])))},available_temporal_buckets:P9,
with_binning:function(a,b){return $CLJS.Bva.l($CLJS.J([a,b]))},append_stage:function(a){return $CLJS.Iwa.l($CLJS.J([a]))},join:function(a,b,c){return $CLJS.Wva.l($CLJS.J([a,b,c]))},aggregations:function(a,b){return $CLJS.Pe($CLJS.xva.l($CLJS.J([a,b])))},raw_native_query:function(a){return $CLJS.owa.l($CLJS.J([a]))},filterable_column_operators:function(a){return $CLJS.Pe($CLJS.Sva.l($CLJS.J([a])))},with_temporal_bucket:function(a,b){return $CLJS.Owa.l($CLJS.J([a,b]))},with_join_conditions:function(a,
b){return $CLJS.jwa.l($CLJS.J([a,$CLJS.ZE(b,$CLJS.J([$CLJS.kk,!0]))]))},available_metrics:function(a){return $CLJS.Pe($CLJS.mwa.l($CLJS.J([a])))},with_different_database:U9,with_fields:function(a,b,c){return $CLJS.Nva.l($CLJS.J([a,b,c]))},join_clause:function(a,b){return $CLJS.Xva.l($CLJS.J([a,b]))},aggregation_clause:R9,external_op:function(a){a=$CLJS.Hva.l($CLJS.J([a]));var b=$CLJS.Uf(a);a=$CLJS.M.h(b,$CLJS.VI);var c=$CLJS.M.h(b,$CLJS.Sk);b=$CLJS.M.h(b,$CLJS.pl);return{operator:a,options:$CLJS.pn(c),
args:$CLJS.Pe(b)}},with_join_fields:function(a,b){return $CLJS.hwa.l($CLJS.J([a,"string"===typeof b?$CLJS.Ui.g(b):b]))},available_binning_strategies:O9,expression:function(a,b,c,d){return $CLJS.Jva.l($CLJS.J([a,b,c,d]))},describe_relative_datetime:function(a,b){a="string"===typeof a?$CLJS.Ui.g(a):a;b="string"===typeof b?$CLJS.Ui.g(b):b;return $CLJS.Mwa.l($CLJS.J([a,b]))},order_bys:function(a,b){return $CLJS.Pe($CLJS.Awa.l($CLJS.J([a,b])))},display_info:function(a,b,c){return $CLJS.pn.l($CLJS.Wm.C($CLJS.pF($CLJS.kwa.l($CLJS.J([$CLJS.M3(a,
b),b,c])),$CLJS.ZF),$CLJS.O_,$CLJS.pF,$CLJS.ZF),$CLJS.J([$CLJS.tm,$CLJS.sF]))},fieldable_columns:function(a,b){return $CLJS.Pe($CLJS.Ova.l($CLJS.J([a,b])))},template_tags:function(a){return $CLJS.n9.l($CLJS.J([$CLJS.qwa.l($CLJS.J([a]))]))},selected_aggregation_operators:function(a,b){return $CLJS.Pe($CLJS.zva.l($CLJS.J([$CLJS.A(a),b])))},order_by_clause:N9,filterable_columns:function(a,b){return $CLJS.Pe($CLJS.Rva.l($CLJS.J([a,b])))},join_condition_rhs_columns:function(a,b,c,d){return $CLJS.Pe($CLJS.$va.l($CLJS.J([a,
b,c,d])))},filters:function(a,b){return $CLJS.Pe($CLJS.Qva.l($CLJS.J([a,b])))},join_condition_lhs_columns:function(a,b,c,d){return $CLJS.Pe($CLJS.Yva.l($CLJS.J([a,b,c,d])))},table_or_card_metadata:function(a,b){var c=$CLJS.I_(b);return $CLJS.m(c)?$CLJS.x0(a,c):$CLJS.w0(a,b)},orderable_columns:function(a,b){return $CLJS.Pe($CLJS.Bwa.l($CLJS.J([a,b])))},suggestedName:function(a){return $CLJS.lwa.l($CLJS.J([a]))},metadataProvider:J9,filter_clause:S9,fields:function(a,b){return $CLJS.Pe($CLJS.Mva.l($CLJS.J([a,
b])))},available_aggregation_operators:function(a,b){return $CLJS.Pe($CLJS.yva.l($CLJS.J([a,b])))},breakouts:function(a,b){return $CLJS.Pe($CLJS.Eva.l($CLJS.J([a,b])))},joinable_columns:function(a,b,c){return $CLJS.Pe($CLJS.ewa.l($CLJS.J([a,b,c])))},group_columns:function(a){return $CLJS.Pe($CLJS.Gva.l($CLJS.J([a])))},describe_temporal_unit:function(a,b){b="string"===typeof b?$CLJS.Ui.g(b):b;return $CLJS.Kwa.l($CLJS.J([a,b]))},joins:function(a,b){return $CLJS.Pe($CLJS.fwa.l($CLJS.J([a,b])))},native_query:function(a,
b,c){return $CLJS.nwa.l($CLJS.J([J9(a,b),c]))},available_join_strategies:function(a,b){return $CLJS.Pe($CLJS.Vva.l($CLJS.J([a,b])))},legacy_query:function(a){return $CLJS.pn.l(M9($CLJS.N2.g(a)),$CLJS.J([$CLJS.tm,$CLJS.sF]))},with_native_extras:function(a,b){return $CLJS.uwa.l($CLJS.J([a,$CLJS.ZE(b,$CLJS.J([$CLJS.kk,!0]))]))},join_strategy:function(a){return $CLJS.dwa.l($CLJS.J([a]))},picker_info:function(a,b){var c=$CLJS.wl.g(b);switch(c instanceof $CLJS.N?c.N:null){case "metadata/table":return{databaseId:$CLJS.YP.g(a),
tableId:$CLJS.Lk.g(b)};case "metadata/card":return{databaseId:$CLJS.YP.g(a),tableId:["card__",$CLJS.p.g($CLJS.Lk.g(b))].join(""),cardId:$CLJS.Lk.g(b),isModel:$CLJS.jpa.g(b)};default:return a=$CLJS.mF($CLJS.PD),$CLJS.m($CLJS.qF("metabase.lib.js",a))&&$CLJS.rF("metabase.lib.js",a,$CLJS.MB.l($CLJS.J(["Cannot provide picker-info for",$CLJS.wl.g(b)])),null),null}},aggregation_operator_columns:function(a){return $CLJS.Pe($CLJS.wva.l($CLJS.J([a])))},join_condition_operators:function(a,b,c,d){return $CLJS.Pe($CLJS.Zva.l($CLJS.J([a,
b,c,d])))},expressionable_columns:T9,filter:function(a,b,c){return $CLJS.Pva.l($CLJS.J([a,b,$CLJS.ZE(c,$CLJS.J([$CLJS.kk,!0]))]))},change_direction:function(a,b){return $CLJS.xwa.l($CLJS.J([a,b]))},with_template_tags:function(a,b){return $CLJS.rwa.l($CLJS.J([a,$CLJS.m9.l($CLJS.J([b]))]))},expressions:function(a,b){return $CLJS.Pe($CLJS.Kva.l($CLJS.J([a,b])))},with_join_strategy:function(a,b){return $CLJS.iwa.l($CLJS.J([a,b]))},order_by:function(a,b,c,d){return $CLJS.ywa.l($CLJS.J([a,b,c,$CLJS.Ui.g(d)]))},
describe_temporal_interval:function(a,b){a="string"===typeof a?$CLJS.Ui.g(a):a;b="string"===typeof b?$CLJS.Ui.g(b):b;return $CLJS.Lwa.l($CLJS.J([a,b]))},breakout:function(a,b,c){return $CLJS.Cva.l($CLJS.J([a,b,$CLJS.Dwa.l($CLJS.J([c]))]))},database_id:function(a){return $CLJS.Iva.l($CLJS.J([a]))},required_native_extras:function(a,b){return $CLJS.Pe($CLJS.swa.l($CLJS.J([J9(a,b)])))},remove_join:function(a,b,c){return $CLJS.Fwa.l($CLJS.J([a,b,c]))},joined_thing:function(a,b){return $CLJS.n8(a,b)},with_native_query:function(a,
b){return $CLJS.pwa.l($CLJS.J([a,b]))},breakoutable_columns:function(a,b){return $CLJS.Pe($CLJS.Dva.l($CLJS.J([a,b])))},rename_join:function(a,b,c,d){return $CLJS.Gwa.l($CLJS.J([a,b,c,d]))}};