var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./inflections.core.js");require("./medley.core.js");require("./metabase.lib.common.js");require("./metabase.lib.dispatch.js");require("./metabase.lib.equality.js");require("./metabase.lib.filter.js");require("./metabase.lib.filter.operator.js");require("./metabase.lib.hierarchy.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.options.js");require("./metabase.lib.query.js");require("./metabase.lib.ref.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.expression.js");require("./metabase.lib.schema.filter.js");require("./metabase.lib.schema.join.js");require("./metabase.lib.types.isa.js");require("./metabase.lib.util.js");require("./metabase.mbql.util.match.js");require("./metabase.shared.util.i18n.js");require("./metabase.util.js");require("./metabase.util.malli.js");
'use strict';var ara,bra,cra,dra,era;ara=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;c=arguments[0];d=arguments[1];var e=arguments[2];b=3<b.length?new $CLJS.y(b.slice(3),0,null):null;return $CLJS.Fb($CLJS.A($CLJS.vu(c,d)))?c:$CLJS.Q.S($CLJS.RZ,c,d,e,b)};
$CLJS.C3=function(a){var b=$CLJS.LG(a);b=b instanceof $CLJS.N?b.N:null;switch(b){case "dispatch-type/nil":return null;case "field":return $CLJS.yP.g($CLJS.HK(a));case "metadata/column":return $CLJS.B3.g(a);case "mbql/join":return $CLJS.qI.g(a);default:throw Error(["No matching clause: ",$CLJS.p.g(b)].join(""));}};
bra=function(a,b){return $CLJS.m($CLJS.AH.g(a))?$CLJS.Wm.j(a,$CLJS.AH,function(c){return $CLJS.ne(c)?$CLJS.Vm.h(function(d){return $CLJS.D3.h?$CLJS.D3.h(d,b):$CLJS.D3.call(null,d,b)},c):c}):a};
$CLJS.E3=function(a){var b=$CLJS.Ag;a:try{if($CLJS.qe(a)&&4===$CLJS.E(a))try{if($CLJS.G(a,0)instanceof $CLJS.N)try{var c=$CLJS.G(a,2);if($CLJS.qe(c)&&3===$CLJS.E(c))try{var d=$CLJS.G(c,0);if($CLJS.O(d,$CLJS.PP))try{var e=$CLJS.G(a,3);if($CLJS.qe(e)&&3===$CLJS.E(e))try{var f=$CLJS.G(e,0);if($CLJS.O(f,$CLJS.PP)){$CLJS.G(e,1);$CLJS.G(e,2);$CLJS.G(c,1);$CLJS.G(c,2);$CLJS.G(a,0);$CLJS.G(a,1);var g=new $CLJS.R(null,1,5,$CLJS.S,[!0],null)}else throw $CLJS.Z;}catch(n){if(n instanceof Error){var l=n;if(l===
$CLJS.Z)throw $CLJS.Z;throw l;}throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=n;if(l===$CLJS.Z)throw $CLJS.Z;throw l;}throw n;}else throw $CLJS.Z;}catch(n){if(n instanceof Error){l=
n;if(l===$CLJS.Z){g=new $CLJS.R(null,1,5,$CLJS.S,[!1],null);break a}throw l;}throw n;}return $CLJS.C($CLJS.A(b($CLJS.Gb,g)))};$CLJS.F3=function(a,b){var c=$CLJS.D3;if($CLJS.Fb($CLJS.E3(a)))return a;var d=$CLJS.K(a,0,null),e=$CLJS.K(a,1,null),f=$CLJS.K(a,2,null);a=$CLJS.K(a,3,null);return new $CLJS.R(null,4,5,$CLJS.S,[d,e,f,$CLJS.Q.j(c,a,b)],null)};
cra=function(a,b,c){return $CLJS.je($CLJS.BY.g(a))?a:$CLJS.m(b)?ara(a,new $CLJS.R(null,1,5,$CLJS.S,[$CLJS.BY],null),function(d){return function l(f,g){try{if($CLJS.qe(g)&&3===$CLJS.E(g))try{var n=$CLJS.G(g,0);if($CLJS.O(n,$CLJS.PP))try{var q=$CLJS.G(g,1);if(null!=q?q.D&256||$CLJS.t===q.He||(q.D?0:$CLJS.Mb($CLJS.kc,q)):$CLJS.Mb($CLJS.kc,q))try{var u=$CLJS.M.j(q,$CLJS.yP,$CLJS.lP);if($CLJS.F.h(u,b))return $CLJS.G(g,2),$CLJS.D3.h?$CLJS.D3.h(g,c):$CLJS.D3.call(null,g,c);throw $CLJS.Z;}catch(x){if(x instanceof
Error){var v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)throw $CLJS.Z;throw v;}throw x;}else throw $CLJS.Z;}catch(x){if(x instanceof Error){v=x;if(v===$CLJS.Z)return $CLJS.FZ(l,f,g);throw v;}throw x;}}($CLJS.Rg,d)}):$CLJS.Wm.j(a,$CLJS.BY,function(d){return $CLJS.Vm.h(function(e){return $CLJS.F3(e,$CLJS.J([c]))},d)})};
$CLJS.D3=function(a,b){var c=$CLJS.LG(a);c=c instanceof $CLJS.N?c.N:null;switch(c){case "field":return $CLJS.tV(a,$CLJS.sV,$CLJS.J([$CLJS.yP,b]));case "metadata/column":return $CLJS.sV(a,$CLJS.B3,b);case "mbql/join":return c=$CLJS.C3(a),cra(bra($CLJS.sV(a,$CLJS.qI,b),b),c,b);default:throw Error(["No matching clause: ",$CLJS.p.g(c)].join(""));}};$CLJS.G3=function(a,b){return $CLJS.xa.j?$CLJS.xa.j("%s__%s",a,b):$CLJS.xa.call(null,"%s__%s",a,b)};
$CLJS.H3=function(a,b,c){var d=$CLJS.U.l,e=$CLJS.Tm.h($CLJS.T_,$CLJS.V)(c);a=$CLJS.G3($CLJS.qI.g(a),$CLJS.Tm.h($CLJS.T_,$CLJS.V)(c));b=b.g?b.g(a):b.call(null,a);return d.call($CLJS.U,c,$CLJS.T_,e,$CLJS.J([$CLJS.$_,b]))};dra={};$CLJS.I3=new $CLJS.N(null,"fk","fk",398442651);$CLJS.B3=new $CLJS.N("metabase.lib.join","join-alias","metabase.lib.join/join-alias",1166233023);$CLJS.J3=new $CLJS.N(null,"pk","pk",-771936732);
era=new $CLJS.w("metabase.lib.stage","ensure-previous-stages-have-metadata","metabase.lib.stage/ensure-previous-stages-have-metadata",2048342183,null);$CLJS.K3=new $CLJS.N(null,"fk-target-field-id","fk-target-field-id",2019750287);$CLJS.L3=new $CLJS.N("metabase.lib.join","ref","metabase.lib.join/ref",950805898);var gra,hra,ira,jra,kra;$CLJS.V0.o(null,$CLJS.tY,function(a,b,c){b=$CLJS.Uf(c);b=$CLJS.M.h(b,$CLJS.yY);b=$CLJS.K(b,0,null);c=$CLJS.Uf(b);b=$CLJS.M.h(c,$CLJS.kP);c=$CLJS.M.h(c,$CLJS.XY);a=$CLJS.m(b)?$CLJS.YH.g($CLJS.w0(a,b)):null;if($CLJS.m(a))return a;a=$CLJS.m(c)?$CLJS.aH("Question {0}",$CLJS.J([c])):null;return $CLJS.m(a)?a:$CLJS.bH("Native Query")});$CLJS.a1.o(null,$CLJS.tY,function(a,b,c){a=$CLJS.z0.j(a,b,c);c=$CLJS.qI.g(c);return new $CLJS.k(null,2,[$CLJS.V,$CLJS.m(c)?c:a,$CLJS.YH,a],null)});
$CLJS.y0.o(null,$CLJS.tY,function(){throw $CLJS.Ej("You can't calculate a metadata map for a join! Use lib.metadata.calculation/returned-columns-method instead.",$CLJS.P);});
$CLJS.V0.o(null,$CLJS.CY,function(a,b,c){a=$CLJS.Uf(c);a=$CLJS.M.h(a,$CLJS.dK);a=a instanceof $CLJS.N?a.N:null;switch(a){case "left-join":return $CLJS.bH("Left outer join");case "right-join":return $CLJS.bH("Right outer join");case "inner-join":return $CLJS.bH("Inner join");case "full-join":return $CLJS.bH("Full outer join");default:throw Error(["No matching clause: ",$CLJS.p.g(a)].join(""));}});
$CLJS.a1.o(null,$CLJS.CY,function(a,b,c){var d=$CLJS.Uf(c),e=$CLJS.M.h(d,$CLJS.dK);c=$CLJS.M.h(d,$CLJS.Uj);a=new $CLJS.k(null,2,[$CLJS.T0,$CLJS.sF(e),$CLJS.YH,$CLJS.z0.j(a,b,d)],null);return $CLJS.m(c)?$CLJS.U.j(a,$CLJS.Uj,!0):a});
$CLJS.b1.o(null,$CLJS.tY,function(a,b,c,d){var e=$CLJS.Uf(c),f=$CLJS.M.h(e,$CLJS.qI),g=$CLJS.M.j(e,$CLJS.AH,$CLJS.Lu),l=$CLJS.M.h(e,$CLJS.yY);c=$CLJS.Uf(d);var n=$CLJS.M.h(c,$CLJS.R0);if($CLJS.F.h(g,$CLJS.Lu))return null;var q="undefined"!==typeof $CLJS.sN&&"undefined"!==typeof dra&&"undefined"!==typeof $CLJS.fra&&"undefined"!==typeof $CLJS.M3?new $CLJS.ud(function(){return $CLJS.M3},$CLJS.fe(era,new $CLJS.k(null,1,[$CLJS.Vl,!0],null)),null):null,u=function(){var v=$CLJS.U.j(a,$CLJS.yY,l);return $CLJS.m(q)?
q.h?q.h(v,-1):q.call(null,v,-1):v}();c=$CLJS.F.h(g,$CLJS.ID)?$CLJS.y3(u,-1,$CLJS.he(l),c):function(){return function z(x){return new $CLJS.Af(null,function(){for(;;){var B=$CLJS.A(x);if(B){if($CLJS.re(B)){var H=$CLJS.$c(B),I=$CLJS.E(H),T=$CLJS.Df(I);a:for(var W=0;;)if(W<I){var ba=$CLJS.be(H,W);ba=$CLJS.tV(ba,$CLJS.Jm,$CLJS.J([$CLJS.yP]));ba=$CLJS.y0.j(u,-1,ba);T.add(ba);W+=1}else{H=!0;break a}return H?$CLJS.If($CLJS.Kf(T),z($CLJS.ad(B))):$CLJS.If($CLJS.Kf(T),null)}T=$CLJS.C(B);T=$CLJS.tV(T,$CLJS.Jm,
$CLJS.J([$CLJS.yP]));return $CLJS.pf($CLJS.y0.j(u,-1,T),z($CLJS.zd(B)))}return null}},null,null)}(g)}();return $CLJS.Vm.h(function(v){v=$CLJS.U.j(v,$CLJS.g0,f);v=$CLJS.D3($CLJS.U.l(v,$CLJS.YH,$CLJS.z0.j(a,b,v),$CLJS.J([$CLJS.J_,$CLJS.Z_])),f);return $CLJS.H3(e,n,v)},c)});$CLJS.c1.o(null,$CLJS.tY,function(a,b,c,d){return $CLJS.y3(a,b,$CLJS.U.j(c,$CLJS.AH,$CLJS.ID),d)});gra=$CLJS.ij.g($CLJS.P);hra=$CLJS.ij.g($CLJS.P);ira=$CLJS.ij.g($CLJS.P);jra=$CLJS.ij.g($CLJS.P);
kra=$CLJS.M.j(new $CLJS.k(null,1,[$CLJS.Vk,$CLJS.MG],null),$CLJS.Vk,$CLJS.rj.A?$CLJS.rj.A():$CLJS.rj.call(null));$CLJS.N3=new $CLJS.Aj($CLJS.$i.h("metabase.lib.join","join-clause-method"),$CLJS.LG,$CLJS.Uj,kra,gra,hra,ira,jra);$CLJS.N3.o(null,$CLJS.tY,function(a){return a});$CLJS.N3.o(null,$CLJS.lZ,function(a){return $CLJS.vV(new $CLJS.k(null,2,[$CLJS.wl,$CLJS.tY,$CLJS.yY,$CLJS.yY.g($CLJS.H_(a))],null))});
$CLJS.N3.o(null,$CLJS.bZ,function(a){return $CLJS.vV(new $CLJS.k(null,2,[$CLJS.wl,$CLJS.tY,$CLJS.yY,new $CLJS.R(null,1,5,$CLJS.S,[a],null)],null))});