var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.shared.formatting.constants.js");require("./metabase.shared.formatting.internal.date_builder.js");require("./metabase.shared.formatting.internal.date_formatters.js");require("./metabase.shared.formatting.internal.date_options.js");require("./metabase.shared.util.time.js");
'use strict';var O$,Cxa,Dxa,Exa,Fxa,P$,Gxa,Hxa,Ixa,R$,Jxa,Kxa;O$=function(a){a=$CLJS.Uf(a);a=$CLJS.M.h(a,$CLJS.o$);return $CLJS.F.h(a,"compact")};
Cxa=function(a,b){return $CLJS.m(b)?function e(d){return new $CLJS.Af(null,function(){for(;;){var f=$CLJS.A(d);if(f){if($CLJS.re(f)){var g=$CLJS.$c(f),l=$CLJS.E(g),n=$CLJS.Df(l);a:for(var q=0;;)if(q<l){var u=$CLJS.be(g,q);u="string"===typeof u?$CLJS.zu(u,/\//,b):u;n.add(u);q+=1}else{g=!0;break a}return g?$CLJS.If($CLJS.Kf(n),e($CLJS.ad(f))):$CLJS.If($CLJS.Kf(n),null)}n=$CLJS.C(f);return $CLJS.pf("string"===typeof n?$CLJS.zu(n,/\//,b):n,e($CLJS.zd(f)))}return null}},null,null)}(a):a};
Dxa=function(a){return function d(c){return new $CLJS.Af(null,function(){for(;;){var e=$CLJS.A(c);if(e){if($CLJS.re(e)){var f=$CLJS.$c(e),g=$CLJS.E(f),l=$CLJS.Df(g);return function(){for(var q=0;;)if(q<g){var u=$CLJS.be(f,q),v=l,x=u;u=$CLJS.F.h($CLJS.X9,x)?$CLJS.Z9:$CLJS.F.h(":month-full",x)?$CLJS.Z9:$CLJS.F.h($CLJS.k$,x)?$CLJS.g$:$CLJS.F.h(":day-of-week-full",x)?$CLJS.g$:u;v.add(u);q+=1}else return!0}()?$CLJS.If($CLJS.Kf(l),d($CLJS.ad(e))):$CLJS.If($CLJS.Kf(l),null)}var n=$CLJS.C(e);return $CLJS.pf(function(){var q=
n;return $CLJS.F.h($CLJS.X9,q)?$CLJS.Z9:$CLJS.F.h(":month-full",q)?$CLJS.Z9:$CLJS.F.h($CLJS.k$,q)?$CLJS.g$:$CLJS.F.h(":day-of-week-full",q)?$CLJS.g$:n}(),d($CLJS.zd(e)))}return null}},null,null)}(a)};
Exa=function(a){var b=$CLJS.Uf(a),c=$CLJS.M.h(b,$CLJS.m$);a=$CLJS.M.h(b,$CLJS.aF);b=$CLJS.M.h(b,$CLJS.bk);if($CLJS.m(c))return c;c=$CLJS.vu($CLJS.z$,new $CLJS.R(null,2,5,$CLJS.S,[a,b],null));if($CLJS.m(c))return c;c=$CLJS.M.h($CLJS.wxa,b);if($CLJS.m(c))return c;c=$CLJS.M.h($CLJS.p$,a);if($CLJS.m(c))return c;c=$CLJS.mF($CLJS.PD);$CLJS.m($CLJS.qF("metabase.shared.formatting.internal.date-formatters",c))&&$CLJS.rF("metabase.shared.formatting.internal.date-formatters",c,$CLJS.MB.l($CLJS.J(["Unrecognized date style",
new $CLJS.k(null,2,[$CLJS.aF,a,$CLJS.bk,b],null)])),null);return $CLJS.C$};Fxa=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.h(a,$CLJS.vxa),c=$CLJS.M.h(a,$CLJS.bF);var d=$CLJS.Uf(a);var e=$CLJS.M.h(d,$CLJS.m$);d=$CLJS.mn.l($CLJS.J([d,$CLJS.M.h($CLJS.r$,e)]));d=Exa(d);b=$CLJS.m(b)?Cxa(d,b):d;c=$CLJS.m(c)?$CLJS.wg.h(new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.g$,", "],null),b):b;return O$(a)?Dxa(c):c};P$=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.h(a,$CLJS.al);return O$(a)&&$CLJS.qi.h(b,"tooltip")};
Gxa=function(a){var b=$CLJS.Uf(a);a=$CLJS.M.h(b,$CLJS.cF);var c=$CLJS.M.h(b,$CLJS.n$),d=$CLJS.M.h(b,$CLJS.dF);a:{var e="string"===typeof c;if(e){e=$CLJS.M.h($CLJS.q$,c);if($CLJS.m(e)){b=e;break a}throw $CLJS.Ej("Unknown time format",b);}b=e}if($CLJS.m(b))return b;if($CLJS.m(c))return c;c=$CLJS.vu($CLJS.zxa,new $CLJS.R(null,2,5,$CLJS.S,[d,a],null));if($CLJS.m(c))return c;c=$CLJS.M.h($CLJS.q$,d);if($CLJS.m(c))return c;c=$CLJS.mF($CLJS.PD);$CLJS.m($CLJS.qF("metabase.shared.formatting.internal.date-formatters",
c))&&$CLJS.rF("metabase.shared.formatting.internal.date-formatters",c,$CLJS.MB.l($CLJS.J(["Unrecognized time style",new $CLJS.k(null,2,[$CLJS.dF,d,$CLJS.cF,a],null)])),null);return $CLJS.Axa};
Hxa=function(a){var b=$CLJS.Uf(a);a=$CLJS.M.h(b,$CLJS.eF);var c=$CLJS.M.h(b,$CLJS.cF),d=$CLJS.m(a)?Fxa(b):null,e=$CLJS.m(c)?Gxa(b):null;a=$CLJS.m($CLJS.m(d)?e:d)?$CLJS.wg.l(d,new $CLJS.R(null,1,5,$CLJS.S,[", "],null),$CLJS.J([e])):function(){if($CLJS.m(d))return d;if($CLJS.m(e))return e;var f=$CLJS.mF($CLJS.PD);$CLJS.m($CLJS.qF("metabase.shared.formatting.internal.date-formatters",f))&&$CLJS.rF("metabase.shared.formatting.internal.date-formatters",f,$CLJS.MB.l($CLJS.J(["Unrecognized date/time format",
b])),null);return $CLJS.C$}();return $CLJS.x$(a)};Ixa=function(a){var b=$CLJS.M.h($CLJS.r($CLJS.J$),a);return $CLJS.m(b)?b:$CLJS.M.h($CLJS.jj.h($CLJS.J$,function(c){return $CLJS.Ie(c,a)?c:$CLJS.U.j(c,a,Hxa(a))}),a)};
$CLJS.Q$=function(a){a=$CLJS.Wm.j($CLJS.xF(a),$CLJS.bk,$CLJS.Ui);var b=$CLJS.mn.l;var c=$CLJS.bk.g(a);c=$CLJS.L$.g?$CLJS.L$.g(c):$CLJS.L$.call(null,c);a=b.call($CLJS.mn,$CLJS.J([$CLJS.Bxa,$CLJS.m(c)?new $CLJS.k(null,1,[$CLJS.cF,"minutes"],null):null,a]));var d=$CLJS.Uf(a);b=$CLJS.M.h(d,$CLJS.TF);c=$CLJS.M.h(d,$CLJS.K$);var e=$CLJS.M.h(d,$CLJS.al);a=$CLJS.M.h(d,$CLJS.bk);d=$CLJS.Jm.l(d,$CLJS.TF,$CLJS.J([$CLJS.K$]));d=$CLJS.m($CLJS.N$.g?$CLJS.N$.g(a):$CLJS.N$.call(null,a))?$CLJS.U.j(d,$CLJS.eF,!1):
d;e=$CLJS.F.h(e,"tooltip")?$CLJS.U.j(d,$CLJS.o$,"condensed"):d;b=$CLJS.m($CLJS.m(b)?b:c)?$CLJS.U.j(e,$CLJS.o$,"compact"):e;return $CLJS.Fb($CLJS.M$.g?$CLJS.M$.g(a):$CLJS.M$.call(null,a))?$CLJS.Jm.h(b,$CLJS.bF):b};
R$=function(a,b){b=$CLJS.Q$(b);var c=$CLJS.w5.h(a,b);if($CLJS.m($CLJS.v5.l($CLJS.J([c])))){c=$CLJS.u5.l($CLJS.J([c,b]));a=$CLJS.K(c,0,null);c=$CLJS.K(c,1,null);var d=$CLJS.Uf(b);d=$CLJS.M.h(d,$CLJS.o$);var e=new $CLJS.ti(null,new $CLJS.k(null,2,["compact",null,"condensed",null],null),null);d=e.g?e.g(d):e.call(null,d);$CLJS.Fb(d)||$CLJS.Fb($CLJS.Fsa.l($CLJS.J([a,c])))?(b=P$(b)?$CLJS.F$:$CLJS.G$,b=[$CLJS.p.g(b(a))," – ",$CLJS.p.g(b(c))].join("")):b=$CLJS.Fb($CLJS.Esa.l($CLJS.J([a,c])))?[$CLJS.p.g((P$(b)?
$CLJS.D$:$CLJS.E$)(a))," – ",$CLJS.p.g((P$(b)?$CLJS.F$:$CLJS.G$)(c))].join(""):[$CLJS.p.g((P$(b)?$CLJS.D$:$CLJS.E$)(a))," – ",$CLJS.p.g($CLJS.x$(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Y9,", ",$CLJS.Oj],null))(c))].join("")}else b=$CLJS.p.g(a);return b};
$CLJS.S$=function(a,b){b=$CLJS.Q$(b);var c=$CLJS.Uf(b),d=$CLJS.M.h(c,Jxa),e=$CLJS.M.h(c,Kxa),f=$CLJS.M.h(c,$CLJS.al),g=$CLJS.M.h(c,$CLJS.bk);b=$CLJS.w5.h(a,c);if($CLJS.m(d))switch(g instanceof $CLJS.N?g.N:null){case "hour-of-day":return(0,$CLJS.xxa)(b);case "day-of-week":return(0,$CLJS.yxa)(b);default:throw $CLJS.Ej("is-exclude option is only compatible with hour-of-day and day-of-week units",new $CLJS.k(null,1,[$CLJS.Sk,c],null));}else{(d=$CLJS.F.h(g,$CLJS.cl))?(d=new $CLJS.ti(null,new $CLJS.k(null,
2,["tooltip",null,"cell",null],null),null),f=d.g?d.g(f):d.call(null,f),e=$CLJS.m(f)?$CLJS.Fb(e):f):e=d;if($CLJS.m(e))return R$(a,c);a=Ixa(c);return a.g?a.g(b):a.call(null,b)}};Jxa=new $CLJS.N(null,"is-exclude","is-exclude",1738462979);Kxa=new $CLJS.N(null,"no-range","no-range",-1511420040);var T$=new $CLJS.k(null,3,[$CLJS.ol,$CLJS.x$(new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Oj,"-",$CLJS.c$],null)),$CLJS.Yj,$CLJS.x$(new $CLJS.R(null,4,5,$CLJS.S,["Q",$CLJS.Yj,"-",$CLJS.Oj],null)),$CLJS.oz,$CLJS.H$],null);
module.exports={format_for_parameter:function(a,b){b=$CLJS.Q$(b);var c=$CLJS.w5.h(a,b);if($CLJS.Fb($CLJS.v5.l($CLJS.J([c]))))return $CLJS.p.g(a);a=$CLJS.bk.g(b);a=T$.g?T$.g(a):T$.call(null,a);if($CLJS.m(a))return a.g?a.g(c):a.call(null,c);c=$CLJS.u5.l($CLJS.J([c,b]));b=$CLJS.K(c,0,null);c=$CLJS.K(c,1,null);return $CLJS.m($CLJS.Dsa.l($CLJS.J([b,c])))?(0,$CLJS.H$)(b):[$CLJS.p.g((0,$CLJS.H$)(b)),"~",$CLJS.p.g((0,$CLJS.H$)(c))].join("")},format_range_with_unit:R$,format_datetime_with_unit:$CLJS.S$};