var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./medley.core.js");require("./metabase.lib.aggregation.js");require("./metabase.lib.binning.js");require("./metabase.lib.card.js");require("./metabase.lib.equality.js");require("./metabase.lib.expression.js");require("./metabase.lib.join.js");require("./metabase.lib.metadata.js");require("./metabase.lib.metadata.calculation.js");require("./metabase.lib.normalize.js");require("./metabase.lib.options.js");require("./metabase.lib.ref.js");require("./metabase.lib.schema.js");require("./metabase.lib.schema.common.js");require("./metabase.lib.schema.id.js");require("./metabase.lib.schema.ref.js");require("./metabase.lib.schema.temporal_bucketing.js");require("./metabase.lib.temporal_bucket.js");require("./metabase.lib.util.js");require("./metabase.shared.util.i18n.js");require("./metabase.shared.util.time.js");require("./metabase.util.js");require("./metabase.util.humanization.js");require("./metabase.util.log.js");require("./metabase.util.malli.js");
'use strict';var Hsa,B5,Isa,Jsa,Ksa,Lsa,Msa,Nsa,F5,G5,I5,L5,M5,Osa,Psa;$CLJS.x5=function(a,b){a=$CLJS.r0(a,b);return 0<a?a-1:null};$CLJS.y5=function(a,b,c,d){d=$CLJS.mn.l($CLJS.J([$CLJS.mn.l($CLJS.J([new $CLJS.k(null,1,[$CLJS.R0,$CLJS.G2()],null),new $CLJS.k(null,3,[$CLJS.P0,!0,$CLJS.U0,!0,$CLJS.M0,!0],null)])),d]));return $CLJS.c1.C(a,b,c,d)};$CLJS.z5=function(a,b,c){return $CLJS.y5(a,b,c,null)};
Hsa=function(a){var b=new $CLJS.k(null,2,[$CLJS.EK,$CLJS.p.g($CLJS.IK()),$CLJS.qk,$CLJS.Tm.h($CLJS.qk,$CLJS.LF)(a)],null);a=$CLJS.L1.g(a);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.ZO,b,a],null)};$CLJS.A5=function(a){return $CLJS.S4.g(a)};B5=function(a,b){return $CLJS.F.h($CLJS.i4.g(a),$CLJS.ri(b,new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.dK,$CLJS.IH,$CLJS.aK],null)))};Isa=function(a,b){b=$CLJS.x0(a,b);return $CLJS.m(b)?$CLJS.c5(a,b):null};
Jsa=function(a){var b=new $CLJS.k(null,3,[$CLJS.EK,$CLJS.p.g($CLJS.IK()),$CLJS.LF,$CLJS.LF.g(a),$CLJS.qk,$CLJS.Tm.h($CLJS.qk,$CLJS.LF)(a)],null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.IF,b,$CLJS.V.g(a)],null)};Ksa=function(a){return $CLJS.t3(a,new $CLJS.k(null,1,[$CLJS.dK,$CLJS.Ui],null))};
Lsa=function(a,b,c){var d=$CLJS.mn.l;b=$CLJS.Fb($CLJS.x5(a,b))?function(){var f=$CLJS.XY.g($CLJS.C($CLJS.yY.g(a)));return $CLJS.m(f)?(f=Isa(a,f),$CLJS.m(f)?$CLJS.LV(function(g){return $CLJS.F.h($CLJS.Lk.g(g),c)},f):null):null}():null;try{var e=$CLJS.x3(a,c)}catch(f){e=null}return d.call($CLJS.mn,$CLJS.J([b,e]))};
Msa=function(a,b){var c=$CLJS.LV(function(d){return $CLJS.F.h($CLJS.$_.g(d),a)},b);if($CLJS.m(c))return c;c=$CLJS.LV(function(d){return $CLJS.F.h($CLJS.V.g(d),a)},b);if($CLJS.m(c))return c;c=$CLJS.mF($CLJS.PD);$CLJS.m($CLJS.qF("metabase.lib.field",c))&&(b=$CLJS.aH("Invalid :field clause: column {0} does not exist. Found: {1}",$CLJS.J([$CLJS.gj.l($CLJS.J([a])),$CLJS.gj.l($CLJS.J([$CLJS.Vm.h($CLJS.$_,b)]))])),b instanceof Error?$CLJS.rF("metabase.lib.field",c,$CLJS.MB(),b):$CLJS.rF("metabase.lib.field",
c,$CLJS.MB.l($CLJS.J([b])),null));return null};
Nsa=function(a,b,c){var d=$CLJS.x5(a,b),e=$CLJS.m(d)?$CLJS.s0(a,d):$CLJS.s0(a,b),f=function(){var l=$CLJS.C5.g(e);if($CLJS.m(l))return l;l=$CLJS.vu(e,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.SY,$CLJS.G_],null));if($CLJS.m(l))return l;l=$CLJS.m($CLJS.XY.g(e))?$CLJS.z5(a,b,e):null;if($CLJS.m(l))return l;l=$CLJS.mF($CLJS.PD);if($CLJS.m($CLJS.qF("metabase.lib.field",l))){var n=$CLJS.aH("Cannot resolve column {0}: stage has no metadata",$CLJS.J([$CLJS.gj.l($CLJS.J([c]))]));return n instanceof Error?$CLJS.rF("metabase.lib.field",
l,$CLJS.MB(),n):$CLJS.rF("metabase.lib.field",l,$CLJS.MB.l($CLJS.J([n])),null)}return null}(),g=function(){var l=$CLJS.A(f);return l?Msa(c,f):l}();return $CLJS.m(g)?$CLJS.m(d)?$CLJS.U.j($CLJS.U.j($CLJS.D3($CLJS.Jm.l(g,$CLJS.Lk,$CLJS.J([$CLJS.N_,$CLJS.D5,$CLJS.E5])),null),$CLJS.V,function(){var l=$CLJS.$_.g(g);return $CLJS.m(l)?l:$CLJS.V.g(g)}()),$CLJS.J_,$CLJS.U_):g:null};
F5=function(a,b,c){$CLJS.K(c,0,null);var d=$CLJS.K(c,1,null),e=$CLJS.Uf(d);d=$CLJS.M.h(e,$CLJS.yP);var f=$CLJS.K(c,2,null);c=$CLJS.mn.l($CLJS.J([function(){var g=$CLJS.LF.g(e);return $CLJS.m(g)?new $CLJS.k(null,1,[$CLJS.LF,g],null):null}(),function(){var g=$CLJS.Tm.h($CLJS.qk,$CLJS.LF)(e);return $CLJS.m(g)?new $CLJS.k(null,1,[$CLJS.qk,g],null):null}(),function(){var g=$CLJS.bR.g(e);return $CLJS.m(g)?new $CLJS.k(null,1,[$CLJS.D5,g],null):null}(),function(){var g=$CLJS.bQ.g(e);return $CLJS.m(g)?new $CLJS.k(null,
1,[$CLJS.E5,g],null):null}(),$CLJS.Ae(f)?Lsa(a,b,f):$CLJS.m(d)?new $CLJS.k(null,2,[$CLJS.wl,$CLJS.xV,$CLJS.V,f],null):function(){var g=Nsa(a,b,f);return $CLJS.m(g)?g:new $CLJS.k(null,2,[$CLJS.wl,$CLJS.xV,$CLJS.V,f],null)}()]));return $CLJS.m(d)?$CLJS.D3(c,d):c};G5=function(a){a=$CLJS.Uf(a);var b=$CLJS.M.h(a,$CLJS.E5);return $CLJS.m($CLJS.m(b)?$CLJS.Ie($CLJS.kV,b):b)?$CLJS.nl:$CLJS.Tm.h($CLJS.qk,$CLJS.LF)(a)};
$CLJS.H5=function(a,b){return"string"===typeof b?$CLJS.x0(a,$CLJS.I_(b)):$CLJS.Ae(b)?$CLJS.w0(a,b):null};I5=function(a,b,c){return $CLJS.m($CLJS.ag(function(d){return $CLJS.F.h($CLJS.bk.g(d),c)},a))?$CLJS.Vm.h(function(d){var e=$CLJS.Jm.h(d,b);return $CLJS.F.h($CLJS.bk.g(d),c)?$CLJS.U.j(e,b,!0):e},a):a};
$CLJS.J5=function J5(a){switch(arguments.length){case 2:return J5.h(arguments[0],arguments[1]);case 3:return J5.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.J5.h=function(a,b){return $CLJS.J5.j(a,-1,b)};$CLJS.J5.j=function(a,b,c){return $CLJS.P1.j(a,b,c)};$CLJS.J5.v=3;
$CLJS.K5=function K5(a){switch(arguments.length){case 2:return K5.h(arguments[0],arguments[1]);case 3:return K5.j(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$CLJS.p.g(arguments.length)].join(""));}};$CLJS.K5.h=function(a,b){return $CLJS.K5.j(a,-1,b)};$CLJS.K5.j=function(a,b,c){return $CLJS.T4.j(a,b,c)};$CLJS.K5.v=3;$CLJS.E5=new $CLJS.N("metabase.lib.field","temporal-unit","metabase.lib.field/temporal-unit",602312727);
L5=new $CLJS.N(null,"parent-id","parent-id",-1400729131);$CLJS.C5=new $CLJS.N("metabase.lib.stage","cached-metadata","metabase.lib.stage/cached-metadata",-1406479151);M5=new $CLJS.N("metabase.lib.field","original-effective-type","metabase.lib.field/original-effective-type",34164372);Osa=new $CLJS.N(null,"earliest","earliest",-1928154382);$CLJS.D5=new $CLJS.N("metabase.lib.field","binning","metabase.lib.field/binning",-222751823);Psa=new $CLJS.N(null,"latest","latest",24323665);$CLJS.u3.o(null,$CLJS.PP,function(a){var b=$CLJS.K(a,0,null),c=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.Ui.g(b),$CLJS.t3(c,new $CLJS.k(null,2,[$CLJS.bQ,$CLJS.Ui,$CLJS.bR,Ksa],null)),a],null)});var N5=function N5(a,b){var d=$CLJS.x3(a,L5.g(b));a=$CLJS.m(L5.g(d))?N5.h?N5.h(a,d):N5.call(null,a,d):d;a=$CLJS.Uf(a);var e=$CLJS.M.h(a,$CLJS.V);return $CLJS.Wm.j(b,$CLJS.V,function(f){return[$CLJS.p.g(e),".",$CLJS.p.g(f)].join("")})};
$CLJS.Z0.o(null,$CLJS.xV,function(a,b,c){return G5(c)});$CLJS.Z0.o(null,$CLJS.PP,function(a,b,c){$CLJS.K(c,0,null);var d=$CLJS.K(c,1,null);d=$CLJS.Uf(d);d=$CLJS.M.h(d,$CLJS.bQ);$CLJS.K(c,2,null);c=F5(a,b,c);c=$CLJS.m(d)?$CLJS.U.j(c,$CLJS.E5,d):c;return $CLJS.$0.j(a,b,c)});$CLJS.y0.o(null,$CLJS.xV,function(a,b,c){a=$CLJS.Uf(c);b=$CLJS.M.h(a,$CLJS.V);return $CLJS.U.j(a,$CLJS.V,b)});
$CLJS.y0.o(null,$CLJS.PP,function(a,b,c){$CLJS.K(c,0,null);var d=$CLJS.K(c,1,null),e=$CLJS.Uf(d),f=$CLJS.M.h(e,$CLJS.EK),g=$CLJS.M.h(e,$CLJS.LF),l=$CLJS.M.h(e,$CLJS.bR),n=$CLJS.M.h(e,$CLJS.qk);d=$CLJS.M.h(e,$CLJS.yP);var q=$CLJS.M.h(e,$CLJS.gO),u=$CLJS.M.h(e,$CLJS.bQ),v=F5(a,b,c),x=$CLJS.mn.l;f=new $CLJS.k(null,2,[$CLJS.wl,$CLJS.xV,$CLJS.L1,f],null);e=$CLJS.YH.g(e);b=$CLJS.m(e)?e:$CLJS.z0.j(a,b,c);b=x.call($CLJS.mn,$CLJS.J([f,v,new $CLJS.k(null,1,[$CLJS.YH,b],null),$CLJS.m(n)?new $CLJS.k(null,1,[$CLJS.qk,
n],null):null,$CLJS.m(g)?new $CLJS.k(null,1,[$CLJS.LF,g],null):null,$CLJS.m(u)?new $CLJS.k(null,1,[$CLJS.E5,u],null):null,$CLJS.m(l)?new $CLJS.k(null,1,[$CLJS.D5,l],null):null,$CLJS.m(q)?new $CLJS.k(null,1,[$CLJS.vQ,q],null):null]));d=$CLJS.m(d)?$CLJS.D3(b,d):b;return $CLJS.m(L5.g(d))?N5(a,d):d});
$CLJS.V0.o(null,$CLJS.xV,function(a,b,c,d){c=$CLJS.Uf(c);var e=$CLJS.M.h(c,$CLJS.YH),f=$CLJS.M.h(c,$CLJS.V),g=$CLJS.M.h(c,$CLJS.bk),l=$CLJS.M.h(c,$CLJS.D5),n=$CLJS.M.h(c,$CLJS.g0),q=$CLJS.M.h(c,$CLJS.vQ),u=$CLJS.M.h(c,$CLJS.N_);e=$CLJS.m(e)?e:$CLJS.Y4.h($CLJS.X4,f);$CLJS.F.h(d,$CLJS.A0)&&-1==e.indexOf(" → ")?($CLJS.m(q)?(q=$CLJS.x3(a,q),$CLJS.m(q)?a=(0,$CLJS.Ca)($CLJS.zu($CLJS.YH.g($CLJS.C0.j(a,b,q)),$CLJS.Q_,"")):(u=$CLJS.H5(a,u),a=$CLJS.z0.C(a,b,u,d))):a=null,n=$CLJS.m(a)?a:$CLJS.m(n)?n:$CLJS.C3(c)):
n=null;n=$CLJS.m(n)?[$CLJS.p.g(n)," → ",$CLJS.p.g(e)].join(""):e;return $CLJS.m(g)?(c=$CLJS.uF($CLJS.zu($CLJS.Ai(g),"-"," ")),$CLJS.xa.j?$CLJS.xa.j("%s: %s",n,c):$CLJS.xa.call(null,"%s: %s",n,c)):$CLJS.m(l)?(c=$CLJS.P4(l,c),$CLJS.xa.j?$CLJS.xa.j("%s: %s",n,c):$CLJS.xa.call(null,"%s: %s",n,c)):n});
$CLJS.V0.o(null,$CLJS.PP,function(a,b,c,d){$CLJS.K(c,0,null);var e=$CLJS.K(c,1,null),f=$CLJS.Uf(e);e=$CLJS.M.h(f,$CLJS.bR);var g=$CLJS.M.h(f,$CLJS.yP),l=$CLJS.M.h(f,$CLJS.bQ);f=$CLJS.M.h(f,$CLJS.gO);$CLJS.K(c,2,null);c=F5(a,b,c);c=$CLJS.m(g)?$CLJS.U.j(c,$CLJS.g0,g):c;l=$CLJS.m(l)?$CLJS.U.j(c,$CLJS.bk,l):c;e=$CLJS.m(e)?$CLJS.U.j(l,$CLJS.D5,e):l;e=$CLJS.m(f)?$CLJS.U.j(e,$CLJS.vQ,f):e;return $CLJS.m(e)?$CLJS.z0.C(a,b,e,d):$CLJS.bH("[Unknown Field]")});
$CLJS.W0.o(null,$CLJS.xV,function(a,b,c){a=$CLJS.Uf(c);return $CLJS.M.h(a,$CLJS.V)});$CLJS.W0.o(null,$CLJS.PP,function(a,b,c){$CLJS.K(c,0,null);$CLJS.K(c,1,null);c=F5(a,b,c);return $CLJS.m(c)?$CLJS.X0.j(a,b,c):"unknown_field"});
$CLJS.a1.o(null,$CLJS.xV,function(a,b,c){return $CLJS.mn.l($CLJS.J([function(){var d=$CLJS.yj($CLJS.a1,$CLJS.Uj);return d.j?d.j(a,b,c):d.call(null,a,b,c)}(),$CLJS.F.h($CLJS.J_.g(c),$CLJS.b0)?function(){var d=$CLJS.b5.g(c);return $CLJS.m(d)?(d=$CLJS.x0(a,d),$CLJS.m(d)?new $CLJS.k(null,1,[$CLJS.O_,new $CLJS.k(null,2,[$CLJS.V,$CLJS.V.g(d),$CLJS.YH,$CLJS.V.g(d)],null)],null):null):null}():null]))});$CLJS.O1.o(null,$CLJS.PP,function(a){$CLJS.K(a,0,null);var b=$CLJS.K(a,1,null);$CLJS.K(a,2,null);return $CLJS.bQ.g(b)});
$CLJS.O1.o(null,$CLJS.xV,function(a){return $CLJS.E5.g(a)});
$CLJS.N1.o(null,$CLJS.PP,function(a,b){$CLJS.K(a,0,null);var c=$CLJS.K(a,1,null);a=$CLJS.K(a,2,null);if($CLJS.m(b)){var d=$CLJS.Ie($CLJS.kV,b),e=$CLJS.Tm.j(M5,$CLJS.qk,$CLJS.LF)(c);c=$CLJS.U.l(c,$CLJS.bQ,b,$CLJS.J([$CLJS.qk,d?$CLJS.nl:e,M5,e]));return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,c,a],null)}b=M5.g(c);c=$CLJS.m(b)?$CLJS.Jm.h($CLJS.U.j(c,$CLJS.qk,b),M5):c;c=$CLJS.Jm.h(c,$CLJS.bQ);return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,c,a],null)});
$CLJS.N1.o(null,$CLJS.xV,function(a,b){return $CLJS.m(b)?$CLJS.U.j(a,$CLJS.E5,b):$CLJS.Jm.h(a,$CLJS.E5)});$CLJS.P1.o(null,$CLJS.PP,function(a,b,c){return $CLJS.J5.j(a,b,F5(a,b,c))});
$CLJS.P1.o(null,$CLJS.xV,function(a,b,c){if($CLJS.qi.h($CLJS.J_.g(c),$CLJS.X_)){a=$CLJS.Tm.h($CLJS.qk,$CLJS.LF)(c);b=null==c?null:$CLJS.qO.g(c);if(null==b)var d=null;else try{var e=$CLJS.YI.g($CLJS.al.g(b));if($CLJS.m(e)){var f=$CLJS.Uf(e),g=$CLJS.M.h(f,Osa),l=$CLJS.M.h(f,Psa),n=$CLJS.Gsa.l($CLJS.J([$CLJS.w5.g(g),$CLJS.w5.g(l)]));d=isNaN(n)?null:$CLJS.m($CLJS.Vs.h?$CLJS.Vs.h(1,n):$CLJS.Vs.call(null,1,n))?$CLJS.mz:$CLJS.m($CLJS.Vs.h?$CLJS.Vs.h(31,n):$CLJS.Vs.call(null,31,n))?$CLJS.oz:$CLJS.m($CLJS.Vs.h?
$CLJS.Vs.h(365,n):$CLJS.Vs.call(null,365,n))?$CLJS.cl:$CLJS.ol}else d=null}catch(q){if(q instanceof Error)d=null;else throw q;}e=$CLJS.XG(a,$CLJS.YI)?$CLJS.Opa:$CLJS.XG(a,$CLJS.UH)?$CLJS.Npa:$CLJS.XG(a,$CLJS.eK)?$CLJS.Mpa:$CLJS.Rg;d=$CLJS.m(d)?I5(e,$CLJS.Uj,d):e;return $CLJS.m($CLJS.E5.g(c))?I5(d,$CLJS.H0,$CLJS.E5.g(c)):d}return $CLJS.Rg});
$CLJS.S4.o(null,$CLJS.PP,function(a){var b=null==a?null:$CLJS.HK(a);b=null==b?null:$CLJS.bR.g(b);return null==b?null:$CLJS.U.l(b,$CLJS.wl,$CLJS.Q4,$CLJS.J([$CLJS.V_,function(c,d){return F5(c,d,a)}]))});$CLJS.S4.o(null,$CLJS.xV,function(a){var b=null==a?null:$CLJS.D5.g(a);return null==b?null:$CLJS.U.l(b,$CLJS.wl,$CLJS.Q4,$CLJS.J([$CLJS.V_,$CLJS.eg(a)]))});$CLJS.R4.o(null,$CLJS.PP,function(a,b){return $CLJS.tV(a,$CLJS.sV,$CLJS.J([$CLJS.bR,b]))});
$CLJS.R4.o(null,$CLJS.xV,function(a,b){return $CLJS.sV(a,$CLJS.D5,b)});$CLJS.T4.o(null,$CLJS.PP,function(a,b,c){return $CLJS.K5.j(a,b,F5(a,b,c))});
$CLJS.T4.o(null,$CLJS.xV,function(a,b,c){b=$CLJS.Uf(c);c=$CLJS.M.h(b,$CLJS.qk);var d=$CLJS.M.h(b,$CLJS.qO),e=$CLJS.M.h(b,$CLJS.Pl);if($CLJS.qi.h($CLJS.J_.g(b),$CLJS.X_)){var f=function(){var n=null==a?null:$CLJS.v3($CLJS.v0(a));n=null==n?null:$CLJS.Ou.g(n);return null==n?null:$CLJS.Ie(n,$CLJS.bR)}(),g=$CLJS.vu(d,new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.al,$CLJS.Jl],null)),l=$CLJS.A5(b);return function u(q){return new $CLJS.Af(null,function(){for(;;){var v=$CLJS.A(q);if(v){if($CLJS.re(v)){var x=$CLJS.$c(v),
z=$CLJS.E(x),B=$CLJS.Df(z);return function(){for(var I=0;;)if(I<z){var T=$CLJS.be(x,I),W=B,ba=T;T=B5(T,l)?$CLJS.U.j(ba,$CLJS.H0,!0):ba;W.add(T);I+=1}else return!0}()?$CLJS.If($CLJS.Kf(B),u($CLJS.ad(v))):$CLJS.If($CLJS.Kf(B),null)}var H=$CLJS.C(v);return $CLJS.pf(function(){var I=H;return B5(H,l)?$CLJS.U.j(I,$CLJS.H0,!0):I}(),u($CLJS.zd(v)))}return null}},null,null)}($CLJS.Fb(function(){if($CLJS.m(f)){var q=$CLJS.vk.g(g);return $CLJS.m(q)?$CLJS.cm.g(g):q}return f}())?null:$CLJS.XG(e,$CLJS.ql)?$CLJS.r($CLJS.asa):
$CLJS.XG(c,$CLJS.Jl)&&!$CLJS.XG(e,$CLJS.Vj)?$CLJS.r($CLJS.$ra):null)}return $CLJS.Rg});$CLJS.rV.o(null,$CLJS.PP,function(a){return a});
$CLJS.rV.o(null,$CLJS.xV,function(a){var b=$CLJS.Uf(a);a=$CLJS.M.h(b,$CLJS.J_);switch(a instanceof $CLJS.N?a.N:null){case "source/aggregations":return Hsa(b);case "source/expressions":return Jsa(b);default:a=function(){var d=$CLJS.J_.g(b),e=new $CLJS.ti(null,new $CLJS.k(null,3,[$CLJS.b0,null,$CLJS.d0,null,$CLJS.U_,null],null),null);return e.g?e.g(d):e.call(null,d)}();var c=$CLJS.mn.l($CLJS.J([new $CLJS.k(null,3,[$CLJS.EK,$CLJS.p.g($CLJS.IK()),$CLJS.LF,$CLJS.LF.g(b),$CLJS.qk,G5(b)],null),function(){var d=
$CLJS.C3(b);return $CLJS.m(d)?new $CLJS.k(null,1,[$CLJS.yP,d],null):null}(),function(){var d=$CLJS.E5.g(b);return $CLJS.m(d)?new $CLJS.k(null,1,[$CLJS.bQ,d],null):null}(),function(){var d=$CLJS.D5.g(b);return $CLJS.m(d)?new $CLJS.k(null,1,[$CLJS.bR,d],null):null}(),function(){var d=$CLJS.vQ.g(b);return $CLJS.m(d)?new $CLJS.k(null,1,[$CLJS.gO,d],null):null}()]));return new $CLJS.R(null,3,5,$CLJS.S,[$CLJS.PP,c,$CLJS.m(a)?function(){var d=$CLJS.$_.g(b);return $CLJS.m(d)?d:$CLJS.V.g(b)}():function(){var d=
$CLJS.Lk.g(b);return $CLJS.m(d)?d:$CLJS.V.g(b)}()],null)}});