var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./schema.utils.js");require("./schema.spec.core.js");
'use strict';var JL,KL,DL;
$CLJS.aha=function(a,b,c){var d=$CLJS.CL.g(a),e=$CLJS.xL(a,b),f=$CLJS.m(d)?function(l){try{var n=d.g?d.g(l):d.call(null,l)}catch(q){if(q instanceof Object)n=DL;else throw q;}return $CLJS.F.h(DL,n)?$CLJS.pL($CLJS.kL($CLJS.hm.g(a),l,new $CLJS.dj(function(){return new $CLJS.jf(null,$CLJS.$i.g($CLJS.gL(d)),new $CLJS.jf(null,$CLJS.fL(l),null,1,null),2,null)}),$CLJS.sL)):$CLJS.m(n)?e.g?e.g(l):e.call(null,l):c.g?c.g(l):c.call(null,l)}:e,g=$CLJS.EL.g(a);return $CLJS.m(g)?function(l){l=f.g?f.g(l):f.call(null,
l);var n=$CLJS.rL(l);return $CLJS.m(n)?$CLJS.pL(g.g?g.g(n):g.call(null,n)):l}:f};$CLJS.FL=function(a,b,c,d,e,f,g){this.na=a;this.options=b;this.Yb=c;this.Rb=d;this.F=e;this.m=f;this.G=g;this.D=2230716170;this.K=139264};$CLJS.HL=function(a,b){return $CLJS.GL(a,b,null)};$CLJS.GL=function(a,b,c){return $CLJS.IL(a,b,c,null)};
$CLJS.IL=function(a,b,c,d){if(!$CLJS.m($CLJS.m(c)?c:null==$CLJS.CL.g($CLJS.$d(b))))throw Error($CLJS.eL("when last option has a guard, err-f must be provided"));return new $CLJS.FL(a,b,c,d,null,null,null)};JL=new $CLJS.N(null,"err-f","err-f",651620941);KL=new $CLJS.N(null,"post","post",269697687);DL=new $CLJS.N("schema.spec.variant","exception","schema.spec.variant/exception",-253680523);$CLJS.EL=new $CLJS.N(null,"wrap-error","wrap-error",536732809);$CLJS.CL=new $CLJS.N(null,"guard","guard",-873147811);$CLJS.h=$CLJS.FL.prototype;$CLJS.h.ka=function(a,b){return this.U(null,b,null)};$CLJS.h.U=function(a,b,c){switch(b instanceof $CLJS.N?b.N:null){case "pre":return this.na;case "options":return this.options;case "err-f":return this.Yb;case "post":return this.Rb;default:return $CLJS.M.j(this.m,b,c)}};$CLJS.h.va=function(a,b,c){return $CLJS.Tb(function(d,e){var f=$CLJS.K(e,0,null);e=$CLJS.K(e,1,null);return b.j?b.j(d,f,e):b.call(null,d,f,e)},c,this)};$CLJS.h.Nd=$CLJS.La(55);
$CLJS.h.W=function(a,b,c){return $CLJS.Oi(b,function(d){return $CLJS.Oi(b,$CLJS.Ti,""," ","",c,d)},"#schema.spec.variant.VariantSpec{",", ","}",c,$CLJS.wg.h(new $CLJS.R(null,4,5,$CLJS.S,[new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.zL,this.na],null),new $CLJS.R(null,2,5,$CLJS.S,[$CLJS.Sk,this.options],null),new $CLJS.R(null,2,5,$CLJS.S,[JL,this.Yb],null),new $CLJS.R(null,2,5,$CLJS.S,[KL,this.Rb],null)],null),this.m))};
$CLJS.h.oa=function(){return new $CLJS.jh(this,4,new $CLJS.R(null,4,5,$CLJS.S,[$CLJS.zL,$CLJS.Sk,JL,KL],null),$CLJS.m(this.m)?$CLJS.fd(this.m):$CLJS.Xf())};$CLJS.h.M=function(){return this.F};$CLJS.h.ea=function(){return 4+$CLJS.E(this.m)};$CLJS.h.ca=function(){var a=this.G;return null!=a?a:this.G=a=-1524878868^$CLJS.Ed(this)};
$CLJS.h.T=function(a,b){return null!=b&&this.constructor===b.constructor&&$CLJS.F.h(this.na,b.na)&&$CLJS.F.h(this.options,b.options)&&$CLJS.F.h(this.Yb,b.Yb)&&$CLJS.F.h(this.Rb,b.Rb)&&$CLJS.F.h(this.m,b.m)};$CLJS.h.za=function(a,b){return $CLJS.Ie(new $CLJS.ti(null,new $CLJS.k(null,4,[$CLJS.zL,null,JL,null,KL,null,$CLJS.Sk,null],null),null),b)?$CLJS.Jm.h($CLJS.Dc($CLJS.th.h($CLJS.P,this),this.F),b):new $CLJS.FL(this.na,this.options,this.Yb,this.Rb,this.F,$CLJS.Vf($CLJS.Jm.h(this.m,b)),null)};
$CLJS.h.ta=function(a,b){switch(b instanceof $CLJS.N?b.N:null){case "pre":case "options":case "err-f":case "post":return!0;default:return $CLJS.Ie(this.m,b)}};
$CLJS.h.$=function(a,b,c){return $CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.zL,b):$CLJS.O.call(null,$CLJS.zL,b))?new $CLJS.FL(c,this.options,this.Yb,this.Rb,this.F,this.m,null):$CLJS.m($CLJS.O.h?$CLJS.O.h($CLJS.Sk,b):$CLJS.O.call(null,$CLJS.Sk,b))?new $CLJS.FL(this.na,c,this.Yb,this.Rb,this.F,this.m,null):$CLJS.m($CLJS.O.h?$CLJS.O.h(JL,b):$CLJS.O.call(null,JL,b))?new $CLJS.FL(this.na,this.options,c,this.Rb,this.F,this.m,null):$CLJS.m($CLJS.O.h?$CLJS.O.h(KL,b):$CLJS.O.call(null,KL,b))?new $CLJS.FL(this.na,
this.options,this.Yb,c,this.F,this.m,null):new $CLJS.FL(this.na,this.options,this.Yb,this.Rb,this.F,$CLJS.U.j(this.m,b,c),null)};$CLJS.h.da=function(){return $CLJS.A($CLJS.wg.h(new $CLJS.R(null,4,5,$CLJS.S,[new $CLJS.Ke($CLJS.zL,this.na),new $CLJS.Ke($CLJS.Sk,this.options),new $CLJS.Ke(JL,this.Yb),new $CLJS.Ke(KL,this.Rb)],null),this.m))};$CLJS.h.O=function(a,b){return new $CLJS.FL(this.na,this.options,this.Yb,this.Rb,b,this.m,this.G)};
$CLJS.h.ja=function(a,b){return $CLJS.qe(b)?this.$(null,$CLJS.be(b,0),$CLJS.be(b,1)):$CLJS.Tb($CLJS.dc,this,b)};