/** @const {ShadowJS} */ var Intl;
/** @const {ShadowJS} */ var TextEncoder;
/** @const {ShadowJS} */ var URL;
/** @const {ShadowJS} */ var Uint8Array;
/** @const {ShadowJS} */ var decodeURIComponent;
/** @const {ShadowJS} */ var devtools;
/** @const {ShadowJS} */ var encodeURI;
/** @const {ShadowJS} */ var module;
ShadowJS.prototype.ISO_8601;
ShadowJS.prototype.MAX_SAFE_INTEGER;
ShadowJS.prototype.MAX_VALUE;
ShadowJS.prototype.MIN_SAFE_INTEGER;
ShadowJS.prototype.Moment;
ShadowJS.prototype.NEGATIVE_INFINITY;
ShadowJS.prototype.NaN;
ShadowJS.prototype.NumberFormat;
ShadowJS.prototype.POSITIVE_INFINITY;
ShadowJS.prototype.core;
ShadowJS.prototype.date;
ShadowJS.prototype.dayOfYear;
ShadowJS.prototype.diff;
ShadowJS.prototype.endOf;
ShadowJS.prototype.entry_set;
ShadowJS.prototype.equiv;
ShadowJS.prototype.floor;
ShadowJS.prototype.fromCharCode;
ShadowJS.prototype.getLength;
ShadowJS.prototype.installed_QMARK_;
ShadowJS.prototype.isMoment;
ShadowJS.prototype.isSame;
ShadowJS.prototype.isValid;
ShadowJS.prototype.isoWeekday;
ShadowJS.prototype.key_set;
ShadowJS.prototype.keys;
ShadowJS.prototype.log;
ShadowJS.prototype.msgid;
ShadowJS.prototype.navigator;
ShadowJS.prototype.ngettext;
ShadowJS.prototype.now;
ShadowJS.prototype.parseZone;
ShadowJS.prototype.quarter;
ShadowJS.prototype.setCapturing;
ShadowJS.prototype.setEnabled;
ShadowJS.prototype.startOf;
ShadowJS.prototype.str;
ShadowJS.prototype.t;
ShadowJS.prototype.userAgent;
ShadowJS.prototype.utc;
ShadowJS.prototype.value_set;
ShadowJS.prototype.week;
ShadowJS.prototype.weekdays;